#!moo verb no_go_tell --on "Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: NO-GO-TELL
# params: AV, WLOC

av = args[0] if len(args) > 0 else None
wloc = args[1] if len(args) > 1 else None

if av:
    print("You can't go there in a " + wloc.desc() + ".", end="")
else:
    print("You can't go there without a vehicle.", end="")
print()
return
