#!moo verb tell_no_prsi --on "Thing" --dspec this

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: TELL-NO-PRSI

print("You didn't say with what!")
return
