#!moo verb with_tell --on "Thing" --dspec this

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: WITH-TELL
# params: OBJ

obj = args[0] if len(args) > 0 else None

print("With a " + obj.desc() + "?")
return
