#!moo verb iboat_function --on "pile of plastic" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, lookup

# ZIL: IBOAT-FUNCTION / combined OBJECT-FUNCTION dispatch
# Invoked by ``_.thing.dispatch_object_function(obj, verb, prep, iobj)``
# which looks up ``obj.action`` and calls ``obj.invoke_verb(action_atom, ...)``.

player = context.player
parser = context.parser
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
inflated_boat = lookup("inflated_boat")
the_verb = args[0] if len(args) > 0 else None
prep = args[1] if len(args) > 1 else None
iobj = args[2] if len(args) > 2 else None
the_player_verb = the_verb

if the_verb == "inflate" or the_verb == "fill":
    if not this.location == player.here():
        print("The boat must be on the ground to be inflated.")
        return
    elif prsi == lookup("pump"):
        print("The boat inflates and appears seaworthy.")
        if not lookup("boat_label").flag("touchbit"):
            print("A tan label is lying inside the boat.")
        player.zstate_set("DEFLATE", False)
        _.remove(this)
        inflated_boat.moveto(player.here())
        # ZIL: <THIS-IS-IT ...>
        return _.thing.this_is_it(inflated_boat)
    elif prsi == lookup("lungs"):
        print("You don't have enough lung power to inflate it.")
        return
    else:
        print("With a " + (prsi.desc() if prsi else "") + "? Surely you jest!")
        return
return False
