#!moo verb inflate fill --on "pile of plastic" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, invoked_verb_name, lookup

# ZIL routine: IBOAT-FUNCTION (inflate/fill branch)

player = context.player
parser = context.parser
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
inflated_boat = lookup("inflated_boat")
the_player_verb = invoked_verb_name(verb_name)

if not this.location == player.here():
    print("The boat must be on the ground to be inflated.")
    return
elif prsi == lookup("pump"):
    print("The boat inflates and appears seaworthy.")
    if not lookup("boat_label").flag("touchbit"):
        print("A tan label is lying inside the boat.")
    player.zstate_set("DEFLATE", False)
    _.remove(this)
    inflated_boat.moveto(player.here())
    # ZIL: <THIS-IS-IT ...>
    return _.zork_thing.this_is_it(inflated_boat)
elif prsi == lookup("lungs"):
    print("You don't have enough lung power to inflate it.")
    return
else:
    print("With a " + (prsi.desc() if prsi else "") + "? Surely you jest!")
    return
