#!moo verb chain_pseudo --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: CHAIN-PSEUDO

the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if the_player_verb in ["take", "get", "pick", "move"]:
    print("The chain is secure.")
    return
elif the_player_verb in ["raise", "lower"]:
    print("Perhaps you should do that to the basket.")
    return
elif the_player_verb in ["examine", "x", "describe", "what"]:
    print("The chain secures a basket within the shaft.")
    return
