#!moo verb door_pseudo --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: DOOR-PSEUDO

player = context.player
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if the_player_verb in ["open", "close", "shut"]:
    print("The door won't budge.")
    return
elif the_player_verb == "through":
    return _.walk(player.zstate_get("P?SOUTH"))
