#!moo verb door_pseudo --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name

# ZIL routine: DOOR-PSEUDO

player = context.player
the_player_verb = invoked_verb_name(verb_name)

if the_player_verb in ["open", "close", "shut"]:
    print("The door won't budge.")
    return
elif the_player_verb == "through":
    return _.walk(player.zstate_get("P?SOUTH"))
