#!moo verb nails_pseudo --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import invoked_verb_name

# ZIL routine: NAILS-PSEUDO

the_player_verb = invoked_verb_name(verb_name)

if the_player_verb in ["take", "get", "pick"]:
    print("The nails, deeply imbedded in the door, cannot be removed.")
    return
