#!moo verb attack cut fight hit kill slice stab swing --on "rusty knife" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: RUSTY-KNIFE-FCN

parser = context.parser
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if (
    (parser.get_iobj() if parser.has_iobj() else None) == this
    and the_player_verb in ["attack", "kill", "hit", "fight", "stab", "cut", "slice"]
) or (
    the_player_verb == "swing"
    and (parser.get_dobj() if parser.has_dobj_str() else None) == this
    and (parser.get_iobj() if parser.has_iobj() else None)
):
    _.remove(this)
    return _.jigs_up(
        "As the knife approaches its victim, your mind is submerged by an\novermastering will. Slowly, your hand turns, until the rusty blade\nis an inch from your neck. The knife seems to sing as it savagely\nslits your throat."
    )
return passthrough()
