#!moo verb take get pick --on "rusty knife" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name, lookup

# ZIL routine: RUSTY-KNIFE-FCN (take branch)

player = context.player
the_player_verb = invoked_verb_name(verb_name)

if lookup("sword").location == player:
    print("As you touch the rusty knife, your sword gives a single pulse of blinding\nblue light.")
return passthrough()
