#!moo verb pour spill --on "Thing" --dspec any --ispec from:any

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

"""Syntax-row dispatcher for pour OBJECT FROM OBJECT.

Generated by moo/zil_import — see :doc:`/reference/zil-importer`.

Action chain (any callback returning truthy short-circuits):
  1. dobj OBJECT-FUNCTION pre-phase
  2. iobj OBJECT-FUNCTION pre-phase
  3. ROOM-FUNCTION M-BEG
  4. Substrate verb: _.thing.v_drop()
  5. ROOM-FUNCTION M-END

Option A delegation: the substrate is rewritten to ``--dspec none`` by
the generator's post-emission pass so it never parser-matches; this
runner is the only parser entry point, and it calls the substrate
programmatically via :func:`invoke_verb` to preserve hand-written
per-object pre-action logic (e.g. take.py's pot-of-gold rainbow gate).
"""

from moo.sdk import context

parser = context.parser
dobj = parser.get_dobj() if parser.has_dobj_str() else None
if dobj is None:
    print("Pour what?")
    return
iobj = parser.get_pobj("from") if parser.has_pobj_str("from") else None
if iobj is None:
    print("Pour OBJECT from what?")
    return


# 1. dobj OBJECT-FUNCTION pre-phase
if _.thing.dispatch_object_function(dobj, "pour", "from", iobj, "pre"):
    return

# 2. iobj OBJECT-FUNCTION pre-phase
if _.thing.dispatch_object_function(iobj, "pour", "from", dobj, "pre-iobj"):
    return

# 3. ROOM-FUNCTION M-BEG
loc = context.player.location
if _.room.dispatch_room_function(loc, "M-BEG", "pour", dobj, iobj):
    return

# 4. Substrate (parser-inert under Option A)
result = _.thing.v_drop()

# 5. ROOM-FUNCTION M-END
_.room.dispatch_room_function(loc, "M-END", "pour", dobj, iobj)

return result
