#!moo verb look --on "Torch Room" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL: TORCH-ROOM-FCN / M-LOOK

player = context.player
parser = context.parser
rarg = args[0] if len(args) > 0 else "M-LOOK"
the_player_verb = (
    args[1]
    if len(args) > 1
    else (parser.words[0].lower() if context.parser is not None and parser.words else verb_name)
)

print(
    "This is a large room with a prominent doorway leading to a down\nstaircase. Above you is a large dome. Up around the edge of the\ndome (20 feet up) is a wooden railing. In the center of the room\nsits a white marble pedestal."
)
if player.zstate_get("DOME-FLAG"):
    print("A piece of rope descends from the railing above, ending some\nfive feet above your head.")
_.zork_thing.describe_objects(True)
