#!moo verb torch_room_fcn look --on "Torch Room" --dspec either

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name

# ZIL: TORCH-ROOM-FCN / combined M-/F-clause dispatch

player = context.player
verb_to_const = {"look": "M-LOOK"}
rarg = args[0] if len(args) > 0 else verb_to_const.get(verb_name, "M-LOOK")
the_player_verb = args[1] if len(args) > 1 else invoked_verb_name(verb_name)

if rarg == "M-LOOK":
    print(this.desc())
    print(
        "This is a large room with a prominent doorway leading to a down\nstaircase. Above you is a large dome. Up around the edge of the\ndome (20 feet up) is a wooden railing. In the center of the room\nsits a white marble pedestal."
    )
    if player.zstate_get("DOME-FLAG"):
        print("A piece of rope descends from the railing above, ending some\nfive feet above your head.")
    _.thing.describe_objects(True)
