#!moo verb water_f --on "water" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context

# ZIL: WATER-F / combined OBJECT-FUNCTION dispatch
# Invoked by ``_.thing.dispatch_object_function(obj, verb, prep, iobj)``
# which looks up ``obj.action`` and calls ``obj.invoke_verb(action_atom, ...)``.

player = context.player
parser = context.parser
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
the_verb = args[0] if len(args) > 0 else None
prep = args[1] if len(args) > 1 else None
iobj = args[2] if len(args) > 2 else None
av = 0
w = 0
pi_p = 0
the_player_verb = the_verb

if the_verb == "through" or the_verb == "board":
    print(_.pick(player.zstate_get("SWIMYUKS")))
    return True
elif the_verb == "fill":
    w = prsi
    # SETG of parser-state slot is a no-op in DjangoMOO
    # SETG of parser-state slot is a no-op in DjangoMOO
    # SETG of parser-state slot is a no-op in DjangoMOO
    pi_p = False
return False
