#!moo verb chalice_fcn --on "chalice" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, lookup

# ZIL: CHALICE-FCN / combined OBJECT-FUNCTION dispatch
# Invoked by ``_.thing.dispatch_object_function(obj, verb, prep, iobj)``
# which looks up ``obj.action`` and calls ``obj.invoke_verb(action_atom, ...)``.

player = context.player
parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
thief = lookup("thief")
treasure_room = lookup("treasure_room")
the_verb = args[0] if len(args) > 0 else None
prep = args[1] if len(args) > 1 else None
iobj = args[2] if len(args) > 2 else None
the_player_verb = the_verb

if the_verb == "take":
    if (
        (prso is not None and prso.location == treasure_room)
        and thief.location == treasure_room
        and thief.flag("hostile")
        and not thief.flag("invisible")
        and not thief.getp("description") == player.zstate_get("ROBBER-U-DESC")
    ):
        print("You'd be stabbed in the back first.")
        return
elif the_verb == "put":
    if prsi == this:
        print("You can't. It's not a very good chalice, is it?")
        return
return False
