#!moo verb chalice_fcn --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: CHALICE-FCN

parser = context.parser

if verb_name in ["open", "close", "shut", "look-inside"]:
    print("You can't do that.")
    return
elif verb_name in ["examine", "x", "describe", "what"]:
    print("It looks pretty much like a " + parser.get_dobj().desc() + ".")
    return
return passthrough()
