#!moo verb put place insert --on "chalice" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, invoked_verb_name

# ZIL routine: CHALICE-FCN (put branch)

parser = context.parser
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
the_player_verb = invoked_verb_name(verb_name)

if prsi == this:
    print("You can't. It's not a very good chalice, is it?")
    return
return passthrough()
