#!moo verb take get pick --on "chalice" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, invoked_verb_name, lookup

# ZIL routine: CHALICE-FCN (take branch)

player = context.player
parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
thief = lookup("thief")
treasure_room = lookup("treasure_room")
the_player_verb = invoked_verb_name(verb_name)

if (
    prso.location == treasure_room
    and thief.location == treasure_room
    and thief.flag("hostile")
    and not thief.flag("invisible")
    and not thief.getp("description") == player.zstate_get("ROBBER-U-DESC")
):
    print("You'd be stabbed in the back first.")
    return
return passthrough()
