#!moo verb open close shut --on "trap door" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: TRAP-DOOR-FCN (open/close branch)

player = context.player
parser = context.parser
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if player.here() == lookup("living_room"):
    # ZIL: <OPEN-CLOSE ...>
    return _.zork_thing.open_close(
        (parser.get_dobj() if parser.has_dobj_str() else None),
        "The door reluctantly opens to reveal a rickety staircase descending into\ndarkness.",
        "The door swings shut and closes.",
    )
return passthrough()
