#!moo verb trap_door_fcn --on "trap door" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, lookup

# ZIL: TRAP-DOOR-FCN / combined OBJECT-FUNCTION dispatch
# Invoked by ``_.thing.dispatch_object_function(obj, verb, prep, iobj)``
# which looks up ``obj.action`` and calls ``obj.invoke_verb(action_atom, ...)``.

player = context.player
parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
living_room = lookup("living_room")
the_verb = args[0] if len(args) > 0 else None
prep = args[1] if len(args) > 1 else None
iobj = args[2] if len(args) > 2 else None
the_player_verb = the_verb

if the_verb == "raise":
    _.perform("open", this, None)
    return True
elif the_verb == "open" or the_verb == "close":
    if player.here() == living_room:
        # ZIL: <OPEN-CLOSE ...>
        return _.thing.open_close(
            prso,
            "The door reluctantly opens to reveal a rickety staircase descending into\ndarkness.",
            "The door swings shut and closes.",
        )
elif the_verb == "look_under":
    if player.here() == living_room:
        if this.flag("open"):
            print("You see a rickety staircase descending into darkness.")
            return
        else:
            print("It's closed.")
            return
return False
