#!moo verb answer reply --on "Actor" --dspec either

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

"""Player command for ANSWER: dispatch by object slot."""

from moo.sdk import context

if context.parser.has_dobj_str() and context.parser.dobj is not None:
    _.thing.reply()
else:
    _.thing.answer()
