#!moo verb extinguish douse --on "Actor" --dspec any

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

"""Player command for EXTINGUISH: delegate to V-LAMP-OFF."""

_.thing.lamp_off()
