#!moo verb light activate burn incinerate ignite --on "Actor" --dspec any

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

"""Player command for LIGHT: delegate to V-LAMP-ON."""

from moo.sdk import context

# Compound verb dispatch: <verb> <particle> routes to a different V-routine.
# Two parser shapes: (a) particle was a registered prep — pull dobj from
# prepositions; (b) particle was bare — re-resolve from words[2:].
compound_table = {
    "light": {"down": "burn"},
    "activate": {"down": "burn"},
    "burn": {"down": "burn"},
    "incinerate": {"down": "burn"},
    "ignite": {"down": "burn"},
}
cmd_words = context.parser.words if context.parser is not None else []
if len(cmd_words) > 1:
    cmd_verb = cmd_words[0].lower()
    cmd_particle = cmd_words[1].lower()
    particle_table = compound_table.get(cmd_verb)
    if particle_table and cmd_particle in particle_table:
        # The particle word may have been mis-parsed as the
        # dobj (``lie down`` → dobj_str='down').  Clear it so
        # the substrate's "no dobj" prompt fires instead of
        # "There is no 'down' here."
        if context.parser.dobj is None and context.parser.dobj_str == cmd_particle:
            context.parser.dobj_str = None
        if context.parser.dobj is None:
            for prep_objects in context.parser.prepositions.values():
                for prep_record in prep_objects:
                    if prep_record[2] is not None:
                        context.parser.dobj = prep_record[2]
                        context.parser.dobj_str = prep_record[1]
                        break
                    if prep_record[1]:
                        # Prep had an obj_str but the parser didn't
                        # resolve it locally.  Try the player's
                        # location (global scenery resolves via
                        # resolve_dobj_late, which only ran on
                        # parser.dobj, not on prep-bound objects).
                        candidate = context.player.find(prep_record[1]).first()
                        if candidate is None and context.player.location is not None:
                            candidate = context.player.location.find(prep_record[1]).first()
                        if candidate is not None:
                            context.parser.dobj = candidate
                            context.parser.dobj_str = prep_record[1]
                            break
                        # Last resort: record the typed string so the
                        # substrate can emit a coherent "There is no
                        # 'X' here." rather than the bare prompt.
                        context.parser.dobj_str = prep_record[1]
                if context.parser.dobj is not None:
                    break
            if context.parser.dobj is None and len(cmd_words) > 2:
                target_str = " ".join(cmd_words[2:])
                resolved = context.player.find(target_str).first()
                if resolved is None and context.player.location is not None:
                    resolved = context.player.location.find(target_str).first()
                if resolved is not None:
                    context.parser.dobj = resolved
                    context.parser.dobj_str = target_str
        _.thing.invoke_verb(particle_table[cmd_particle])
        return

_.thing.lamp_on()
