#!moo verb push press move --on "brown button" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: BUTTON-F (push branch)

player = context.player
parser = context.parser
dam_room = lookup("dam_room")
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if (parser.get_dobj() if parser.has_dobj_str() else None) == lookup("blue_button"):
    if player.zstate_get("WATER-LEVEL") == 0:
        lookup("leak").set_flag("invisible", False)
        print(
            "There is a rumbling sound and a stream of water appears to burst\nfrom the east wall of the room (apparently, a leak has occurred in a\npipe)."
        )
        player.zstate_set("WATER-LEVEL", 1)
        return _.queue("i-maint-room", -1)
    else:
        print("The blue button appears to be jammed.")
        return
elif (parser.get_dobj() if parser.has_dobj_str() else None) == lookup("red_button"):
    print("The lights within the room ", end="")
    if player.here().flag("onbit"):
        player.here().set_flag("onbit", False)
        print("shut off.")
        return
    else:
        player.here().set_flag("onbit", True)
        print("come on.")
        return
elif (parser.get_dobj() if parser.has_dobj_str() else None) == this:
    dam_room.set_flag("touchbit", False)
    player.zstate_set("GATE-FLAG", False)
    print("Click.")
    return
elif (parser.get_dobj() if parser.has_dobj_str() else None) == lookup("yellow_button"):
    dam_room.set_flag("touchbit", False)
    player.zstate_set("GATE-FLAG", True)
    print("Click.")
    return
return passthrough()
