# Generated by extras/zil_import
import pytest
from moo.sdk import lookup

pytestmark = [
    pytest.mark.django_db(transaction=True, reset_sequences=True),
    pytest.mark.parametrize("t_init", ["zork1"], indirect=True),
]


class TestTakeables:
    def test_water_takeable(self, zork_world):
        o = lookup("quantity of water")
        assert o is not None
        assert o.get_property("takeable") is True

    def test_skull_takeable(self, zork_world):
        o = lookup("crystal skull")
        assert o is not None
        assert o.get_property("takeable") is True

    def test_lunch_takeable(self, zork_world):
        o = lookup("lunch")
        assert o is not None
        assert o.get_property("takeable") is True

    def test_bell_takeable(self, zork_world):
        o = lookup("brass bell")
        assert o is not None
        assert o.get_property("takeable") is True


class TestContainers:
    def test_book_is_container(self, zork_world):
        o = lookup("black book")
        assert o is not None
        parents = [p.name for p in o.parents.all()]
        assert any("Container" in p or "container" in p for p in parents)

    def test_kitchen_table_is_container(self, zork_world):
        o = lookup("kitchen table")
        assert o is not None
        parents = [p.name for p in o.parents.all()]
        assert any("Container" in p or "container" in p for p in parents)
        assert o.get_property("capacity") == 50

    def test_sandwich_bag_is_container(self, zork_world):
        o = lookup("brown sack")
        assert o is not None
        parents = [p.name for p in o.parents.all()]
        assert any("Container" in p or "container" in p for p in parents)
        assert o.get_property("capacity") == 9


class TestReadable:
    def test_book_readable(self, zork_world):
        o = lookup("black book")
        assert o is not None
        assert o.get_property("readable") is True

    def test_advertisement_readable(self, zork_world):
        o = lookup("leaflet")
        assert o is not None
        assert o.get_property("readable") is True
