# Generated by extras/zil_import
import pytest
from moo.sdk import lookup

pytestmark = [
    pytest.mark.django_db(transaction=True, reset_sequences=True),
    pytest.mark.parametrize("t_init", ["zork1"], indirect=True),
]


def test_exit_traversal_north(zork_world):
    room = lookup("West of House")
    exits = room.get_property("exits")
    matches = [e for e in exits if e.aliases.filter(alias="north").exists()]
    assert matches, "no north exit on West of House"
    dest = matches[0].get_property("dest")
    assert dest is not None
    assert dest.name == "North of House"


def test_blocked_exit_east(zork_world):
    room = lookup("West of House")
    exits = room.get_property("exits")
    matches = [e for e in exits if e.aliases.filter(alias="east").exists()]
    assert matches, "no east exit on West of House"
    blocked = matches[0]
    assert blocked.get_property("dest") is None
    assert blocked.get_property("nogo_msg")
