#!moo verb break crack describe destroy examine get give hear hello hi listen move mung pick smash take throw toss what x --on "troll" --dspec any --ispec on:this in:this at:this with:this from:this under:this over:this before:this around:this through:this behind:this beside:this

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

import random
from moo.sdk import NoSuchObjectError, context, invoked_verb_name, lookup

# ZIL routine: TROLL-FCN
# params: MODE

player = context.player
parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
axe = lookup("axe")
knife = lookup("knife")
sword = lookup("sword")
mode = args[0] if len(args) > 0 else None
the_player_verb = invoked_verb_name(verb_name)

if not mode:
    if the_player_verb in ["examine", "x", "describe", "what"]:
        print(this.getp("description"))
        return
    elif (the_player_verb in ["throw", "toss", "give"] and prso and prsi == this) or the_player_verb in [
        "take",
        "get",
        "pick",
        "move",
        "mung",
        "destroy",
        "break",
        "smash",
        "crack",
    ]:
        # ZIL: <AWAKEN ...>
        _.thing.awaken(this)
        if the_player_verb in ["throw", "toss", "give"]:
            if prso == axe and axe.location == player:
                print("The troll scratches his head in confusion, then takes the axe.")
                this.set_flag("hostile", True)
                axe.moveto(this)
                return True
            elif prso in (this, axe):
                print("You would have to get the " + (prso.desc() if prso else "") + " first, and that seems unlikely.")
                return True
            if the_player_verb in ["throw", "toss"]:
                print("The troll, who is remarkably coordinated, catches the " + (prso.desc() if prso else ""), end="")
            else:
                print("The troll, who is not overly proud, graciously accepts the gift", end="")
            if random.randint(1, 100) <= 20 and prso in (knife, sword, axe):
                _.remove(prso)
                print(
                    " and eats it hungrily. Poor troll, he dies from an internal hemorrhage\nand his carcass disappears in a sinister black fog."
                )
                _.remove(this)
                # ZIL: <APPLY ...>
                if this is not None and this.has_verb("f_dead", recurse=False):
                    this.invoke_verb("f_dead")
                return player.zstate_set("TROLL-FLAG", True)
            elif prso in (knife, sword, axe):
                prso.moveto(player.here())
                print(
                    " and, being for the moment sated, throws it back. Fortunately, the\ntroll has poor control, and the "
                    + (prso.desc() if prso else "")
                    + " falls to the floor. He does\nnot look pleased."
                )
                return this.set_flag("hostile", True)
            else:
                print(" and not having the most discriminating tastes, gleefully eats it.")
                return _.remove(prso)
        elif the_player_verb in ["take", "get", "pick", "move"]:
            print('The troll spits in your face, grunting "Better luck next time" in a\nrather barbarous accent.')
            return
        elif the_player_verb in ["mung", "destroy", "break", "smash", "crack"]:
            print("The troll laughs at your puny gesture.")
            return
    elif the_player_verb in ["listen", "hear"]:
        print("Every so often the troll says something, probably uncomplimentary, in\nhis guttural tongue.")
        return
    elif player.zstate_get("TROLL-FLAG") and the_player_verb in ["hello", "hi"]:
        print("Unfortunately, the troll can't hear you.")
        return
return passthrough()
