#!moo verb f_busy_p --on "troll" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

import random
from moo.sdk import context, lookup

# ZIL: TROLL-FCN / F-BUSY?

player = context.player
axe = lookup("axe")
mode = args[0] if len(args) > 0 else "F-BUSY?"

if axe.location == this:
    pass
elif axe.location == player.here() and random.randint(1, 100) <= 75:
    axe.set_flag("ndescbit", True)
    axe.set_flag("weapon", False)
    axe.moveto(this)
    this.set_property(
        "description", "A nasty-looking troll, brandishing a bloody axe, blocks all passages out\nof the room."
    )
    if this.location == player.here():
        print("The troll, angered and humiliated, recovers his weapon. He appears to have\nan axe to grind with you.")
elif this.location == player.here():
    this.set_property("description", "A pathetically babbling troll is here.")
    print("The troll, disarmed, cowers in terror, pleading for his life in\nthe guttural tongue of the trolls.")
