#!moo verb f_conscious --on "troll" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL: TROLL-FCN / F-CONSCIOUS

player = context.player
axe = lookup("axe")
mode = args[0] if len(args) > 0 else "F-CONSCIOUS"

if this.location == player.here():
    this.set_flag("hostile", True)
    print("The troll stirs, quickly resuming a fighting stance.")
if axe.location == this:
    this.set_property(
        "description", "A nasty-looking troll, brandishing a bloody axe, blocks\nall passages out of the room."
    )
elif axe.location == lookup("troll_room"):
    axe.set_flag("ndescbit", True)
    axe.set_flag("weapon", False)
    axe.moveto(this)
    this.set_property(
        "description", "A nasty-looking troll, brandishing a bloody axe, blocks\nall passages out of the room."
    )
else:
    this.set_property("description", "A troll is here.")
player.zstate_set("TROLL-FLAG", False)
