#!moo verb f_first_p --on "troll" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

import random
from moo.sdk import context

# ZIL: TROLL-FCN / F-FIRST?

player = context.player
mode = args[0] if len(args) > 0 else "F-FIRST?"

if random.randint(1, 100) <= 33:
    this.set_flag("hostile", True)
    player.zstate_set("P-CONT", False)
    True
