#!moo verb f_unconscious --on "troll" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL: TROLL-FCN / F-UNCONSCIOUS

player = context.player
axe = lookup("axe")
mode = args[0] if len(args) > 0 else "F-UNCONSCIOUS"

this.set_flag("hostile", False)
if axe.location == this:
    axe.moveto(player.here())
    axe.set_flag("ndescbit", False)
    axe.set_flag("weapon", True)
this.set_property(
    "description", "An unconscious troll is sprawled on the floor. All passages\nout of the room are open."
)
player.zstate_set("TROLL-FLAG", True)
