#!moo verb tell --on "troll" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: TROLL-FCN (tell branch)

player = context.player
mode = args[0] if len(args) > 0 else None
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

player.zstate_set("P-CONT", False)
print("The troll isn't much of a conversationalist.")
return
