#!moo verb troll_fcn f_busy_p f_dead f_unconscious f_conscious f_first_p --on "troll" --dspec either

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

import random
from moo.sdk import context, invoked_verb_name, lookup

# ZIL: TROLL-FCN / combined M-/F-clause dispatch

player = context.player
axe = lookup("axe")
verb_to_const = {
    "f_busy_p": "F-BUSY?",
    "f_dead": "F-DEAD",
    "f_unconscious": "F-UNCONSCIOUS",
    "f_conscious": "F-CONSCIOUS",
    "f_first_p": "F-FIRST?",
}
rarg = args[0] if len(args) > 0 else verb_to_const.get(verb_name, "F-BUSY?")
mode = args[0] if len(args) > 0 else rarg
the_player_verb = args[1] if len(args) > 1 else invoked_verb_name(verb_name)

if rarg == "F-BUSY?":
    if axe.location == this:
        pass
    elif axe.location == player.here() and random.randint(1, 100) <= 75:
        axe.set_flag("ndescbit", True)
        axe.set_flag("weapon", False)
        axe.moveto(this)
        this.set_property(
            "description", "A nasty-looking troll, brandishing a bloody axe, blocks all passages out\nof the room."
        )
        if this.location == player.here():
            print(
                "The troll, angered and humiliated, recovers his weapon. He appears to have\nan axe to grind with you."
            )
        True
    elif this.location == player.here():
        this.set_property("description", "A pathetically babbling troll is here.")
        print("The troll, disarmed, cowers in terror, pleading for his life in\nthe guttural tongue of the trolls.")
        True
elif rarg == "F-DEAD":
    if axe.location == this:
        axe.moveto(player.here())
        axe.set_flag("ndescbit", False)
        axe.set_flag("weapon", True)
    player.zstate_set("TROLL-FLAG", True)
elif rarg == "F-UNCONSCIOUS":
    this.set_flag("hostile", False)
    if axe.location == this:
        axe.moveto(player.here())
        axe.set_flag("ndescbit", False)
        axe.set_flag("weapon", True)
    this.set_property(
        "description", "An unconscious troll is sprawled on the floor. All passages\nout of the room are open."
    )
    player.zstate_set("TROLL-FLAG", True)
elif rarg == "F-CONSCIOUS":
    if this.location == player.here():
        this.set_flag("hostile", True)
        print("The troll stirs, quickly resuming a fighting stance.")
    if axe.location == this:
        this.set_property(
            "description", "A nasty-looking troll, brandishing a bloody axe, blocks\nall passages out of the room."
        )
    elif axe.location == lookup("troll_room"):
        axe.set_flag("ndescbit", True)
        axe.set_flag("weapon", False)
        axe.moveto(this)
        this.set_property(
            "description", "A nasty-looking troll, brandishing a bloody axe, blocks\nall passages out of the room."
        )
    else:
        this.set_property("description", "A troll is here.")
    player.zstate_set("TROLL-FLAG", False)
elif rarg == "F-FIRST?":
    if random.randint(1, 100) <= 33:
        this.set_flag("hostile", True)
        player.zstate_set("P-CONT", False)
        True
