#!moo verb look-inside examine x describe what --on "mirror (MIRROR-2)" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name, lookup

# ZIL routine: MIRROR-MIRROR (look-inside/examine branch)

player = context.player
rm2 = lookup("mirror_room_2")
l1 = 0
l2 = 0
n = 0
the_player_verb = invoked_verb_name(verb_name)

if player.zstate_get("MIRROR-MUNG"):
    print("The mirror is broken into many pieces.", end="")
else:
    print("There is an ugly person staring back at you.", end="")
print()
return
