#!moo verb mung destroy break smash crack throw toss attack kill hit fight stab cut slice --on "mirror (MIRROR-2)" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name, lookup

# ZIL routine: MIRROR-MIRROR (mung/throw/attack branch)

player = context.player
rm2 = lookup("mirror_room_2")
l1 = 0
l2 = 0
n = 0
the_player_verb = invoked_verb_name(verb_name)

if player.zstate_get("MIRROR-MUNG"):
    print("Haven't you done enough damage already?")
    return
else:
    player.zstate_set("MIRROR-MUNG", True)
    player.zstate_set("LUCKY", False)
    print("You have broken the mirror. I hope you have a seven years' supply of\ngood luck handy.")
    return
