#!moo verb chasm_pseudo --on "Thing" --dspec this

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, invoked_verb_name, lookup

# ZIL routine: CHASM-PSEUDO

parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
the_player_verb = invoked_verb_name(verb_name)

if prso is None:
    if context.parser is not None and context.parser.has_dobj_str():
        print("There is no '" + context.parser.dobj_str + "' here.")
    else:
        print("I don't know how to do that.")
    return

if the_player_verb == "leap" or (the_player_verb in ["put", "place", "insert"] and prso == lookup("me")):
    print("You look before leaping, and realize that you would never survive.")
    return
elif the_player_verb == "cross":
    print("It's too far to jump, and there's no bridge.")
    return
elif the_player_verb in ["put", "place", "insert", "throw_off"] and prsi == lookup("pseudo_object"):
    print("The " + (prso.desc() if prso else "") + " drops out of sight into the chasm.")
    return _.remove(prso)
