#!moo verb dome_pseudo --on "Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import invoked_verb_name

# ZIL routine: DOME-PSEUDO

the_player_verb = invoked_verb_name(verb_name)

if the_player_verb == "kiss":
    print("No.")
    return
