#!moo verb lake_pseudo --on "Thing" --dspec this

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name

# ZIL routine: LAKE-PSEUDO

player = context.player
the_player_verb = invoked_verb_name(verb_name)

if player.zstate_get("LOW-TIDE"):
    print("There's not much lake left....")
    return
elif the_player_verb == "cross":
    print("It's too wide to cross.")
    return
elif the_player_verb == "through":
    print("You can't swim in this lake.")
    return
