#!moo verb bug --on "Zork Actor" --dspec none

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: V-BUG

print("Bug? Not in a flawless program like this! (Cough, cough).")
return
