#!moo verb curses curse shit fuck damn --on "Zork Actor" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: V-CURSES

parser = context.parser

if parser.get_dobj() if parser.has_dobj_str() else None:
    if (parser.get_dobj() if parser.has_dobj_str() else None).flag("actorbit"):
        print("Insults of this nature won't help you.")
        return
    else:
        print("What a loony!")
        return
else:
    print("Such language in a high-class establishment like this!")
    return
