#!moo verb diagnose --on "Zork Actor" --dspec none

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: V-DIAGNOSE
# aux: MS, WD, RS

player = context.player
ms = _.zork_thing.fight_strength(False)
wd = player.getp("strength")
rs = ms + wd

player.zstate_get("#DECL")
if _.table_get(_.zork_thing.int(_.zork_thing.i_cure()), player.zstate_get("C-ENABLED?")) == 0:
    wd = 0
else:
    wd = -wd
if wd == 0:
    print("You are in perfect health.", end="")
else:
    print("You have ", end="")
    if wd == 1:
        print("a light wound,", end="")
    elif wd == 2:
        print("a serious wound,", end="")
    elif wd == 3:
        print("several wounds,", end="")
    elif wd > 3:
        print("serious wounds,", end="")
if wd != 0:
    print(
        " which will be cured after "
        + str(
            (
                (player.zstate_get("CURE-WAIT") * (wd - 1))
                + _.table_get(_.zork_thing.int(_.zork_thing.i_cure()), player.zstate_get("C-TICK"))
            )
        )
        + " moves.",
        end="",
    )
print()
print("You can ", end="")
if rs == 0:
    print("expect death soon", end="")
elif rs == 1:
    print("be killed by one more light wound", end="")
elif rs == 2:
    print("be killed by a serious wound", end="")
elif rs == 3:
    print("survive one serious wound", end="")
elif rs > 3:
    print("survive several wounds", end="")
print(".")
if not player.zstate_get("DEATHS") == 0:
    print("You have been killed ", end="")
    if player.zstate_get("DEATHS") == 1:
        print("once", end="")
    else:
        print("twice", end="")
    print(".")
    return
