#!moo verb exit --on "Zork Actor" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context

# ZIL routine: V-EXIT

player = context.player
parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None

if prso in (False, player.zstate_get("ROOMS")) and player.location.flag("vehicle"):
    _.perform("disembark", player.location, None)
    return True
elif prso and player.location == prso:
    _.perform("disembark", prso, None)
    return True
else:
    return _.walk(player.zstate_get("P?OUT"))
