#!moo verb frobozz --on "Zork Actor" --dspec none

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: V-FROBOZZ

print("The FROBOZZ Corporation created, owns, and operates this dungeon.")
return
