#!moo verb restore --on "Zork Actor" --dspec none

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: V-RESTORE

if False:  # pylint: disable=using-constant-test
    print("Ok.")
    # ZIL: <V-FIRST-LOOK ...>
    return _.zork_thing.first_look()
else:
    print("Failed.")
    return
