#!moo verb restart --on "Zork Actor" --dspec none

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: V-RESTART

# ZIL: <V-SCORE ...>
_.zork_thing.score(True)
print("Do you wish to restart? (Y is affirmative): ", end="")
if _.zork_thing.is_yes():
    print("Restarting.")
    print("Restart not supported in DjangoMOO.")
    print("Failed.")
    return
