#!moo verb script --on "Zork Actor" --dspec none

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: V-SCRIPT

# ZIL: <PUT ...>
_.table_put(0, 8, (((_.table_get(_.get_property("zstate_version_table"), 8)) or 0) | ((1) or 0)))
print("Here begins a transcript of interaction with")
# ZIL: <V-VERSION ...>
_.zork_thing.version()
return True
