#!moo verb treasure temple --on "Zork Actor" --dspec none

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: V-TREASURE

player = context.player
north_temple = lookup("north_temple")
treasure_room = lookup("treasure_room")

if player.here() == north_temple:
    return _.goto(treasure_room)
elif player.here() == treasure_room:
    return _.goto(north_temple)
else:
    print("Nothing happens.")
    return
