#!moo verb verbose --on "Zork Actor" --dspec none

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: V-VERBOSE

player = context.player

player.zstate_set("VERBOSE", True)
player.zstate_set("SUPER-BRIEF", False)
print("Maximum verbosity.")
return
