#!moo verb version --on "Zork Actor" --dspec none

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, task_time_low

# ZIL routine: V-VERSION
# aux: CNT

player = context.player
cnt = 17

print(
    "ZORK I: The Great Underground Empire\n\nInfocom interactive fiction - a fantasy story\n\nCopyright (c) 1981, 1982, 1983, 1984, 1985, 1986",
    end="",
)
print(" Infocom, Inc. All rights reserved.")
print(
    "ZORK is a registered trademark of Infocom, Inc.\n\nRelease "
    + str((((_.table_get(_.get_property("zstate_version_table"), 1)) or 0) & ((player.zstate_get("*3777*")) or 0)))
    + " / Serial number ",
    end="",
)
while True:
    if task_time_low():
        print("[zil] long-running loop in V-VERSION; aborting (bug — please report).")
        return False
    if (cnt := (cnt + 1)) > 23:
        break
    else:
        print(chr(_.table_get(_.get_property("zstate_version_table"), cnt)), end="")
print()
return
