#!moo verb dboat_function --on "punctured boat" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, lookup

# ZIL: DBOAT-FUNCTION / combined OBJECT-FUNCTION dispatch
# Invoked by ``_.thing.dispatch_object_function(obj, verb, prep, iobj)``
# which looks up ``obj.action`` and calls ``obj.invoke_verb(action_atom, ...)``.

parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
putty = lookup("putty")
the_verb = args[0] if len(args) > 0 else None
prep = args[1] if len(args) > 1 else None
iobj = args[2] if len(args) > 2 else None
the_player_verb = the_verb

if the_verb == "put" or the_verb == "put_on":
    if prso == putty:
        # ZIL: <FIX-BOAT ...>
        return _.thing.fix_boat()
elif the_verb == "inflate" or the_verb == "fill":
    print("No chance. Some moron punctured it.")
    return
elif the_verb == "plug":
    if prsi == putty:
        # ZIL: <FIX-BOAT ...>
        return _.thing.fix_boat()
    else:
        # ZIL: <WITH-TELL ...>
        return _.thing.with_tell(prsi)
return False
