#!moo verb plug --on "punctured boat" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, invoked_verb_name, lookup

# ZIL routine: DBOAT-FUNCTION (plug branch)

parser = context.parser
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
the_player_verb = invoked_verb_name(verb_name)

if prsi == lookup("putty"):
    # ZIL: <FIX-BOAT ...>
    return _.thing.fix_boat()
else:
    # ZIL: <WITH-TELL ...>
    return _.thing.with_tell(prsi)
