#!moo verb plug --on "punctured boat" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: DBOAT-FUNCTION (plug branch)

parser = context.parser
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if (parser.get_iobj() if parser.has_iobj() else None) == lookup("putty"):
    # ZIL: <FIX-BOAT ...>
    return _.zork_thing.fix_boat()
else:
    # ZIL: <WITH-TELL ...>
    return _.zork_thing.with_tell((parser.get_iobj() if parser.has_iobj() else None))
