#!moo verb bottle_function --on "glass bottle" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, lookup

# ZIL: BOTTLE-FUNCTION / combined OBJECT-FUNCTION dispatch
# Invoked by ``_.thing.dispatch_object_function(obj, verb, prep, iobj)``
# which looks up ``obj.action`` and calls ``obj.invoke_verb(action_atom, ...)``.

parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
the_verb = args[0] if len(args) > 0 else None
prep = args[1] if len(args) > 1 else None
iobj = args[2] if len(args) > 2 else None
e_p = 0
the_player_verb = the_verb

if the_verb == "throw":
    if prso == this:
        _.remove(prso)
        e_p = True
        print("The bottle hits the far wall and shatters.")
        return
elif the_verb == "mung":
    e_p = True
    _.remove(prso)
    print("A brilliant maneuver destroys the bottle.")
    return
elif the_verb == "shake":
    if (prso.flag("open") if prso else None) and lookup("water").location == prso:
        e_p = True
return False
