#!moo verb bottle_function --on "Thing" --dspec this

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, lookup

# ZIL routine: BOTTLE-FUNCTION
# aux: E?

parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
water = lookup("water")
e_p = 0

if e_p and water.location == prso:
    print("The water spills to the floor and evaporates.")
    _.remove(water)
    return True
elif e_p:
    return True
return passthrough()
