#!moo verb mung destroy break smash crack --on "glass bottle" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, invoked_verb_name

# ZIL routine: BOTTLE-FUNCTION (mung branch)

parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
e_p = 0
the_player_verb = invoked_verb_name(verb_name)

e_p = True
_.remove(prso)
print("A brilliant maneuver destroys the bottle.")
return
