#!moo verb shake --on "glass bottle" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, invoked_verb_name, lookup

# ZIL routine: BOTTLE-FUNCTION (shake branch)

parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
e_p = 0
the_player_verb = invoked_verb_name(verb_name)

if (prso.flag("open") if prso else None) and lookup("water").location == prso:
    e_p = True
return passthrough()
