#!moo verb throw toss --on "glass bottle" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: BOTTLE-FUNCTION (throw branch)

parser = context.parser
e_p = 0
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if (parser.get_dobj() if parser.has_dobj_str() else None) == this:
    _.remove((parser.get_dobj() if parser.has_dobj_str() else None))
    e_p = True
    print("The bottle hits the far wall and shatters.")
    return
return passthrough()
