#!moo verb axe_f --on "Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: AXE-F

player = context.player

if player.zstate_get("TROLL-FLAG"):
    pass
else:
    # ZIL: <WEAPON-FUNCTION ...>
    return _.thing.weapon_function(this, lookup("troll"))
