#!moo verb look --on "Reservoir South" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL: RESERVOIR-SOUTH-FCN / M-LOOK

player = context.player
parser = context.parser
rarg = args[0] if len(args) > 0 else "M-LOOK"
the_player_verb = (
    args[1]
    if len(args) > 1
    else (parser.words[0].lower() if context.parser is not None and parser.words else verb_name)
)

if player.zstate_get("LOW-TIDE") and player.zstate_get("GATES-OPEN"):
    print(
        "You are in a long room, to the north of which was formerly a lake.\nHowever, with the water level lowered, there is merely a wide stream\nrunning through the center of the room.",
        end="",
    )
elif player.zstate_get("GATES-OPEN"):
    print(
        "You are in a long room. To the north is a large lake, too deep\nto cross. You notice, however, that the water level appears to be\ndropping at a rapid rate. Before long, it might be possible to cross\nto the other side from here.",
        end="",
    )
elif player.zstate_get("LOW-TIDE"):
    print(
        "You are in a long room, to the north of which is a wide area which\nwas formerly a reservoir, but now is merely a stream. You notice,\nhowever, that the level of the stream is rising quickly and that\nbefore long it will be impossible to cross here.",
        end="",
    )
else:
    print("You are in a long room on the south shore of a large lake, far\ntoo deep and wide for crossing.", end="")
print()
print(
    "There is a path along the stream to the east or west, a steep pathway\nclimbing southwest along the edge of a chasm, and a path leading into a\ncanyon to the southeast."
)
_.zork_thing.describe_objects(True)
