#!moo verb turnfunc --on "Frigid River (RIVER-4)" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL: RIVR4-ROOM / M-END

player = context.player
parser = context.parser
rarg = args[0] if len(args) > 0 else "M-END"
the_player_verb = (
    args[1]
    if len(args) > 1
    else (parser.words[0].lower() if context.parser is not None and parser.words else verb_name)
)

if lookup("buoy").location == player and player.zstate_get("BUOY-FLAG"):
    print("You notice something funny about the feel of the buoy.")
    player.zstate_set("BUOY-FLAG", False)
