#!moo verb preturnfunc --on "Altar" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name, lookup

# ZIL: SOUTH-TEMPLE-FCN / M-BEG

player = context.player
rarg = args[0] if len(args) > 0 else "M-BEG"
the_player_verb = args[1] if len(args) > 1 else invoked_verb_name(verb_name)

player.zstate_set("COFFIN-CURE", not lookup("coffin").location == player)
return False
