#!moo verb smell sniff --on "brown sack" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, lookup

# ZIL routine: SANDWICH-BAG-FCN (smell branch)

parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if lookup("lunch").location == prso:
    print("It smells of hot peppers.")
    return
return passthrough()
