#!moo verb open --on "red buoy" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import invoked_verb_name, lookup

# ZIL routine: TREASURE-INSIDE (open branch)

the_player_verb = invoked_verb_name(verb_name)

# ZIL: <SCORE-OBJ ...>
_.zork_thing.score_obj(lookup("emerald"))
return passthrough()
