#!moo verb open --on "red buoy" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: TREASURE-INSIDE (open branch)

the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

# ZIL: <SCORE-OBJ ...>
_.zork_thing.score_obj(lookup("emerald"))
return passthrough()
