#!moo verb lld_room look preturnfunc turnfunc --on "Entrance to Hades" --dspec either

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, invoked_verb_name, lookup

# ZIL: LLD-ROOM / combined M-/F-clause dispatch

player = context.player
parser = context.parser
prso = None
if context.parser is not None:
    try:
        prso = parser.get_dobj() if parser.has_dobj_str() else None
    except NoSuchObjectError:
        prso = None
bell = lookup("bell")
book = lookup("book")
candles = lookup("candles")
hot_bell = lookup("hot_bell")
verb_to_const = {"look": "M-LOOK", "preturnfunc": "M-BEG", "turnfunc": "M-END"}
rarg = args[0] if len(args) > 0 else verb_to_const.get(verb_name, "M-LOOK")
the_player_verb = args[1] if len(args) > 1 else invoked_verb_name(verb_name)

if rarg == "M-LOOK":
    print(this.desc())
    print(
        "You are outside a large gateway, on which is inscribed\n\n\n  Abandon every hope\nall ye who enter here!\n\n\nThe gate is open; through it you can see a desolation, with a pile of\nmangled bodies in one corner. Thousands of voices, lamenting some\nhideous fate, can be heard."
    )
    if not player.zstate_get("LLD-FLAG") and not player.zstate_get("DEAD"):
        print("The way through the gate is barred by evil spirits, who jeer at your\nattempts to pass.")
    _.thing.describe_objects(True)
elif rarg == "M-BEG":
    if the_player_verb == "exorcise":
        if not player.zstate_get("LLD-FLAG"):
            if bell.location == player and book.location == player and candles.location == player:
                print("You must perform the ceremony.")
                return True
            else:
                print("You aren't equipped for an exorcism.")
                return True
    elif not player.zstate_get("LLD-FLAG") and the_player_verb == "ring" and prso == bell:
        player.zstate_set("XB", True)
        _.remove(bell)
        # ZIL: <THIS-IS-IT ...>
        _.thing.this_is_it(hot_bell)
        hot_bell.moveto(player.here())
        print(
            "The bell suddenly becomes red hot and falls to the ground. The\nwraiths, as if paralyzed, stop their jeering and slowly turn to face\nyou. On their ashen faces, the expression of a long-forgotten terror\ntakes shape."
        )
        if candles.location == player:
            print("In your confusion, the candles drop to the ground (and they are out).")
            candles.moveto(player.here())
            candles.set_flag("onbit", False)
            _.cancel("i-candles")
        _.schedule_realtime("i_xb", 6)
        _.schedule_realtime("i_xbh", 20)
        return True
    elif player.zstate_get("XC") and the_player_verb == "read" and prso == book and not player.zstate_get("LLD-FLAG"):
        print(
            'Each word of the prayer reverberates through the hall in a deafening\nconfusion. As the last word fades, a voice, loud and commanding,\nspeaks: "Begone, fiends!" A heart-stopping scream fills the cavern,\nand the spirits, sensing a greater power, flee through the walls.'
        )
        _.remove(lookup("ghosts"))
        player.zstate_set("LLD-FLAG", True)
        _.unschedule_realtime("i_xc")
        return True
elif rarg == "M-END":
    if player.zstate_get("XB") and candles.location == player and candles.flag("onbit") and not player.zstate_get("XC"):
        player.zstate_set("XC", True)
        print(
            "The flames flicker wildly and appear to dance. The earth beneath\nyour feet trembles, and your legs nearly buckle beneath you.\nThe spirits cower at your unearthly power."
        )
        _.unschedule_realtime("i_xb")
        _.schedule_realtime("i_xc", 3)
