#!moo verb look --on "Entrance to Hades" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL: LLD-ROOM / M-LOOK

player = context.player
parser = context.parser
rarg = args[0] if len(args) > 0 else "M-LOOK"
the_player_verb = (
    args[1]
    if len(args) > 1
    else (parser.words[0].lower() if context.parser is not None and parser.words else verb_name)
)

print(
    "You are outside a large gateway, on which is inscribed\n\n\n  Abandon every hope\nall ye who enter here!\n\n\nThe gate is open; through it you can see a desolation, with a pile of\nmangled bodies in one corner. Thousands of voices, lamenting some\nhideous fate, can be heard."
)
if not player.zstate_get("LLD-FLAG") and not player.zstate_get("DEAD"):
    print("The way through the gate is barred by evil spirits, who jeer at your\nattempts to pass.")
_.zork_thing.describe_objects(True)
