#!moo verb preturnfunc --on "Entrance to Hades" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, lookup

# ZIL: LLD-ROOM / M-BEG

player = context.player
parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
bell = lookup("bell")
book = lookup("book")
candles = lookup("candles")
hot_bell = lookup("hot_bell")
rarg = args[0] if len(args) > 0 else "M-BEG"
the_player_verb = (
    args[1]
    if len(args) > 1
    else (parser.words[0].lower() if context.parser is not None and parser.words else verb_name)
)

if the_player_verb == "exorcise":
    if not player.zstate_get("LLD-FLAG"):
        if bell.location == player and book.location == player and candles.location == player:
            print("You must perform the ceremony.")
        else:
            print("You aren't equipped for an exorcism.")
            return True
elif not player.zstate_get("LLD-FLAG") and the_player_verb == "ring" and prso == bell:
    player.zstate_set("XB", True)
    _.remove(bell)
    # ZIL: <THIS-IS-IT ...>
    _.zork_thing.this_is_it(hot_bell)
    hot_bell.moveto(player.here())
    print(
        "The bell suddenly becomes red hot and falls to the ground. The\nwraiths, as if paralyzed, stop their jeering and slowly turn to face\nyou. On their ashen faces, the expression of a long-forgotten terror\ntakes shape."
    )
    if candles.location == player:
        print("In your confusion, the candles drop to the ground (and they are out).")
        candles.moveto(player.here())
        candles.set_flag("onbit", False)
        _.cancel("i-candles")
    _.queue("i-xb", 6)
    _.queue("i-xbh", 20)
    return True
elif player.zstate_get("XC") and the_player_verb == "read" and prso == book and not player.zstate_get("LLD-FLAG"):
    print(
        'Each word of the prayer reverberates through the hall in a deafening\nconfusion. As the last word fades, a voice, loud and commanding,\nspeaks: "Begone, fiends!" A heart-stopping scream fills the cavern,\nand the spirits, sensing a greater power, flee through the walls.'
    )
    _.remove(lookup("ghosts"))
    player.zstate_set("LLD-FLAG", True)
    _.cancel("i-xc")
    return True
