#!moo verb turnfunc --on "Entrance to Hades" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name, lookup

# ZIL: LLD-ROOM / M-END

player = context.player
candles = lookup("candles")
rarg = args[0] if len(args) > 0 else "M-END"
the_player_verb = args[1] if len(args) > 1 else invoked_verb_name(verb_name)

if player.zstate_get("XB") and candles.location == player and candles.flag("onbit") and not player.zstate_get("XC"):
    player.zstate_set("XC", True)
    print(
        "The flames flicker wildly and appear to dance. The earth beneath\nyour feet trembles, and your legs nearly buckle beneath you.\nThe spirits cower at your unearthly power."
    )
    _.unschedule_realtime("i_xb")
    _.schedule_realtime("i_xc", 3)
