#!moo verb describe examine get give hear hello hi listen look_inside pick take throw toss what x --on "thief" --dspec any --ispec on:this in:this at:this with:this from:this under:this over:this before:this around:this through:this behind:this beside:this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

import random
from moo.sdk import NoSuchObjectError, context, invoked_verb_name, lookup

# ZIL routine: ROBBER-FUNCTION
# params: MODE
# aux: FLG, X

player = context.player
parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
large_bag = lookup("large_bag")
stiletto = lookup("stiletto")
mode = args[0] if len(args) > 0 else None
flg = 0
x = 0
the_player_verb = invoked_verb_name(verb_name)

if not mode:
    if the_player_verb in ["hello", "hi"] and this.getp("description") == player.zstate_get("ROBBER-U-DESC"):
        print(
            "The thief, being temporarily incapacitated, is unable to acknowledge\nyour greeting with his usual graciousness."
        )
        return
    elif prso == lookup("knife") and the_player_verb in ["throw", "toss"] and not this.flag("hostile"):
        prso.moveto(player.here())
        if random.randint(1, 100) <= 10:
            print("You evidently frightened the robber, though you didn't hit him. He\nflees", end="")
            _.remove(large_bag)
            x = False
            if stiletto.location == this:
                _.remove(stiletto)
                x = True
            if this.contents.first():
                # ZIL: <MOVE-ALL ...>
                _.thing.move_all(this, player.here())
                print(", but the contents of his bag fall on the floor.", end="")
            else:
                print(".", end="")
            large_bag.moveto(this)
            if x:
                stiletto.moveto(this)
            print()
            return this.set_flag("invisible", True)
        else:
            print(
                "You missed. The thief makes no attempt to take the knife, though it\nwould be a fine addition to the collection in his bag. He does seem\nangered by your attempt."
            )
            return this.set_flag("hostile", True)
    elif the_player_verb in ["throw", "toss", "give"] and prso and not prso == this and prsi == this:
        if this.getp("strength") < 0:
            this.set_property("strength", (-this.getp("strength")))
            _.schedule_realtime("i_thief", 0)
            # ZIL: <RECOVER-STILETTO ...>
            _.thing.recover_stiletto()
            this.set_property("description", player.zstate_get("ROBBER-C-DESC"))
            print("Your proposed victim suddenly recovers consciousness.")
        (prso.moveto(this) if prso else None)
        if (prso.getp("tvalue") if prso else None) > 0:
            player.zstate_set("THIEF-ENGROSSED", True)
            print(
                "The thief is taken aback by your unexpected generosity, but accepts\nthe "
                + (prso.desc() if prso else "")
                + " and stops to admire its beauty."
            )
            return
        else:
            print("The thief places the " + (prso.desc() if prso else "") + " in his bag and thanks\nyou politely.")
            return
    elif the_player_verb in ["take", "get", "pick"]:
        print("Once you got him, what would you do with him?")
        return
    elif the_player_verb in ["examine", "x", "describe", "what", "look_inside"]:
        print(
            "The thief is a slippery character with beady eyes that flit back\nand forth. He carries, along with an unmistakable arrogance, a large bag\nover his shoulder and a vicious stiletto, whose blade is aimed\nmenacingly in your direction. I'd watch out if I were you."
        )
        return
    elif the_player_verb in ["listen", "hear"]:
        print("The thief says nothing, as you have not been formally introduced.")
        return
return passthrough()
