#!moo verb f_dead --on "thief" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup, task_time_low

# ZIL: ROBBER-FUNCTION / F-DEAD

player = context.player
stiletto = lookup("stiletto")
mode = args[0] if len(args) > 0 else "F-DEAD"
flg = 0
x = 0

stiletto.moveto(player.here())
stiletto.set_flag("ndescbit", False)
x = _.thing.deposit_booty(player.here())
if player.here() == lookup("treasure_room"):
    x = player.here().contents.first()
    while True:
        if task_time_low():
            print("[zil] long-running loop in ROBBER-FUNCTION; aborting (bug — please report).")
            return False
        if not x:
            print("The chalice is now safe to take.")
            break
        elif not x in (lookup("chalice"), this, player):
            x.set_flag("invisible", False)
            if not flg:
                flg = True
                print("As the thief dies, the power of his magic decreases, and his\ntreasures reappear:")
            print("  A " + x.desc(), end="")
            if x.contents.first() and _.thing.is_see_inside(x):
                print(", with " + _.thing.print_contents(x), end="")
            print()
        x = _.next_sibling(x)
elif x:
    print("His booty remains.")
_.unschedule_realtime("i_thief")
