#!moo verb f_first_p --on "thief" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

import random
from moo.sdk import context

# ZIL: ROBBER-FUNCTION / F-FIRST?

player = context.player
mode = args[0] if len(args) > 0 else "F-FIRST?"
flg = 0
x = 0

if player.zstate_get("THIEF-HERE") and not this.flag("invisible") and random.randint(1, 100) <= 20:
    this.set_flag("hostile", True)
    player.zstate_set("P-CONT", False)
