#!moo verb f_unconscious --on "thief" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL: ROBBER-FUNCTION / F-UNCONSCIOUS

player = context.player
stiletto = lookup("stiletto")
mode = args[0] if len(args) > 0 else "F-UNCONSCIOUS"
flg = 0
x = 0

_.cancel("i-thief")
this.set_flag("hostile", False)
stiletto.moveto(player.here())
stiletto.set_flag("ndescbit", False)
this.set_property("description", player.zstate_get("ROBBER-U-DESC"))
