#!moo verb tell --on "thief" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name

# ZIL routine: ROBBER-FUNCTION (tell branch)

player = context.player
mode = args[0] if len(args) > 0 else None
flg = 0
x = 0
the_player_verb = invoked_verb_name(verb_name)

print("The thief is a strong, silent type.")
return player.zstate_set("P-CONT", False)
