#!moo verb score_obj --on "Thing" --dspec this

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: SCORE-OBJ
# params: OBJ
# aux: TEMP

obj = args[0] if len(args) > 0 else None
temp = 0

if (temp := obj.getp("value")) > 0:
    # ZIL: <SCORE-UPD ...>
    _.thing.score_upd(temp)
    return obj.set_property("value", 0)
