#!moo verb pre_mung --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: PRE-MUNG

parser = context.parser

if _.zork_thing.null_f():
    return True
elif not (parser.get_iobj() if parser.has_iobj() else None) or not (
    parser.get_iobj().flag("weapon") if parser.has_iobj() else None
):
    print("Trying to destroy the " + (parser.get_dobj() if parser.has_dobj_str() else None).desc() + " with ", end="")
    if not (parser.get_iobj() if parser.has_iobj() else None):
        print("your bare hands", end="")
    else:
        print("a " + (parser.get_iobj().desc() if parser.has_iobj() else ""), end="")
    print(" is futile.")
    return
