#!moo verb pre_fill --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, lookup

# ZIL routine: PRE-FILL
# aux: TX

player = context.player
parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
global_water = lookup("global_water")
water = lookup("water")
tx = 0

if prso is None:
    if context.parser is not None and context.parser.has_dobj_str():
        print("There is no '" + context.parser.dobj_str + "' here.")
    else:
        print("I don't know how to do that.")
    return True

if not prsi:
    tx = getpt(player.here(), player.zstate_get("P?GLOBAL"))
    if tx and _.zork_thing.zmemqb(global_water, tx, (ptsize(tx) - 1)):
        _.perform("fill", prso, global_water)
        return True
    elif water.location == player.location:
        _.perform("fill", prso, water)
        return True
    else:
        print("There is nothing to fill it with.")
        return True
if prsi == water:
    return False
elif not prsi == global_water:
    _.perform("put", prsi, prso)
    return True
