#!moo verb pre_burn --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: PRE-BURN

parser = context.parser

if not (parser.get_iobj() if parser.has_iobj() else None):
    # ZIL: <TELL-NO-PRSI ...>
    return _.zork_thing.tell_no_prsi()
elif flaming_p((parser.get_iobj() if parser.has_iobj() else None)):
    return False
else:
    print("With a " + (parser.get_iobj().desc() if parser.has_iobj() else "") + "??!?")
    return
