#!moo verb pre_take --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: PRE-TAKE

player = context.player
parser = context.parser

if (parser.get_dobj() if parser.has_dobj_str() else None).location == player:
    if (parser.get_dobj() if parser.has_dobj_str() else None).flag("wearbit"):
        print("You are already wearing it.")
        return
    else:
        print("You already have that!")
        return
elif (parser.get_dobj() if parser.has_dobj_str() else None).location.flag("contbit") and not (
    parser.get_dobj() if parser.has_dobj_str() else None
).location.flag("open"):
    print("You can't reach something that's inside a closed container.")
    return True
elif parser.get_iobj() if parser.has_iobj() else None:
    if (parser.get_iobj() if parser.has_iobj() else None) == lookup("ground"):
        # SETG of parser-state slot is a no-op in DjangoMOO
        return False
    # ZIL: <NULL-F ...>
    _.zork_thing.null_f()
    if (
        not (parser.get_iobj() if parser.has_iobj() else None)
        == (parser.get_dobj() if parser.has_dobj_str() else None).location
    ):
        print(
            "The "
            + (parser.get_dobj() if parser.has_dobj_str() else None).desc()
            + " isn't in the "
            + (parser.get_iobj().desc() if parser.has_iobj() else "")
            + "."
        )
        return
    else:
        # SETG of parser-state slot is a no-op in DjangoMOO
        return False
elif (parser.get_dobj() if parser.has_dobj_str() else None) == player.location:
    print("You're inside of it!")
    return
