#!moo verb pre_take --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, lookup

# ZIL routine: PRE-TAKE

player = context.player
parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None

if prso is None:
    if context.parser is not None and context.parser.has_dobj_str():
        print("There is no '" + context.parser.dobj_str + "' here.")
    else:
        print("I don't know how to do that.")
    return True

if prso.location == player:
    if prso.flag("wearbit") if prso else None:
        print("You are already wearing it.")
        return True
    else:
        print("You already have that!")
        return True
elif prso.location.flag("contbit") and not prso.location.flag("open"):
    print("You can't reach something that's inside a closed container.")
    return True
elif prsi:
    if prsi == lookup("ground"):
        # SETG of parser-state slot is a no-op in DjangoMOO
        return False
    # ZIL: <NULL-F ...>
    _.zork_thing.null_f()
    if prsi != prso.location:
        print("The " + (prso.desc() if prso else "") + " isn't in the " + (prsi.desc() if prsi else "") + ".")
        return True
    else:
        # SETG of parser-state slot is a no-op in DjangoMOO
        return False
elif prso == player.location:
    print("You're inside of it!")
    return True
