#!moo verb pre_move --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: PRE-MOVE

parser = context.parser

if _.zork_thing.is_held((parser.get_dobj() if parser.has_dobj_str() else None)):
    print("You aren't an accomplished enough juggler.")
    return
