#!moo verb pre_board --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: PRE-BOARD
# aux: AV

player = context.player
parser = context.parser
av = 0

av = player.location
if _.zork_thing.null_f():
    return True
elif (parser.get_dobj() if parser.has_dobj_str() else None).flag("vehicle"):
    if not (parser.get_dobj() if parser.has_dobj_str() else None).location == player.here():
        print(
            "The "
            + (parser.get_dobj() if parser.has_dobj_str() else None).desc()
            + " must be on the ground to be boarded."
        )
    elif av.flag("vehicle"):
        print("You are already in the " + av.desc() + "!")
    else:
        return False
elif (parser.get_dobj() if parser.has_dobj_str() else None) in (lookup("water"), lookup("global_water")):
    _.perform("swim", (parser.get_dobj() if parser.has_dobj_str() else None), None)
    return True
else:
    print(
        "You have a theory on how to board a "
        + (parser.get_dobj() if parser.has_dobj_str() else None).desc()
        + ", perhaps?"
    )
# ZIL: <RFATAL ...>
return 2
