#!moo verb describe_object --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: DESCRIBE-OBJECT
# params: OBJ, V?, LEVEL
# aux: STR, AV

player = context.player
obj = args[0] if len(args) > 0 else None
v_p = args[1] if len(args) > 1 else None
level = args[2] if len(args) > 2 else None
str_v = 0
av = 0

player.zstate_set("DESC-OBJECT", obj)
if level == 0 and (
    obj.invoke_verb("descfunc") if obj is not None and obj.has_verb("descfunc", recurse=False) else None
):
    return True
elif level == 0 and (
    (not obj.flag("touchbit") and (str_v := obj.getp("first_description"))) or (str_v := obj.getp("description"))
):
    print(str_v, end="")
elif level == 0:
    print("There is a " + obj.desc() + " here", end="")
    if obj.flag("onbit"):
        print(" (providing light)", end="")
    print(".", end="")
else:
    print(_.table_get(player.zstate_get("INDENTS"), level) + "A " + obj.desc(), end="")
    if obj.flag("onbit"):
        print(" (providing light)", end="")
    elif obj.flag("wearbit") and obj.location == player:
        print(" (being worn)", end="")
# ZIL: <NULL-F ...>
_.zork_thing.null_f()
if level == 0 and (av := player.location) and av.flag("vehicle"):
    print(" (outside the " + av.desc() + ")", end="")
print()
if _.zork_thing.is_see_inside(obj) and obj.contents.first():
    # ZIL: <PRINT-CONT ...>
    return _.zork_thing.print_cont(obj, v_p, level)
