#!moo verb prep_print --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: PREP-PRINT
# params: PREP
# aux: WRD

prep = args[0] if len(args) > 0 else None
wrd = 0

if prep != 0:
    print(" ", end="")
    wrd = _.zork_thing.prep_find(prep)
    print(str(wrd), end="")
    return
