#!moo verb print_contents --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import task_time_low

# ZIL routine: PRINT-CONTENTS
# params: OBJ
# aux: F, N, 1ST?, IT?, TWO?

obj = args[0] if len(args) > 0 else None
f = 0
n = 0
v_1st_p = True
it_p = 0
two_p = 0

if f := obj.contents.first():
    while True:
        if task_time_low():
            print("[zil] long-running loop in PRINT-CONTENTS; aborting (bug — please report).")
            return False
        n = _.next_sibling(f)
        if v_1st_p:
            v_1st_p = False
        else:
            print(", ", end="")
            if not n:
                print("and ", end="")
        print("a " + f.desc(), end="")
        if not it_p and not two_p:
            it_p = f
        else:
            two_p = True
            it_p = False
        f = n
        if not f:
            if it_p and not two_p:
                # ZIL: <THIS-IS-IT ...>
                _.zork_thing.this_is_it(it_p)
            return True
