#!moo verb print_cont --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, task_time_low

# ZIL routine: PRINT-CONT
# params: OBJ, V?, LEVEL
# aux: Y, 1ST?, SHIT, AV, STR, PV?, INV?

player = context.player
obj = args[0] if len(args) > 0 else None
v_p = args[1] if len(args) > 1 else None
level = args[2] if len(args) > 2 else 0
y = 0
v_1st_p = 0
shit = 0
av = 0
str_v = 0
pv_p = 0
inv_p = 0

if not (y := obj.contents.first()):
    return True
if (av := player.location) and av.flag("vehicle"):
    True
else:
    av = False
v_1st_p = True
shit = True
if player in (obj, obj.location):
    inv_p = True
else:
    while True:
        if task_time_low():
            print("[zil] long-running loop in PRINT-CONT; aborting (bug — please report).")
            return False
        if not y:
            break
        elif y == av:
            pv_p = True
        elif y == player:
            pass
        elif not y.flag("invisible") and not y.flag("touchbit") and (str_v := y.getp("first_description")):
            if not y.flag("ndescbit"):
                print(str_v)
                shit = False
            if _.zork_thing.is_see_inside(y) and not y.location.getp("descfcn") and y.contents.first():
                if _.zork_thing.print_cont(y, v_p, 0):
                    v_1st_p = False
        y = _.next_sibling(y)
y = obj.contents.first()
while True:
    if task_time_low():
        print("[zil] long-running loop in PRINT-CONT; aborting (bug — please report).")
        return False
    if not y:
        if pv_p and av and av.contents.first():
            level = level + 1
            # ZIL: <PRINT-CONT ...>
            _.zork_thing.print_cont(av, v_p, level)
        break
    elif y in (av, player):
        pass
    elif not y.flag("invisible") and (inv_p or y.flag("touchbit") or not y.getp("first_description")):
        if not y.flag("ndescbit"):
            if v_1st_p:
                if _.zork_thing.firster(obj, level):
                    if level < 0:
                        level = 0
                level = 1 + level
                v_1st_p = False
            if level < 0:
                level = 0
            # ZIL: <DESCRIBE-OBJECT ...>
            _.zork_thing.describe_object(y, v_p, level)
        elif y.contents.first() and _.zork_thing.is_see_inside(y):
            level = level + 1
            # ZIL: <PRINT-CONT ...>
            _.zork_thing.print_cont(y, v_p, level)
            level = level - 1
    y = _.next_sibling(y)
if v_1st_p and shit:
    return False
else:
    return True
