# Generated by extras/zil_import — do not edit by hand
"""Zork-specific root classes — standalone, no dependency on default bootstrap."""
# pylint: disable=undefined-variable

from moo.core.models.verb import Verb as _Verb

# The system object (_) is created by initialize_dataset.
# Wizard is also created there. Everything else we create from scratch.
# ZIL SDK verbs are attached directly to the System Object, $player, and
# $root_class — translated routines call them as ``_.flag(...)``,
# ``context.player.zstate_set(...)``, ``context.player.move(...)``, etc.

# ---------------------------------------------------------------------------
# Root classes
# ---------------------------------------------------------------------------
# Accept verb — needed so objects can be placed in rooms/containers.
# PROPDEF defaults from zork1.zil go on the root so every object/actor/exit
# inherits them; the WEIGHT routine reads ``size`` on context.player which
# wouldn't have it otherwise.
root, _created = bootstrap.get_or_create_object("Root", unique_name=True)
# Drop any prior ``accept`` rows before re-adding — replace=True only updates
# the first match, so without this every --sync left a leftover row from past
# syncs accumulating until ``add_verb`` raised AmbiguousVerbError on dispatch.
_Verb.objects.filter(origin=root, names__name="accept").delete()
root.add_verb("accept", code="return True")
root.set_property("size", 5)
root.set_property("capacity", 0)
root.set_property("value", 0)
root.set_property("tvalue", 0)

# ``thing`` is the only substrate handle that lives on the System
# Object — translated routines invoke cross-class verbs via
# ``_.thing.foo()`` (predicates, dispatchers, M-clause splits).  The
# remaining substrate classes are reachable via ``--on "Zork <Class>"`` at
# verb-load time and need no system-property alias.
thing, _created = bootstrap.get_or_create_object("Thing", unique_name=True, parents=[root])
thing.set_property("takeable", False)
thing.set_property("size", 5)
thing.set_property("value", 0)
thing.set_property("tvalue", 0)
thing.set_property("readable", False)
thing.set_property("flammable", False)
_.set_property("thing", thing)

container, _created = bootstrap.get_or_create_object("Container", unique_name=True, parents=[thing])
container.set_property("takeable", False)
container.set_property("open", False)
container.set_property("size", 10)
container.set_property("capacity", 10)
container.set_property("value", 0)

room, _created = bootstrap.get_or_create_object("Room", unique_name=True, parents=[root])
room.set_property("value", 0)
room.set_property("discovered", False)
room.set_property("outdoor", False)
room.set_property("sacred", False)
room.set_property("maze", False)
# Default rooms to dark; ROOM_FLAG_PROPERTIES maps ZIL ``ONBIT`` → ``dark=False``
# so any canonical-lit room overrides the default at object emission.
room.set_property("dark", True)

# Actor inherits from Thing so per-object actor handlers
# (e.g. troll's TROLL-FCN ``examine`` / ``attack``) can ``passthrough()``
# to the Thing substrate.  In canonical ZIL an actor IS a thing —
# V-EXAMINE / V-ATTACK / V-TAKE all dispatch on actors via the same
# substrate routines as inert objects, with per-object FCN handlers
# supplying the actor-specific responses.  Without Thing in the
# chain, ``passthrough()`` from a per-object actor handler walks
# ``[Actor]`` only and never finds the substrate, so a clause
# like the troll's ``examine`` handler returning ``passthrough()``
# emits a RuntimeWarning and the player sees no body.
actor, _created = bootstrap.get_or_create_object("Actor", unique_name=True, parents=[thing])
# ``get_or_create_object`` only wires up parents on first create; for DBs
# bootstrapped before Actor inherited from Thing, fix the chain
# in place so existing actor objects pick up the substrate verbs without
# a full reset.
if thing not in actor.parents.all():
    actor.parents.add(thing)

# Wizard must inherit from Actor so the parser can resolve verbs
# registered ``--on "Actor"`` when commands dispatch on the Wizard
# avatar.
if actor not in wizard.parents.all():
    wizard.parents.add(actor)

exit, _created = bootstrap.get_or_create_object("Exit", unique_name=True, parents=[root])

# Actor NPC — mirrors $npc from default bootstrap.  ACTORBIT objects
# (thief, troll, cyclops, bat, ghosts) are reparented here instead of to
# Actor so they pick up the personality hook (``act`` verb) and
# anonymous-Player-record lifecycle, modeled after the default ``$npc``
# class.  Player-character placeholders (ME, ADVENTURER, PLAYER, WINNER)
# stay on Actor — giving them an anonymous Player row would collide
# with the real connected player.
actor_npc, _created = bootstrap.get_or_create_object("Actor NPC", unique_name=True, parents=[actor])
if actor not in actor_npc.parents.all():
    actor_npc.parents.add(actor)

_classes = {
    "root": root,
    "thing": thing,
    "container": container,
    "room": room,
    "actor": actor,
    "actor_npc": actor_npc,
    "exit": exit,
}
log.info("Zork classes: %d created/updated", len(_classes))
