# Generated by moo/zil_import — do not edit by hand
"""ZIL table data stored as list properties on the System Object."""
# pylint: disable=undefined-variable

# Tables are stored with zstate_ prefix so pick() can find them.
# Key conversion: UPPER-KEBAB-CASE -> lower_snake_case with zstate_ prefix.

_.set_property("zstate_p_cctbl", [0, 0, 0, 0])
_.set_property("zstate_oops_table", [None, None, None, None])
_.set_property("zstate_p_itbl", [0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
_.set_property("zstate_p_otbl", [0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
_.set_property("zstate_p_vtbl", [0, 0, 0, 0])
_.set_property(
    "zstate_p_ovtbl",
    [
        0,
        _rooms.get("#BYTE") or _objects.get("#BYTE") or "#BYTE",
        0,
        _rooms.get("#BYTE") or _objects.get("#BYTE") or "#BYTE",
        0,
    ],
)
_.set_property(
    "zstate_jumploss",
    [
        4,
        0,
        "You should have looked before you leaped.",
        "In the movies, your life would be passing before your eyes.",
        "Geronimo...",
    ],
)
_.set_property(
    "zstate_wheeeee",
    [
        5,
        0,
        "Very good. Now you can go to the second grade.",
        "Are you enjoying yourself?",
        "Wheeeeeeeeee!!!!!",
        "Do you expect me to applaud?",
    ],
)
_.set_property("zstate_indents", ["", "  ", "    ", "      ", "        ", "          "])
_.set_property("zstate_ho_hum", [4, 0, " doesn't seem to work.", " isn't notably helpful.", " has no effect."])
_.set_property("zstate_hellos", [5, 0, "Hello.", "Good day.", "Nice weather we've been having lately.", "Goodbye."])
_.set_property(
    "zstate_yuks", [5, 0, "A valiant attempt.", "You can't be serious.", "An interesting idea...", "What a concept!"]
)
_.set_property("zstate_dummy", [4, 0, "Look around.", "Too late for that.", "Have your eyes checked."])
_.set_property(
    "zstate_house_around",
    [
        5,
        _rooms.get("WEST-OF-HOUSE") or _objects.get("WEST-OF-HOUSE") or "WEST-OF-HOUSE",
        _rooms.get("NORTH-OF-HOUSE") or _objects.get("NORTH-OF-HOUSE") or "NORTH-OF-HOUSE",
        _rooms.get("EAST-OF-HOUSE") or _objects.get("EAST-OF-HOUSE") or "EAST-OF-HOUSE",
        _rooms.get("SOUTH-OF-HOUSE") or _objects.get("SOUTH-OF-HOUSE") or "SOUTH-OF-HOUSE",
        _rooms.get("WEST-OF-HOUSE") or _objects.get("WEST-OF-HOUSE") or "WEST-OF-HOUSE",
    ],
)
_.set_property(
    "zstate_forest_around",
    [
        6,
        _rooms.get("FOREST-1") or _objects.get("FOREST-1") or "FOREST-1",
        _rooms.get("FOREST-2") or _objects.get("FOREST-2") or "FOREST-2",
        _rooms.get("FOREST-3") or _objects.get("FOREST-3") or "FOREST-3",
        _rooms.get("PATH") or _objects.get("PATH") or "PATH",
        _rooms.get("CLEARING") or _objects.get("CLEARING") or "CLEARING",
        _rooms.get("FOREST-1") or _objects.get("FOREST-1") or "FOREST-1",
    ],
)
_.set_property(
    "zstate_in_house_around",
    [
        4,
        _rooms.get("LIVING-ROOM") or _objects.get("LIVING-ROOM") or "LIVING-ROOM",
        _rooms.get("KITCHEN") or _objects.get("KITCHEN") or "KITCHEN",
        _rooms.get("ATTIC") or _objects.get("ATTIC") or "ATTIC",
        _rooms.get("KITCHEN") or _objects.get("KITCHEN") or "KITCHEN",
    ],
)
_.set_property(
    "zstate_above_ground",
    [
        11,
        _rooms.get("WEST-OF-HOUSE") or _objects.get("WEST-OF-HOUSE") or "WEST-OF-HOUSE",
        _rooms.get("NORTH-OF-HOUSE") or _objects.get("NORTH-OF-HOUSE") or "NORTH-OF-HOUSE",
        _rooms.get("EAST-OF-HOUSE") or _objects.get("EAST-OF-HOUSE") or "EAST-OF-HOUSE",
        _rooms.get("SOUTH-OF-HOUSE") or _objects.get("SOUTH-OF-HOUSE") or "SOUTH-OF-HOUSE",
        _rooms.get("FOREST-1") or _objects.get("FOREST-1") or "FOREST-1",
        _rooms.get("FOREST-2") or _objects.get("FOREST-2") or "FOREST-2",
        _rooms.get("FOREST-3") or _objects.get("FOREST-3") or "FOREST-3",
        _rooms.get("PATH") or _objects.get("PATH") or "PATH",
        _rooms.get("CLEARING") or _objects.get("CLEARING") or "CLEARING",
        _rooms.get("GRATING-CLEARING") or _objects.get("GRATING-CLEARING") or "GRATING-CLEARING",
        _rooms.get("CANYON-VIEW") or _objects.get("CANYON-VIEW") or "CANYON-VIEW",
    ],
)
_.set_property(
    "zstate_bat_drops",
    [
        9,
        0,
        _rooms.get("MINE-1") or _objects.get("MINE-1") or "MINE-1",
        _rooms.get("MINE-2") or _objects.get("MINE-2") or "MINE-2",
        _rooms.get("MINE-3") or _objects.get("MINE-3") or "MINE-3",
        _rooms.get("MINE-4") or _objects.get("MINE-4") or "MINE-4",
        _rooms.get("LADDER-TOP") or _objects.get("LADDER-TOP") or "LADDER-TOP",
        _rooms.get("LADDER-BOTTOM") or _objects.get("LADDER-BOTTOM") or "LADDER-BOTTOM",
        _rooms.get("SQUEEKY-ROOM") or _objects.get("SQUEEKY-ROOM") or "SQUEEKY-ROOM",
        _rooms.get("MINE-ENTRANCE") or _objects.get("MINE-ENTRANCE") or "MINE-ENTRANCE",
    ],
)
_.set_property(
    "zstate_loud_runs",
    [
        4,
        0,
        _rooms.get("DAMP-CAVE") or _objects.get("DAMP-CAVE") or "DAMP-CAVE",
        _rooms.get("ROUND-ROOM") or _objects.get("ROUND-ROOM") or "ROUND-ROOM",
        _rooms.get("DEEP-CANYON") or _objects.get("DEEP-CANYON") or "DEEP-CANYON",
    ],
)
_.set_property(
    "zstate_drownings",
    [
        "up to your ankles.",
        "up to your shin.",
        "up to your knees.",
        "up to your hips.",
        "up to your waist.",
        "up to your chest.",
        "up to your neck.",
        "over your head.",
        "high in your lungs.",
    ],
)
_.set_property(
    "zstate_cyclomad",
    [
        "The cyclops seems somewhat agitated.",
        "The cyclops appears to be getting more agitated.",
        "The cyclops is moving about the room, looking for something.",
        "The cyclops was looking for salt and pepper. No doubt they are\ncondiments for his upcoming snack.",
        "The cyclops is moving toward you in an unfriendly manner.",
        "You have two choices: 1. Leave  2. Become dinner.",
    ],
)
_.set_property(
    "zstate_lamp_table",
    [100, "The lamp appears a bit dimmer.", 70, "The lamp is definitely dimmer now.", 15, "The lamp is nearly out.", 0],
)
_.set_property(
    "zstate_candle_table",
    [
        20,
        "The candles grow shorter.",
        10,
        "The candles are becoming quite short.",
        5,
        "The candles won't last long now.",
        0,
    ],
)
_.set_property(
    "zstate_river_speeds",
    [
        10,
        _rooms.get("RIVER-1") or _objects.get("RIVER-1") or "RIVER-1",
        4,
        _rooms.get("RIVER-2") or _objects.get("RIVER-2") or "RIVER-2",
        4,
        _rooms.get("RIVER-3") or _objects.get("RIVER-3") or "RIVER-3",
        3,
        _rooms.get("RIVER-4") or _objects.get("RIVER-4") or "RIVER-4",
        2,
        _rooms.get("RIVER-5") or _objects.get("RIVER-5") or "RIVER-5",
        1,
    ],
)
_.set_property(
    "zstate_river_next",
    [
        5,
        _rooms.get("RIVER-1") or _objects.get("RIVER-1") or "RIVER-1",
        _rooms.get("RIVER-2") or _objects.get("RIVER-2") or "RIVER-2",
        _rooms.get("RIVER-3") or _objects.get("RIVER-3") or "RIVER-3",
        _rooms.get("RIVER-4") or _objects.get("RIVER-4") or "RIVER-4",
        _rooms.get("RIVER-5") or _objects.get("RIVER-5") or "RIVER-5",
    ],
)
_.set_property(
    "zstate_river_launch",
    [
        16,
        _rooms.get("DAM-BASE") or _objects.get("DAM-BASE") or "DAM-BASE",
        _rooms.get("RIVER-1") or _objects.get("RIVER-1") or "RIVER-1",
        _rooms.get("WHITE-CLIFFS-NORTH") or _objects.get("WHITE-CLIFFS-NORTH") or "WHITE-CLIFFS-NORTH",
        _rooms.get("RIVER-3") or _objects.get("RIVER-3") or "RIVER-3",
        _rooms.get("WHITE-CLIFFS-SOUTH") or _objects.get("WHITE-CLIFFS-SOUTH") or "WHITE-CLIFFS-SOUTH",
        _rooms.get("RIVER-4") or _objects.get("RIVER-4") or "RIVER-4",
        _rooms.get("SHORE") or _objects.get("SHORE") or "SHORE",
        _rooms.get("RIVER-5") or _objects.get("RIVER-5") or "RIVER-5",
        _rooms.get("SANDY-BEACH") or _objects.get("SANDY-BEACH") or "SANDY-BEACH",
        _rooms.get("RIVER-4") or _objects.get("RIVER-4") or "RIVER-4",
        _rooms.get("RESERVOIR-SOUTH") or _objects.get("RESERVOIR-SOUTH") or "RESERVOIR-SOUTH",
        _rooms.get("RESERVOIR") or _objects.get("RESERVOIR") or "RESERVOIR",
        _rooms.get("RESERVOIR-NORTH") or _objects.get("RESERVOIR-NORTH") or "RESERVOIR-NORTH",
        _rooms.get("RESERVOIR") or _objects.get("RESERVOIR") or "RESERVOIR",
        _rooms.get("STREAM-VIEW") or _objects.get("STREAM-VIEW") or "STREAM-VIEW",
        _rooms.get("IN-STREAM") or _objects.get("IN-STREAM") or "IN-STREAM",
    ],
)
_.set_property(
    "zstate_bdigs",
    [
        "You seem to be digging a hole here.",
        "The hole is getting deeper, but that's about it.",
        "You are surrounded by a wall of sand on all sides.",
    ],
)
_.set_property("zstate_def1", [1, 1, 1, 1, 6, 6, 2, 2, 3, 3, 3, 3, 3])
_.set_property("zstate_def2a", [1, 1, 1, 1, 1, 6, 6, 4, 4, 2])
_.set_property("zstate_def2b", [1, 1, 1, 6, 6, 4, 4, 4, 2, 3, 3, 3])
_.set_property("zstate_def3a", [1, 1, 1, 1, 1, 6, 6, 4, 4, 5, 5])
_.set_property("zstate_def3b", [1, 1, 1, 6, 6, 4, 4, 4, 5, 5, 5])
_.set_property("zstate_def3c", [1, 6, 6, 4, 4, 4, 4, 5, 5, 5])
_.set_property("zstate_def1_res", [_.get_property("zstate_def1"), 0, 0])
_.set_property("zstate_def2_res", [_.get_property("zstate_def2a"), _.get_property("zstate_def2b"), 0, 0])
_.set_property(
    "zstate_def3_res",
    [_.get_property("zstate_def3a"), 0, _.get_property("zstate_def3b"), 0, _.get_property("zstate_def3c")],
)
_.set_property(
    "zstate_hero_melee",
    [
        [
            6,
            [5, "Your ", 0, " misses the ", 1, " by an inch."],
            [3, "A good slash, but it misses the ", 1, " by a mile."],
            [3, "You charge, but the ", 1, " jumps nimbly aside."],
            [3, "Clang! Crash! The ", 1, " parries."],
            [3, "A quick stroke, but the ", 1, " is on guard."],
            [3, "A good stroke, but it's too slow; the ", 1, " dodges."],
        ],
        [
            5,
            [5, "Your ", 0, " crashes down, knocking the ", 1, " into dreamland."],
            [3, "The ", 1, " is battered into unconsciousness."],
            [3, "A furious exchange, and the ", 1, " is knocked out!"],
            [5, "The haft of your ", 0, " knocks out the ", 1, "."],
            [3, "The ", 1, " is knocked out!"],
        ],
        [
            3,
            [5, "It's curtains for the ", 1, " as your ", 0, " removes his head."],
            [3, "The fatal blow strikes the ", 1, " square in the heart: He dies."],
            [3, "The ", 1, " takes a fatal blow and slumps to the floor dead."],
        ],
        [
            4,
            [3, "The ", 1, " is struck on the arm; blood begins to trickle down."],
            [5, "Your ", 0, " pinks the ", 1, " on the wrist, but it's not serious."],
            [1, "Your stroke lands, but it was only the flat of the blade."],
            [3, "The blow lands, making a shallow gash in the ", 1, "'s arm!"],
        ],
        [
            4,
            [3, "The ", 1, " receives a deep gash in his side."],
            [3, "A savage blow on the thigh! The ", 1, " is stunned but can still fight!"],
            [1, "Slash! Your blow lands! That one hit an artery, it could be serious!"],
            [1, "Slash! Your stroke connects! This could be serious!"],
        ],
        [
            5,
            [3, "The ", 1, " is staggered, and drops to his knees."],
            [3, "The ", 1, " is momentarily disoriented and can't fight back."],
            [3, "The force of your blow knocks the ", 1, " back, stunned."],
            [3, "The ", 1, " is confused and can't fight back."],
            [3, "The quickness of your thrust knocks the ", 1, " back, stunned."],
        ],
        [
            2,
            [3, "The ", 1, "'s weapon is knocked to the floor, leaving him unarmed."],
            [3, "The ", 1, " is disarmed by a subtle feint past his guard."],
        ],
    ],
)
_.set_property(
    "zstate_cyclops_melee",
    [
        [
            2,
            [1, "The Cyclops misses, but the backwash almost knocks you over."],
            [1, "The Cyclops rushes you, but runs into the wall."],
        ],
        [1, [1, "The Cyclops sends you crashing to the floor, unconscious."]],
        [1, [1, "The Cyclops breaks your neck with a massive smash."]],
        [2, [1, "A quick punch, but it was only a glancing blow."], [1, "A glancing blow from the Cyclops' fist."]],
        [
            2,
            [1, "The monster smashes his huge fist into your chest, breaking several\nribs."],
            [1, "The Cyclops almost knocks the wind out of you with a quick punch."],
        ],
        [
            2,
            [1, "The Cyclops lands a punch that knocks the wind out of you."],
            [1, "Heedless of your weapons, the Cyclops tosses you against the rock\nwall of the room."],
        ],
        [
            2,
            [3, "The Cyclops grabs your ", 0, ", tastes it, and throws it to the\nground in disgust."],
            [3, "The monster grabs you on the wrist, squeezes, and you drop your\n", 0, " in pain."],
        ],
        [1, [1, "The Cyclops seems unable to decide whether to broil or stew his\ndinner."]],
        [1, [1, "The Cyclops, no sportsman, dispatches his unconscious victim."]],
    ],
)
_.set_property(
    "zstate_troll_melee",
    [
        [
            4,
            [1, "The troll swings his axe, but it misses."],
            [1, "The troll's axe barely misses your ear."],
            [1, "The axe sweeps past as you jump aside."],
            [1, "The axe crashes against the rock, throwing sparks!"],
        ],
        [1, [1, "The flat of the troll's axe hits you delicately on the head, knocking\nyou out."]],
        [
            3,
            [1, "The troll neatly removes your head."],
            [1, "The troll's axe stroke cleaves you from the nave to the chops."],
            [1, "The troll's axe removes your head."],
        ],
        [
            4,
            [1, "The axe gets you right in the side. Ouch!"],
            [1, "The flat of the troll's axe skins across your forearm."],
            [1, "The troll's swing almost knocks you over as you barely parry\nin time."],
            [1, "The troll swings his axe, and it nicks your arm as you dodge."],
        ],
        [
            3,
            [3, "The troll charges, and his axe slashes you on your ", 0, " arm."],
            [1, "An axe stroke makes a deep wound in your leg."],
            [1, "The troll's axe swings down, gashing your shoulder."],
        ],
        [
            4,
            [1, "The troll hits you with a glancing blow, and you are momentarily\nstunned."],
            [1, "The troll swings; the blade turns on your armor but crashes\nbroadside into your head."],
            [1, "You stagger back under a hail of axe strokes."],
            [1, "The troll's mighty blow drops you to your knees."],
        ],
        [
            3,
            [3, "The axe hits your ", 0, " and knocks it spinning."],
            [3, "The troll swings, you parry, but the force of his blow knocks your ", 0, " away."],
            [3, "The axe knocks your ", 0, " out of your hand. It falls to the floor."],
        ],
        [
            2,
            [1, "The troll hesitates, fingering his axe."],
            [1, "The troll scratches his head ruminatively:  Might you be magically\nprotected, he wonders?"],
        ],
        [1, [1, "Conquering his fears, the troll puts you to death."]],
    ],
)
_.set_property(
    "zstate_thief_melee",
    [
        [
            4,
            [1, "The thief stabs nonchalantly with his stiletto and misses."],
            [1, "You dodge as the thief comes in low."],
            [1, "You parry a lightning thrust, and the thief salutes you with\na grim nod."],
            [1, "The thief tries to sneak past your guard, but you twist away."],
        ],
        [
            2,
            [1, "Shifting in the midst of a thrust, the thief knocks you unconscious\nwith the haft of his stiletto."],
            [1, "The thief knocks you out."],
        ],
        [
            3,
            [1, "Finishing you off, the thief inserts his blade into your heart."],
            [1, "The thief comes in from the side, feints, and inserts the blade\ninto your ribs."],
            [1, "The thief bows formally, raises his stiletto, and with a wry grin,\nends the battle and your life."],
        ],
        [
            4,
            [1, "A quick thrust pinks your left arm, and blood starts to\ntrickle down."],
            [1, "The thief draws blood, raking his stiletto across your arm."],
            [1, "The stiletto flashes faster than you can follow, and blood wells\nfrom your leg."],
            [1, "The thief slowly approaches, strikes like a snake, and leaves\nyou wounded."],
        ],
        [
            4,
            [1, "The thief strikes like a snake! The resulting wound is serious."],
            [1, "The thief stabs a deep cut in your upper arm."],
            [1, "The stiletto touches your forehead, and the blood obscures your\nvision."],
            [1, "The thief strikes at your wrist, and suddenly your grip is slippery\nwith blood."],
        ],
        [
            3,
            [1, "The butt of his stiletto cracks you on the skull, and you stagger\nback."],
            [1, "The thief rams the haft of his blade into your stomach, leaving\nyou out of breath."],
            [1, "The thief attacks, and you fall back desperately."],
        ],
        [
            3,
            [
                5,
                "A long, theatrical slash. You catch it on your ",
                0,
                ", but the\nthief twists his knife, and the ",
                0,
                " goes flying.",
            ],
            [3, "The thief neatly flips your ", 0, " out of your hands, and it drops\nto the floor."],
            [3, "You parry a low thrust, and your ", 0, " slips out of your hand."],
        ],
        [
            3,
            [
                1,
                "The thief, a man of superior breeding, pauses for a moment to consider the propriety of finishing you off.",
            ],
            [1, "The thief amuses himself by searching your pockets."],
            [1, "The thief entertains himself by rifling your pack."],
        ],
        [
            2,
            [1, "The thief, forgetting his essentially genteel upbringing, cuts your\nthroat."],
            [1, "The thief, a pragmatist, dispatches you as a threat to his\nlivelihood."],
        ],
    ],
)
_.set_property(
    "zstate_villains",
    [
        3,
        [
            _rooms.get("TROLL") or _objects.get("TROLL") or "TROLL",
            _rooms.get("SWORD") or _objects.get("SWORD") or "SWORD",
            1,
            0,
            _.get_property("zstate_troll_melee"),
        ],
        [
            _rooms.get("THIEF") or _objects.get("THIEF") or "THIEF",
            _rooms.get("KNIFE") or _objects.get("KNIFE") or "KNIFE",
            1,
            0,
            _.get_property("zstate_thief_melee"),
        ],
        [
            _rooms.get("CYCLOPS") or _objects.get("CYCLOPS") or "CYCLOPS",
            None,
            0,
            0,
            _.get_property("zstate_cyclops_melee"),
        ],
    ],
)

# Canonical START routine slices: DEFx-RES slots point into DEFx.
_def1 = _.get_property("zstate_def1")
_.set_property("zstate_def1_res", [_def1, _def1[1:], _def1[2:]])
_def2a = _.get_property("zstate_def2a")
_def2b = _.get_property("zstate_def2b")
_.set_property("zstate_def2_res", [_def2a, _def2b, _def2b[1:], _def2b[2:]])
_def3a = _.get_property("zstate_def3a")
_def3b = _.get_property("zstate_def3b")
_def3c = _.get_property("zstate_def3c")
_.set_property("zstate_def3_res", [_def3a, _def3a[1:], _def3b, _def3b[1:], _def3c])

log.info("Zork 1" + " tables: 41 loaded onto System Object")

# Z-machine header for V-VERSION: bytes 0-1=release, 18-23=serial.
_.set_property(
    "zstate_version_table",
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ord("0"), ord("2"), ord("0"), ord("4"), ord("2"), ord("4")],
)
