# Generated by extras/zil_import — do not edit by hand
"""Reset stale realtime-daemon scheduling state at bootstrap."""
# pylint: disable=undefined-variable

from django_celery_beat.models import PeriodicTask

# Drop any stale realtime-daemon PTs from a prior bootstrap.  The
# matching ones are re-created on demand by translated GO / room
# enterfunc / object handlers that call _.schedule_realtime().
# Don't unpack into ``_`` — that shadows the System Object.
_swept_count, _swept_breakdown = PeriodicTask.objects.filter(description__startswith="zork1-daemon:").delete()
_.set_property("_realtime_pts", {})
log.info("zork1 realtime daemons: swept %d stale PT row(s)", _swept_count)
