# Generated by extras/zil_import — do not edit by hand
"""Adventurer avatar + Player record migration.

Per-instance ACL grants are NOT here — the M2M signal on
``Object.parents`` fires each Zork class's ``initialize`` verb
(``Thing/initialize`` etc.) when objects were first created in
``020_rooms.py`` / ``030_objects.py`` / etc.

The Adventurer itself owns its own object and properties, so the
``owners`` group rule covers ``anything`` without needing ``everyone``
grants on it.
"""
# pylint: disable=undefined-variable

from django.contrib.auth.models import User
from moo.core.models.auth import Player

_actor = lookup("Actor")

# Adventurer is single-inheritance from Actor (same parent chain
# as Wizard, but with `wizard=False` on its Player record so ACL checks
# actually fire instead of getting bypassed by the wizards group rule).
# Adventurer ends up self-owned so all its own state mutations succeed
# via the ``owners`` group rule. First-create owner is the bootstrap
# caller (wizard) — required by the unsaved-owner check at object.py:976
# — then a second save reassigns ownership to Adventurer itself.
adventurer, _adv_created = bootstrap.get_or_create_object("Adventurer", unique_name=True, parents=[_actor])
if _adv_created:
    adventurer.owner = adventurer
    adventurer.save()
_site = adventurer.site

# Set VOWELBIT on Adventurer so the article helper produces "an Adventurer"
# rather than "a Adventurer".  V-TELL's "You can't talk to <article> <obj>!"
# rebuke would otherwise grammar-bug on every NPC-tell that resolves dobj
# back to the player.
adventurer.set_property("vowelbit", True)


# Migrate phil's Player record (or any pre-existing record) to point at
# Adventurer with wizard=False.  If phil's User row hasn't been created
# yet (fresh DB), skip — the SSH server auto-provisions a wizard avatar
# on first connect, which a re-run of this bootstrap will then migrate.
try:
    _phil = User.objects.get(username="phil")
except User.DoesNotExist:
    _phil = None
if _phil is not None:
    Player.objects.update_or_create(
        user=_phil,
        site=_site,
        defaults=dict(avatar=adventurer, wizard=False),
    )
    log.info("Adventurer Player record wired for phil on %s", _site.domain)
