# Generated by extras/zil_import — do not edit by hand
"""
Zork 1 bootstrap for DjangoMOO.

Load with:
    manage.py moo_init --bootstrap zork1

World statistics (as parsed from dungeon.zil / actions.zil):
    Rooms:   110
    Objects: 140

Derived from the Infocom Zork 1 source (dungeon.zil / actions.zil), released
under the MIT License by Microsoft / Activision Publishing, Inc. in 2025.
See LICENSE and README.md in this directory for full terms and credits.

Zork is a registered trademark of Activision Publishing, Inc.
"""
# pylint: disable=no-name-in-module,c-extension-no-member

import importlib.resources
import logging
import secrets
from time import time

from moo import bootstrap
from moo.core import code, lookup

log = logging.getLogger(__name__)
for _line in "ZORK I: The Great Underground Empire\n  Original (c) Infocom, Inc. 1980; MIT-licensed source release 2025.\n  Zork is a registered trademark of Activision Publishing, Inc.\n  DjangoMOO bootstrap: 110 rooms, 140 objects.".splitlines():
    log.info(_line)
_repo = bootstrap.initialize_dataset("zork1")
wizard = lookup("Wizard")
_ = lookup("System Object")

_namespace = {
    "log": log,
    "secrets": secrets,
    "time": time,
    "bootstrap": bootstrap,
    "lookup": lookup,
    "wizard": wizard,
    "repo": _repo,
    "_": _,
}

_pkg = importlib.resources.files("moo.bootstrap.zork1")
_scripts = sorted(
    (f for f in _pkg.iterdir() if f.name.endswith(".py") and f.name[0].isdigit()),
    key=lambda f: f.name,
)

with code.ContextManager(wizard, log.info, site=wizard.site):
    for _script in _scripts:
        exec(compile(_script.read_text(encoding="utf8"), _script.name, "exec"), _namespace)  # pylint: disable=exec-used
    bootstrap.load_verbs(_repo, "moo.bootstrap.zork1.verbs", replace=True)
