#!moo verb examine x describe what --on "kitchen window" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: KITCHEN-WINDOW-F (examine branch)

player = context.player
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if not player.zstate_get("KITCHEN-WINDOW-FLAG"):
    print("The window is slightly ajar, but not enough to allow entry.")
    return
return passthrough()
