#!moo verb go walk move board through --on "kitchen window" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: KITCHEN-WINDOW-F (walk/board/through branch)

player = context.player
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if player.here() == lookup("kitchen"):
    _.walk(player.zstate_get("P?EAST"))
else:
    _.walk(player.zstate_get("P?WEST"))
return True
