#!moo verb kitchen_window_f --on "kitchen window" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL: KITCHEN-WINDOW-F / combined OBJECT-FUNCTION dispatch
# Invoked by ``_.thing.dispatch_object_function(obj, verb, prep, iobj)``
# which looks up ``obj.action`` and calls ``obj.invoke_verb(action_atom, ...)``.

player = context.player
kitchen = lookup("kitchen")
the_verb = args[0] if len(args) > 0 else None
prep = args[1] if len(args) > 1 else None
iobj = args[2] if len(args) > 2 else None
the_player_verb = the_verb

if the_verb == "open" or the_verb == "close":
    player.zstate_set("KITCHEN-WINDOW-FLAG", True)
    # ZIL: <OPEN-CLOSE ...>
    return _.thing.open_close(
        this,
        "With great effort, you open the window far enough to allow entry.",
        "The window closes (more easily than it opened).",
    )
elif the_verb == "examine":
    if not player.zstate_get("KITCHEN-WINDOW-FLAG"):
        print("The window is slightly ajar, but not enough to allow entry.")
        return
elif the_verb == "walk" or the_verb == "board" or the_verb == "through":
    if player.here() == kitchen:
        _.walk(player.zstate_get("P?EAST"))
    else:
        _.walk(player.zstate_get("P?WEST"))
    return True
elif the_verb == "look_inside":
    print("You can see ", end="")
    if player.here() == kitchen:
        print("a clear area leading towards a forest.")
        return
    else:
        print("what appears to be a kitchen.")
        return
return False
