#!moo verb open close shut --on "kitchen window" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: KITCHEN-WINDOW-F (open/close branch)

player = context.player
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

player.zstate_set("KITCHEN-WINDOW-FLAG", True)
# ZIL: <OPEN-CLOSE ...>
return _.zork_thing.open_close(
    this,
    "With great effort, you open the window far enough to allow entry.",
    "The window closes (more easily than it opened).",
)
