#!moo verb bag_of_coins_f --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: BAG-OF-COINS-F

# ZIL: <STUPID-CONTAINER ...>
return _.zork_thing.stupid_container(this, "coins")
