#!moo verb mirror_mirror --on "mirror (MIRROR-1)" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, lookup, task_time_low

# ZIL: MIRROR-MIRROR / combined OBJECT-FUNCTION dispatch
# Invoked by ``_.thing.dispatch_object_function(obj, verb, prep, iobj)``
# which looks up ``obj.action`` and calls ``obj.invoke_verb(action_atom, ...)``.

player = context.player
parser = context.parser
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
the_verb = args[0] if len(args) > 0 else None
prep = args[1] if len(args) > 1 else None
iobj = args[2] if len(args) > 2 else None
rm2 = lookup("mirror_room_2")
l1 = 0
l2 = 0
n = 0
the_player_verb = the_verb

if the_verb == "rub":
    if not player.zstate_get("MIRROR-MUNG"):
        if prsi and not prsi == lookup("hands"):
            print("You feel a faint tingling transmitted through the " + (prsi.desc() if prsi else "") + ".")
            return True
        if player.here() == rm2:
            rm2 = lookup("mirror_room_1")
        l1 = player.here().contents.first()
        l2 = rm2.contents.first()
        while True:
            if task_time_low():
                print("[zil] long-running loop in MIRROR-MIRROR; aborting (bug — please report).")
                return False
            if not l1:
                break
            n = _.next_sibling(l1)
            l1.moveto(rm2)
            l1 = n
        while True:
            if task_time_low():
                print("[zil] long-running loop in MIRROR-MIRROR; aborting (bug — please report).")
                return False
            if not l2:
                break
            n = _.next_sibling(l2)
            l2.moveto(player.here())
            l2 = n
        _.goto(rm2)
        print("There is a rumble from deep within the earth and the room shakes.")
        return
elif the_verb == "look_inside" or the_verb == "examine":
    if player.zstate_get("MIRROR-MUNG"):
        print("The mirror is broken into many pieces.", end="")
    else:
        print("There is an ugly person staring back at you.", end="")
    print()
    return
elif the_verb == "take":
    print("The mirror is many times your size. Give up.")
    return
elif the_verb == "mung" or the_verb == "throw" or the_verb == "attack":
    if player.zstate_get("MIRROR-MUNG"):
        print("Haven't you done enough damage already?")
        return
    else:
        player.zstate_set("MIRROR-MUNG", True)
        player.zstate_set("LUCKY", False)
        print("You have broken the mirror. I hope you have a seven years' supply of\ngood luck handy.")
        return
return False
