#!moo verb take get pick --on "mirror (MIRROR-1)" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import invoked_verb_name, lookup

# ZIL routine: MIRROR-MIRROR (take branch)

rm2 = lookup("mirror_room_2")
l1 = 0
l2 = 0
n = 0
the_player_verb = invoked_verb_name(verb_name)

print("The mirror is many times your size. Give up.")
return
