#!moo verb alarm wake awake surprise startle --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: V-ALARM

parser = context.parser

if (parser.get_dobj() if parser.has_dobj_str() else None).flag("actorbit"):
    if (parser.get_dobj() if parser.has_dobj_str() else None).getp("strength") < 0:
        print("The " + (parser.get_dobj() if parser.has_dobj_str() else None).desc() + " is rudely awakened.")
        # ZIL: <AWAKEN ...>
        return _.zork_thing.awaken((parser.get_dobj() if parser.has_dobj_str() else None))
    else:
        print("He's wide awake, or haven't you noticed...")
        return
else:
    print("The " + (parser.get_dobj() if parser.has_dobj_str() else None).desc() + " isn't sleeping.")
    return
