#!moo verb board --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: V-BOARD
# aux: AV

player = context.player
parser = context.parser
av = 0

pre_x = "pre_board"
if _.zork_thing.invoke_verb(pre_x):
    return
print("You are now in the " + (parser.get_dobj() if parser.has_dobj_str() else None).desc() + ".")
player.moveto((parser.get_dobj() if parser.has_dobj_str() else None))
# ZIL: <APPLY ...>
if (parser.get_dobj() if parser.has_dobj_str() else None) is not None and (
    parser.get_dobj() if parser.has_dobj_str() else None
).has_verb("enterfunc", recurse=False):
    (parser.get_dobj() if parser.has_dobj_str() else None).invoke_verb("enterfunc")
return True
