#!moo verb burn incinerate ignite --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: V-BURN

player = context.player
parser = context.parser

pre_x = "pre_burn"
if _.zork_thing.invoke_verb(pre_x):
    return
if _.zork_thing.null_f():
    return False
elif (parser.get_dobj() if parser.has_dobj_str() else None).flag("flammable"):
    if (parser.get_dobj() if parser.has_dobj_str() else None).location == player or player.location == (
        parser.get_dobj() if parser.has_dobj_str() else None
    ):
        _.remove((parser.get_dobj() if parser.has_dobj_str() else None))
        print(
            "The "
            + (parser.get_dobj() if parser.has_dobj_str() else None).desc()
            + " catches fire. Unfortunately, you were ",
            end="",
        )
        if player.location == (parser.get_dobj() if parser.has_dobj_str() else None):
            print("in", end="")
        else:
            print("holding", end="")
        return _.jigs_up(" it at the time.")
    else:
        _.remove((parser.get_dobj() if parser.has_dobj_str() else None))
        print("The " + (parser.get_dobj() if parser.has_dobj_str() else None).desc() + " catches fire and is consumed.")
        return
else:
    print("You can't burn a " + (parser.get_dobj() if parser.has_dobj_str() else None).desc() + ".")
    return
