#!moo verb command --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: V-COMMAND

parser = context.parser

if (parser.get_dobj() if parser.has_dobj_str() else None).flag("actorbit"):
    print("The " + (parser.get_dobj() if parser.has_dobj_str() else None).desc() + " pays no attention.")
    return
else:
    print("You cannot talk to that!")
    return
