#!moo verb cut slice pierce --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context

# ZIL routine: V-CUT

player = context.player
parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None

if prso is None:
    if context.parser is not None and context.parser.has_dobj_str():
        print("There is no '" + context.parser.dobj_str + "' here.")
    else:
        print("What do you want to cut?")
    return

if prso.flag("actorbit") if prso else None:
    return _.perform("attack", prso, prsi)
elif (prso.flag("flammable") if prso else None) and (prsi.flag("weapon") if prsi else None):
    if player.location == prso:
        print("Not a bright idea, especially since you're in it.")
        return True
    _.remove(prso)
    print(
        "Your skillful "
        + (prsi.desc() if prsi else "")
        + "smanship slices the "
        + (prso.desc() if prso else "")
        + " into innumerable slivers which blow away."
    )
    return
elif not (prsi.flag("weapon") if prsi else None):
    print('The "cutting edge" of a ' + (prsi.desc() if prsi else "") + " is hardly adequate.")
    return
else:
    print("Strange concept, cutting the " + (prso.desc() if prso else "") + "....")
    return
