#!moo verb dig --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: V-DIG

parser = context.parser

if not (parser.get_iobj() if parser.has_iobj() else None):
    # SETG of parser-state slot is a no-op in DjangoMOO
    pass
if (parser.get_iobj() if parser.has_iobj() else None) == lookup("shovel"):
    print("There's no reason to be digging here.")
    return True
if parser.get_iobj().flag("toolbit") if parser.has_iobj() else None:
    print("Digging with the " + (parser.get_iobj().desc() if parser.has_iobj() else "") + " is slow and tedious.")
    return
else:
    print("Digging with a " + (parser.get_iobj().desc() if parser.has_iobj() else "") + " is silly.")
    return
