#!moo verb disembark unboard --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context

# ZIL routine: V-DISEMBARK

player = context.player
parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None

if prso is None:
    if context.parser is not None and context.parser.has_dobj_str():
        print("There is no '" + context.parser.dobj_str + "' here.")
    else:
        print("What do you want to disembark?")
    return

if prso == player.zstate_get("ROOMS") and player.location.flag("vehicle"):
    _.perform("disembark", player.location, None)
    return True
elif player.location != prso:
    print("You're not in that!")
    # ZIL: <RFATAL ...>
    return 2
elif player.here().flag("outdoor"):
    print("You are on your own feet again.")
    return player.moveto(player.here())
else:
    print("You realize that getting out here would be fatal.")
    # ZIL: <RFATAL ...>
    return 2
