#!moo verb fill --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: V-FILL

player = context.player
parser = context.parser
global_water = lookup("global_water")
water = lookup("water")

pre_x = "pre_fill"
if _.zork_thing.invoke_verb(pre_x):
    return
if not (parser.get_iobj() if parser.has_iobj() else None):
    if global_water.global_in(player.here()):
        _.perform("fill", (parser.get_dobj() if parser.has_dobj_str() else None), global_water)
        return True
    elif water.location == player.location:
        _.perform("fill", (parser.get_dobj() if parser.has_dobj_str() else None), water)
        return True
    else:
        print("There's nothing to fill it with.")
        return
else:
    print("You may know how to do that, but I don't.")
    return
