#!moo verb lamp_off extinguish douse --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: V-LAMP-OFF

player = context.player
parser = context.parser

if (parser.get_dobj() if parser.has_dobj_str() else None).flag("lit"):
    if not (parser.get_dobj() if parser.has_dobj_str() else None).flag("onbit"):
        print("It is already off.")
    else:
        (parser.get_dobj() if parser.has_dobj_str() else None).set_flag("onbit", False)
        if player.zstate_get("LIT"):
            player.zstate_set("LIT", _.zork_thing.is_lit(player.here()))
        print("The " + (parser.get_dobj() if parser.has_dobj_str() else None).desc() + " is now off.")
        if not player.zstate_get("LIT"):
            print("It is now pitch black.")
else:
    print("You can't turn that off.")
return True
