#!moo verb launch --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: V-LAUNCH

parser = context.parser

if (parser.get_dobj() if parser.has_dobj_str() else None).flag("vehicle"):
    print('You can\'t launch that by saying "launch"!')
    return
else:
    print("That's pretty weird.")
    return
