#!moo verb look_inside --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: V-LOOK-INSIDE

parser = context.parser

if (parser.get_dobj() if parser.has_dobj_str() else None).flag("is_door"):
    if (parser.get_dobj() if parser.has_dobj_str() else None).flag("open"):
        print(
            "The "
            + (parser.get_dobj() if parser.has_dobj_str() else None).desc()
            + " is open, but I can't tell what's beyond it.",
            end="",
        )
    else:
        print("The " + (parser.get_dobj() if parser.has_dobj_str() else None).desc() + " is closed.", end="")
    print()
    return
elif (parser.get_dobj() if parser.has_dobj_str() else None).flag("contbit"):
    if (parser.get_dobj() if parser.has_dobj_str() else None).flag("actorbit"):
        print("There is nothing special to be seen.")
        return
    elif _.zork_thing.is_see_inside((parser.get_dobj() if parser.has_dobj_str() else None)):
        if (parser.get_dobj() if parser.has_dobj_str() else None).contents.first() and _.zork_thing.print_cont(
            (parser.get_dobj() if parser.has_dobj_str() else None)
        ):
            return True
        elif _.zork_thing.null_f():
            return True
        else:
            print("The " + (parser.get_dobj() if parser.has_dobj_str() else None).desc() + " is empty.")
            return
    else:
        print("The " + (parser.get_dobj() if parser.has_dobj_str() else None).desc() + " is closed.")
        return
else:
    print("You can't look inside a " + (parser.get_dobj() if parser.has_dobj_str() else None).desc() + ".")
    return
