#!moo verb melt liquify --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: V-MELT

parser = context.parser

print("It's not clear that a " + (parser.get_dobj() if parser.has_dobj_str() else None).desc() + " can be melted.")
return
