#!moo verb open --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context

# ZIL routine: V-OPEN
# aux: F, STR

parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
f = 0
str_v = 0

if prso is None:
    if context.parser is not None and context.parser.has_dobj_str():
        print("There is no '" + context.parser.dobj_str + "' here.")
    else:
        print("What do you want to open?")
    return

if (prso.flag("contbit") if prso else None) and not (prso.getp("capacity") if prso else None) == 0:
    if prso.flag("open") if prso else None:
        print("It is already open.")
        return
    else:
        (prso.set_flag("open", True) if prso else None)
        (prso.set_flag("touchbit", True) if prso else None)
        if not prso.contents.first() or (prso.flag("transparent") if prso else None):
            print("Opened.")
            return
        elif (
            (f := prso.contents.first())
            and not _.next_sibling(f)
            and not f.flag("touchbit")
            and (str_v := f.getp("first_description"))
        ):
            print("The " + (prso.desc() if prso else "") + " opens.")
            print(str_v)
            return
        else:
            print(
                "Opening the " + (prso.desc() if prso else "") + " reveals " + _.zork_thing.print_contents(prso), end=""
            )
            print(".")
            return
elif prso.flag("is_door") if prso else None:
    if prso.flag("open") if prso else None:
        print("It is already open.")
        return
    else:
        print("The " + (prso.desc() if prso else "") + " opens.")
        return prso.set_flag("open", True) if prso else None
else:
    print("You must tell me how to do that to a " + (prso.desc() if prso else "") + ".")
    return
