#!moo verb plug glue patch repair fix --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: V-PLUG

print("This has no effect.")
return
