#!moo verb pour_on --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: V-POUR-ON

parser = context.parser
putty = lookup("putty")

if (parser.get_dobj() if parser.has_dobj_str() else None) == lookup("water"):
    _.remove((parser.get_dobj() if parser.has_dobj_str() else None))
    if flaming_p((parser.get_iobj() if parser.has_iobj() else None)):
        print("The " + (parser.get_iobj().desc() if parser.has_iobj() else "") + " is extinguished.")
        # ZIL: <NULL-F ...>
        _.zork_thing.null_f()
        (parser.get_iobj().set_flag("onbit", False) if parser.has_iobj() else None)
        return parser.get_iobj().set_flag("flamebit", False) if parser.has_iobj() else None
    else:
        print(
            "The water spills over the "
            + (parser.get_iobj().desc() if parser.has_iobj() else "")
            + ", to the floor, and evaporates."
        )
        return
elif (parser.get_dobj() if parser.has_dobj_str() else None) == putty:
    return _.perform("put", putty, (parser.get_iobj() if parser.has_iobj() else None))
else:
    print("You can't pour that.")
    return
