#!moo verb push press move --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: V-PUSH

# ZIL: <HACK-HACK ...>
return _.zork_thing.hack_hack("Pushing the ")
