#!moo verb put apply stuff insert place hide --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: V-PUT

parser = context.parser

pre_x = "pre_put"
if _.zork_thing.invoke_verb(pre_x):
    return
if (
    (parser.get_iobj().flag("open") if parser.has_iobj() else None)
    or (parser.get_iobj().flag("openable") if parser.has_iobj() else None)
    or (parser.get_iobj().flag("vehicle") if parser.has_iobj() else None)
):
    pass
else:
    print("You can't do that.")
    return True
if not (parser.get_iobj().flag("open") if parser.has_iobj() else None):
    print("The " + (parser.get_iobj().desc() if parser.has_iobj() else "") + " isn't open.")
    # ZIL: <THIS-IS-IT ...>
    return _.zork_thing.this_is_it((parser.get_iobj() if parser.has_iobj() else None))
elif (parser.get_iobj() if parser.has_iobj() else None) == (parser.get_dobj() if parser.has_dobj_str() else None):
    print("How can you do that?")
    return
elif (parser.get_dobj() if parser.has_dobj_str() else None).location == (
    parser.get_iobj() if parser.has_iobj() else None
):
    print(
        "The "
        + (parser.get_dobj() if parser.has_dobj_str() else None).desc()
        + " is already in the "
        + (parser.get_iobj().desc() if parser.has_iobj() else "")
        + "."
    )
    return
elif (
    (
        _.zork_thing.weight((parser.get_iobj() if parser.has_iobj() else None))
        + _.zork_thing.weight((parser.get_dobj() if parser.has_dobj_str() else None))
    )
    - (parser.get_iobj().getp("size") if parser.has_iobj() else None)
) > (parser.get_iobj().getp("capacity") if parser.has_iobj() else None):
    print("There's no room.")
    return
elif not _.zork_thing.is_held((parser.get_dobj() if parser.has_dobj_str() else None)) and (
    parser.get_dobj() if parser.has_dobj_str() else None
).flag("trytakebit"):
    print("You don't have the " + (parser.get_dobj() if parser.has_dobj_str() else None).desc() + ".")
    return True
elif not _.zork_thing.is_held((parser.get_dobj() if parser.has_dobj_str() else None)) and not _.zork_thing.itake():
    return True
else:
    (parser.get_dobj() if parser.has_dobj_str() else None).moveto((parser.get_iobj() if parser.has_iobj() else None))
    (parser.get_dobj() if parser.has_dobj_str() else None).set_flag("touchbit", True)
    # ZIL: <SCORE-OBJ ...>
    _.zork_thing.score_obj((parser.get_dobj() if parser.has_dobj_str() else None))
    print("Done.")
    return
