#!moo verb read skim --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: V-READ

parser = context.parser

pre_x = "pre_read"
if _.zork_thing.invoke_verb(pre_x):
    return
if not (parser.get_dobj() if parser.has_dobj_str() else None).flag("readable"):
    print("How does one read a " + (parser.get_dobj() if parser.has_dobj_str() else None).desc() + "?")
    return
else:
    print((parser.get_dobj() if parser.has_dobj_str() else None).getp("text"))
    return
