#!moo verb sgive --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: V-SGIVE

pre_x = "pre_sgive"
if _.zork_thing.invoke_verb(pre_x):
    return
print("Foo!")
return
