#!moo verb sspray --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: V-SSPRAY

parser = context.parser

return _.perform(
    "spray", (parser.get_iobj() if parser.has_iobj() else None), (parser.get_dobj() if parser.has_dobj_str() else None)
)
