#!moo verb stab --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: V-STAB
# aux: W

player = context.player
parser = context.parser
w = 0

if w := _.zork_thing.find_weapon(player):
    _.perform("attack", (parser.get_dobj() if parser.has_dobj_str() else None), w)
    return True
else:
    print(
        "No doubt you propose to stab the "
        + (parser.get_dobj() if parser.has_dobj_str() else None).desc()
        + " with your pinky?"
    )
    return
