#!moo verb take get hold carry remove grab catch pick --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context

# ZIL routine: V-TAKE

parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None

if prso is None:
    if context.parser is not None and context.parser.has_dobj_str():
        print("There is no '" + context.parser.dobj_str + "' here.")
    else:
        print("What do you want to take?")
    return

pre_x = "pre_take"
if _.zork_thing.invoke_verb(pre_x):
    return
if _.zork_thing.itake() == True:
    if prso.flag("wearbit") if prso else None:
        print("You are now wearing the " + (prso.desc() if prso else "") + ".")
        return
    else:
        print("Taken.")
        return
