#!moo verb tell ask --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context

# ZIL routine: V-TELL

player = context.player
parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None

if prso is None:
    if context.parser is not None and context.parser.has_dobj_str():
        print("There is no '" + context.parser.dobj_str + "' here.")
    else:
        print("What do you want to tell?")
    return

if prso.flag("actorbit") if prso else None:
    if player:
        player.zstate_set("WINNER", prso)
        return player.zstate_set("HERE", player.location)
    else:
        print(
            "The "
            + (prso.desc() if prso else "")
            + " pauses for a moment, perhaps thinking that you should reread\nthe manual."
        )
        return
else:
    print("You can't talk to the " + (prso.desc() if prso else "") + "!")
    player.zstate_set("QUOTE-FLAG", False)
    player.zstate_set("P-CONT", False)
    # ZIL: <RFATAL ...>
    return 2
