#!moo verb tell ask --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: V-TELL

player = context.player
parser = context.parser

if (parser.get_dobj() if parser.has_dobj_str() else None).flag("actorbit"):
    if player:
        player.zstate_set("WINNER", (parser.get_dobj() if parser.has_dobj_str() else None))
        return player.zstate_set("HERE", player.location)
    else:
        print(
            "The "
            + (parser.get_dobj() if parser.has_dobj_str() else None).desc()
            + " pauses for a moment, perhaps thinking that you should reread\nthe manual."
        )
        return
else:
    print("You can't talk to the " + (parser.get_dobj() if parser.has_dobj_str() else None).desc() + "!")
    player.zstate_set("QUOTE-FLAG", False)
    player.zstate_set("P-CONT", False)
    # ZIL: <RFATAL ...>
    return 2
