#!moo verb throw hurl chuck toss --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: V-THROW

player = context.player
parser = context.parser

if _.zork_thing.idrop():
    if (parser.get_iobj() if parser.has_iobj() else None) == lookup("me"):
        print("A terrific throw! The " + (parser.get_dobj() if parser.has_dobj_str() else None).desc(), end="")
        player.zstate_set("WINNER", player)
        return _.jigs_up(
            " hits you squarely in the head. Normally,\nthis wouldn't do much damage, but by incredible mischance, you fall over\nbackwards trying to duck, and break your neck, justice being swift and\nmerciful in the Great Underground Empire."
        )
    elif (parser.get_iobj() if parser.has_iobj() else None) and (
        parser.get_iobj().flag("actorbit") if parser.has_iobj() else None
    ):
        print(
            "The "
            + (parser.get_iobj().desc() if parser.has_iobj() else "")
            + " ducks as the "
            + (parser.get_dobj() if parser.has_dobj_str() else None).desc()
            + " flies by and crashes to the ground."
        )
        return
    else:
        print("Thrown.")
        return
else:
    print("Huh?")
    return
