#!moo verb unlock --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: V-UNLOCK

# ZIL: <V-LOCK ...>
return _.zork_thing.lock()
