#!moo verb walk_to --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: V-WALK-TO

player = context.player
parser = context.parser

if (parser.get_dobj() if parser.has_dobj_str() else None) and (
    (parser.get_dobj() if parser.has_dobj_str() else None).location == player.here()
    or (parser.get_dobj() if parser.has_dobj_str() else None).global_in(player.here())
):
    print("It's here!")
    return
else:
    print("You should supply a direction!")
    return
