#!moo verb wear --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: V-WEAR

parser = context.parser

if not (parser.get_dobj() if parser.has_dobj_str() else None).flag("wearbit"):
    print("You can't wear the " + (parser.get_dobj() if parser.has_dobj_str() else None).desc() + ".")
    return
else:
    _.perform("take", (parser.get_dobj() if parser.has_dobj_str() else None), None)
    return True
