#!moo verb look --on "Grating Room" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name, lookup

# ZIL: MAZE-11-FCN / M-LOOK

player = context.player
rarg = args[0] if len(args) > 0 else "M-LOOK"
the_player_verb = args[1] if len(args) > 1 else invoked_verb_name(verb_name)

print(this.desc())
print("You are in a small room near the maze. There are twisty passages\nin the immediate vicinity.")
if lookup("grate").flag("open"):
    print("Above you is an open grating with sunlight pouring in.", end="")
elif player.zstate_get("GRUNLOCK"):
    print("Above you is a grating.", end="")
else:
    print("Above you is a grating locked with a skull-and-crossbones lock.", end="")
print()
_.zork_thing.describe_objects(True)
