#!moo verb stiletto_function --on "Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import lookup

# ZIL routine: STILETTO-FUNCTION

# ZIL: <WEAPON-FUNCTION ...>
return _.thing.weapon_function(this, lookup("thief"))
