#!moo verb through --on "stairs" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import invoked_verb_name

# ZIL routine: STAIRS-F (through branch)

the_player_verb = invoked_verb_name(verb_name)

print("You should say whether you want to go up or down.")
return
