#!moo verb bat_f --on "bat" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL: BAT-F / combined OBJECT-FUNCTION dispatch
# Invoked by ``_.thing.dispatch_object_function(obj, verb, prep, iobj)``
# which looks up ``obj.action`` and calls ``obj.invoke_verb(action_atom, ...)``.

player = context.player
the_verb = args[0] if len(args) > 0 else None
prep = args[1] if len(args) > 1 else None
iobj = args[2] if len(args) > 2 else None
the_player_verb = the_verb

if the_verb == "tell":
    # ZIL: <FWEEP ...>
    _.thing.fweep(6)
    return player.zstate_set("P-CONT", False)
elif the_verb == "take" or the_verb == "attack" or the_verb == "mung":
    if lookup("garlic").location in (player, player.here()):
        print("You can't reach him; he's on the ceiling.")
        return
    else:
        # ZIL: <FLY-ME ...>
        return _.thing.fly_me()
return False
