#!moo verb look --on "Up a Tree" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import invoked_verb_name, lookup

# ZIL: TREE-ROOM / M-LOOK

path = lookup("path")
rarg = args[0] if len(args) > 0 else "M-LOOK"
f = 0
the_player_verb = args[1] if len(args) > 1 else invoked_verb_name(verb_name)

print(this.desc())
print(
    "You are about 10 feet above the ground nestled among some large\nbranches. The nearest branch above you is above your reach."
)
if (f := path.contents.first()) and _.next_sibling(f):
    print("On the ground below you can see:  " + _.zork_thing.print_contents(path), end="")
    print(".")
_.zork_thing.describe_objects(True)
