#!moo verb preturnfunc --on "Up a Tree" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL: TREE-ROOM / M-BEG

player = context.player
parser = context.parser
egg = lookup("egg")
nest = lookup("nest")
path = lookup("path")
tree = lookup("tree")
rarg = args[0] if len(args) > 0 else "M-BEG"
f = 0
the_player_verb = (
    args[1]
    if len(args) > 1
    else (parser.words[0].lower() if context.parser is not None and parser.words else verb_name)
)

if the_player_verb == "climb-down" and (parser.get_dobj() if parser.has_dobj_str() else None) in (
    tree,
    player.zstate_get("ROOMS"),
):
    _.walk(player.zstate_get("P?DOWN"))
    return True
elif the_player_verb in ["climb-up", "climb-foo"] and (parser.get_dobj() if parser.has_dobj_str() else None) == tree:
    _.walk(player.zstate_get("P?UP"))
    return True
elif the_player_verb == "drop":
    if not _.zork_thing.idrop():
        return True
    elif (parser.get_dobj() if parser.has_dobj_str() else None) == nest and egg.location == nest:
        print("The nest falls to the ground, and the egg spills out of it, seriously\ndamaged.")
        _.remove(egg)
        lookup("broken_egg").moveto(path)
    elif (parser.get_dobj() if parser.has_dobj_str() else None) == egg:
        print("The egg falls to the ground and springs open, seriously damaged.", end="")
        egg.moveto(path)
        # ZIL: <BAD-EGG ...>
        _.zork_thing.bad_egg()
        print()
    elif not (parser.get_dobj() if parser.has_dobj_str() else None) in (player, tree):
        (parser.get_dobj() if parser.has_dobj_str() else None).moveto(path)
        print("The " + (parser.get_dobj() if parser.has_dobj_str() else None).desc() + " falls to the ground.")
    elif the_player_verb == "leap":
        _.jigs_up("That was just a bit too far down.")
        return True
