#!moo verb tree_room look preturnfunc enterfunc --on "Up a Tree" --dspec either

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, invoked_verb_name, lookup

# ZIL: TREE-ROOM / combined M-/F-clause dispatch

player = context.player
parser = context.parser
prso = None
if context.parser is not None:
    try:
        prso = parser.get_dobj() if parser.has_dobj_str() else None
    except NoSuchObjectError:
        prso = None
egg = lookup("egg")
nest = lookup("nest")
path = lookup("path")
tree = lookup("tree")
verb_to_const = {"look": "M-LOOK", "preturnfunc": "M-BEG", "enterfunc": "M-ENTER"}
rarg = args[0] if len(args) > 0 else verb_to_const.get(verb_name, "M-LOOK")
f = 0
the_player_verb = args[1] if len(args) > 1 else invoked_verb_name(verb_name)

if rarg == "M-LOOK":
    print(this.desc())
    print(
        "You are about 10 feet above the ground nestled among some large\nbranches. The nearest branch above you is above your reach."
    )
    if (f := path.contents.first()) and _.next_sibling(f):
        print("On the ground below you can see:  " + _.thing.print_contents(path), end="")
        print(".")
    _.thing.describe_objects(True)
elif rarg == "M-BEG":
    if the_player_verb == "climb_down" and prso in (tree, player.zstate_get("ROOMS")):
        _.walk(player.zstate_get("P?DOWN"))
        return True
    elif the_player_verb in ["climb_up", "climb_foo"] and prso == tree:
        _.walk(player.zstate_get("P?UP"))
        return True
    elif the_player_verb == "drop":
        if not _.thing.idrop():
            return True
        elif prso == nest and egg.location == nest:
            print("The nest falls to the ground, and the egg spills out of it, seriously\ndamaged.")
            _.remove(egg)
            lookup("broken_egg").moveto(path)
            return True
        elif prso == egg:
            print("The egg falls to the ground and springs open, seriously damaged.", end="")
            egg.moveto(path)
            # ZIL: <BAD-EGG ...>
            _.thing.bad_egg()
            print()
            return True
        elif not prso in (player, tree):
            prso.moveto(path)
            print("The " + (prso.desc() if prso else "") + " falls to the ground.")
            return True
        elif the_player_verb == "leap":
            _.jigs_up("That was just a bit too far down.")
            return True
elif rarg == "M-ENTER":
    _.schedule_realtime("i_forest_room", -1)
