#!moo verb climb-on --on "carpet" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name, lookup

# ZIL routine: RUG-FCN (climb-on branch)

player = context.player
the_player_verb = invoked_verb_name(verb_name)

if not player.zstate_get("RUG-MOVED") and not lookup("trap_door").flag("open"):
    print("As you sit, you notice an irregularity underneath it. Rather than be\nuncomfortable, you stand up again.")
    return
else:
    print("I suppose you think it's a magic carpet?")
    return
