#!moo verb move push press --on "carpet" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name, lookup

# ZIL routine: RUG-FCN (move/push branch)

player = context.player
trap_door = lookup("trap_door")
the_player_verb = invoked_verb_name(verb_name)

if player.zstate_get("RUG-MOVED"):
    print("Having moved the carpet previously, you find it impossible to move\nit again.")
    return
else:
    print(
        "With a great effort, the rug is moved to one side of the room, revealing\nthe dusty cover of a closed trap door."
    )
    trap_door.set_flag("invisible", False)
    # ZIL: <THIS-IS-IT ...>
    _.zork_thing.this_is_it(trap_door)
    return player.zstate_set("RUG-MOVED", True)
