#!moo verb raise --on "carpet" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name

# ZIL routine: RUG-FCN (raise branch)

player = context.player
the_player_verb = invoked_verb_name(verb_name)

print("The rug is too heavy to lift", end="")
if player.zstate_get("RUG-MOVED"):
    print(".")
    return
else:
    print(", but in trying to take it you have\nnoticed an irregularity beneath it.")
    return
