#!moo verb cyclops_room_fcn look enterfunc --on "Cyclops Room" --dspec either

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name

# ZIL: CYCLOPS-ROOM-FCN / combined M-/F-clause dispatch

player = context.player
verb_to_const = {"look": "M-LOOK", "enterfunc": "M-ENTER"}
rarg = args[0] if len(args) > 0 else verb_to_const.get(verb_name, "M-LOOK")
the_player_verb = args[1] if len(args) > 1 else invoked_verb_name(verb_name)

if rarg == "M-LOOK":
    print(this.desc())
    print("This room has an exit on the northwest, and a staircase leading up.")
    if player.zstate_get("CYCLOPS-FLAG") and not player.zstate_get("MAGIC-FLAG"):
        print("The cyclops is sleeping blissfully at the foot of the stairs.")
    elif player.zstate_get("MAGIC-FLAG"):
        print("The east wall, previously solid, now has a cyclops-sized opening in it.")
    elif player.zstate_get("CYCLOWRATH") == 0:
        print(
            "A cyclops, who looks prepared to eat horses (much less mere\nadventurers), blocks the staircase. From his state of health, and\nthe bloodstains on the walls, you gather that he is not very\nfriendly, though he likes people."
        )
    elif player.zstate_get("CYCLOWRATH") > 0:
        print(
            "The cyclops is standing in the corner, eyeing you closely. I don't\nthink he likes you very much. He looks extremely hungry, even for a\ncyclops."
        )
    elif player.zstate_get("CYCLOWRATH") < 0:
        print(
            "The cyclops, having eaten the hot peppers, appears to be gasping.\nHis enflamed tongue protrudes from his man-sized mouth."
        )
    _.thing.describe_objects(True)
elif rarg == "M-ENTER":
    if player.zstate_get("CYCLOWRATH") == 0:
        return True
    _.queue("i-cyclops", 0)
