#!moo verb enterfunc --on "Cyclops Room" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name

# ZIL: CYCLOPS-ROOM-FCN / M-ENTER

player = context.player
rarg = args[0] if len(args) > 0 else "M-ENTER"
the_player_verb = args[1] if len(args) > 1 else invoked_verb_name(verb_name)

if player.zstate_get("CYCLOWRATH") == 0:
    return True
_.queue("i-cyclops", 0)
