#!moo verb fight_strength --on "Thing" --dspec this

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: FIGHT-STRENGTH
# params: ADJUST?
# aux: S

player = context.player
adjust_p = args[0] if len(args) > 0 else True
s = 0

s = player.zstate_get("STRENGTH-MIN") + (
    player.zstate_get("SCORE")
    // (player.zstate_get("SCORE-MAX") // (player.zstate_get("STRENGTH-MAX") - player.zstate_get("STRENGTH-MIN")))
)
if adjust_p:
    return s + player.getp("strength")
else:
    return s
