#!moo verb steal_junk --on "Thing" --dspec this

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

import random
from moo.sdk import context, lookup, task_time_low

# ZIL routine: STEAL-JUNK
# params: RM
# aux: X, N

player = context.player
rm = args[0] if len(args) > 0 else None
x = 0
n = 0

x = rm.contents.first()
while True:
    if task_time_low():
        print("[zil] long-running loop in STEAL-JUNK; aborting (bug — please report).")
        return False
    if not x:
        return False
    n = _.next_sibling(x)
    if (
        x.getp("tvalue") == 0
        and x.flag("takeable")
        and not x.flag("sacred")
        and not x.flag("invisible")
        and (x == lookup("stiletto") or random.randint(1, 100) <= 10)
    ):
        x.moveto(lookup("thief"))
        x.set_flag("touchbit", True)
        x.set_flag("invisible", True)
        if x == lookup("rope"):
            player.zstate_set("DOME-FLAG", False)
        if rm == player.here():
            print("You suddenly notice that the " + x.desc() + " vanished.")
            return True
        else:
            return False
    x = n
