#!moo verb thief_vs_adventurer --on "Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

import random
from moo.sdk import context, lookup

# ZIL routine: THIEF-VS-ADVENTURER
# params: HERE?
# aux: ROBBED?, WINNER-ROBBED?

player = context.player
thief = lookup("thief")
here_p = args[0] if len(args) > 0 else None
robbed_p = 0
winner_robbed_p = 0

if not player.zstate_get("DEAD") and player.here() == lookup("treasure_room"):
    pass
elif not player.zstate_get("THIEF-HERE"):
    if not player.zstate_get("DEAD") and not here_p and random.randint(1, 100) <= 30:
        if lookup("stiletto").location == thief:
            thief.set_flag("invisible", False)
            print(
                "Someone carrying a large bag is casually leaning against one of the\nwalls here. He does not speak, but it is clear from his aspect that\nthe bag will be taken only over his dead body."
            )
            player.zstate_set("THIEF-HERE", True)
            return True
    elif here_p and thief.flag("hostile") and not _.thing.is_winning(thief):
        print(
            "Your opponent, determining discretion to be the better part of\nvalor, decides to terminate this little contretemps. With a rueful\nnod of his head, he steps backward into the gloom and disappears."
        )
        thief.set_flag("invisible", True)
        thief.set_flag("hostile", False)
        # ZIL: <RECOVER-STILETTO ...>
        _.thing.recover_stiletto()
        return True
    elif here_p and thief.flag("hostile") and random.randint(1, 100) <= 90:
        return False
    elif here_p and random.randint(1, 100) <= 30:
        print("The holder of the large bag just left, looking disgusted.\nFortunately, he took nothing.")
        thief.set_flag("invisible", True)
        # ZIL: <RECOVER-STILETTO ...>
        _.thing.recover_stiletto()
        return True
    elif random.randint(1, 100) <= 70:
        return False
    elif not player.zstate_get("DEAD"):
        if _.thing.rob(player.here(), thief, 100):
            robbed_p = player.here()
        elif _.thing.rob(player, thief):
            robbed_p = player
        player.zstate_set("THIEF-HERE", True)
        if robbed_p and not here_p:
            print(
                "A seedy-looking individual with a large bag just wandered through\nthe room. On the way through, he quietly abstracted some valuables from ",
                end="",
            )
            if robbed_p == player.here():
                print("the room", end="")
            else:
                print("your possession", end="")
            print(', mumbling something about\n"Doing unto others before..."')
            # ZIL: <STOLE-LIGHT? ...>
            _.thing.is_stole_light()
        elif here_p:
            # ZIL: <RECOVER-STILETTO ...>
            _.thing.recover_stiletto()
            if robbed_p:
                print("The thief just left, still carrying his large bag. You may\nnot have noticed that he ", end="")
                if robbed_p == player:
                    print("robbed you blind first.", end="")
                else:
                    print("appropriated the valuables in the room.", end="")
                print()
                # ZIL: <STOLE-LIGHT? ...>
                _.thing.is_stole_light()
            else:
                print("The thief, finding nothing of value, left disgusted.")
            thief.set_flag("invisible", True)
            here_p = False
            return True
        else:
            print(
                'A "lean and hungry" gentleman just wandered through, carrying a\nlarge bag. Finding nothing of value, he left disgruntled.'
            )
            return True
else:
    if here_p:
        if random.randint(1, 100) <= 30:
            if _.thing.rob(player.here(), thief, 100):
                robbed_p = player.here()
            elif _.thing.rob(player, thief):
                robbed_p = player
            if robbed_p:
                print("The thief just left, still carrying his large bag. You may\nnot have noticed that he ", end="")
                if robbed_p == player:
                    print("robbed you blind first.", end="")
                else:
                    print("appropriated the valuables in the room.", end="")
                print()
                # ZIL: <STOLE-LIGHT? ...>
                _.thing.is_stole_light()
            else:
                print("The thief, finding nothing of value, left disgusted.")
            thief.set_flag("invisible", True)
            here_p = False
            # ZIL: <RECOVER-STILETTO ...>
            _.thing.recover_stiletto()
return False
