#!moo verb villain_blow --on "Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

import random
from moo.sdk import context

# ZIL routine: VILLAIN-BLOW
# params: OO, OUT?
# aux: VILLAIN, REMARKS, DWEAPON, ATT, DEF, OA, OD, TBL, RES, NWEAPON

player = context.player
oo = args[0] if len(args) > 0 else None
out_p = args[1] if len(args) > 1 else None
villain = _.table_get(oo, player.zstate_get("V-VILLAIN"))
remarks = _.table_get(oo, player.zstate_get("V-MSGS"))
dweapon = 0
att = 0
def_v = 0
oa = 0
od = 0
tbl = 0
res = 0
nweapon = 0

player.set_flag("staggered", False)
if villain.flag("staggered"):
    print("The " + villain.desc() + " slowly regains his feet.")
    villain.set_flag("staggered", False)
    return True
oa = (att := _.thing.villain_strength(oo))
if not (def_v := _.thing.fight_strength()) > 0:
    return True
od = _.thing.fight_strength(False)
dweapon = _.thing.find_weapon(player)
if def_v < 0:
    res = player.zstate_get("KILLED")
else:
    if def_v == 1:
        if att > 2:
            att = 3
        tbl = _.table_get(player.zstate_get("DEF1-RES"), (att - 1))
    elif def_v == 2:
        if att > 3:
            att = 4
        tbl = _.table_get(player.zstate_get("DEF2-RES"), (att - 1))
    elif def_v > 2:
        att = att - def_v
        if att < -1:
            att = -2
        elif att > 1:
            att = 2
        tbl = _.table_get(player.zstate_get("DEF3-RES"), (att + 2))
    res = _.table_get(tbl, (random.randint(1, 9) - 1))
    if out_p:
        if res == player.zstate_get("STAGGER"):
            res = player.zstate_get("HESITATE")
        else:
            res = player.zstate_get("SITTING-DUCK")
    if res == player.zstate_get("STAGGER") and dweapon and random.randint(1, 100) <= 25:
        res = player.zstate_get("LOSE-WEAPON")
    # ZIL: <REMARK ...>
    _.thing.remark(_.thing.random_element(_.table_get(remarks, (res - 1))), player, dweapon)
if res == player.zstate_get("MISSED") or res == player.zstate_get("HESITATE"):
    pass
elif res == player.zstate_get("UNCONSCIOUS"):
    pass
elif res == player.zstate_get("KILLED") or res == player.zstate_get("SITTING-DUCK"):
    def_v = 0
elif res == player.zstate_get("LIGHT-WOUND"):
    def_v = def_v - 1
    if def_v < 0:
        def_v = 0
    if player.zstate_get("LOAD-ALLOWED") > 50:
        player.zstate_set("LOAD-ALLOWED", (player.zstate_get("LOAD-ALLOWED") - 10))
elif res == player.zstate_get("SERIOUS-WOUND"):
    def_v = def_v - 2
    if def_v < 0:
        def_v = 0
    if player.zstate_get("LOAD-ALLOWED") > 50:
        player.zstate_set("LOAD-ALLOWED", (player.zstate_get("LOAD-ALLOWED") - 20))
elif res == player.zstate_get("STAGGER"):
    player.set_flag("staggered", True)
else:
    dweapon.moveto(player.here())
    if nweapon := _.thing.find_weapon(player):
        print("Fortunately, you still have a " + nweapon.desc() + ".")
# ZIL: <WINNER-RESULT ...>
return _.thing.winner_result(def_v, res, od)
