#!moo verb burn count describe examine insert lamp-off lamp-on light place put what x --on "pair of candles" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, invoked_verb_name, lookup

# ZIL routine: CANDLES-FCN

player = context.player
parser = context.parser
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
match = lookup("match")
the_player_verb = invoked_verb_name(verb_name)

if not this.flag("touchbit"):
    _.queue("i-candles", 0)
if this == prsi:
    return False
else:
    if the_player_verb in ["lamp-on", "burn", "light"]:
        if this.flag("rmungbit"):
            print("Alas, there's not much left of the candles. Certainly not enough to\nburn.")
            return
        elif not prsi:
            if match.flag("flamebit"):
                print("(with the match)")
                _.perform("lamp_on", this, match)
                return True
            else:
                print("You should say what to light them with.")
                # ZIL: <RFATAL ...>
                return 2
        elif prsi == match and match.flag("onbit"):
            print("The candles are ", end="")
            if this.flag("onbit"):
                print("already lit.")
                return
            else:
                this.set_flag("onbit", True)
                print("lit.")
                return _.queue("i-candles", 0)
        elif prsi == lookup("torch"):
            if this.flag("onbit"):
                print("You realize, just in time, that the candles are already lighted.")
                return
            else:
                print("The heat from the torch is so intense that the candles are vaporized.")
                return _.remove(this)
        else:
            print("You have to light them with something that's burning, you know.")
            return
    elif the_player_verb == "count":
        print("Let's see, how many objects in a pair? Don't tell me, I'll get it.")
        return
    elif the_player_verb == "lamp-off":
        _.cancel("i-candles")
        if this.flag("onbit"):
            print("The flame is extinguished.", end="")
            this.set_flag("onbit", False)
            this.set_flag("touchbit", True)
            player.zstate_set("LIT", _.zork_thing.is_lit(player.here()))
            if not player.zstate_get("LIT"):
                print(" It's really dark in here....", end="")
            print()
            return True
        else:
            print("The candles are not lighted.")
            return
    elif the_player_verb in ["put", "place", "insert"] and (prsi.flag("flammable") if prsi else None):
        print("That wouldn't be smart.")
        return
    elif the_player_verb in ["examine", "x", "describe", "what"]:
        print("The candles are ", end="")
        if this.flag("onbit"):
            print("burning.", end="")
        else:
            print("out.", end="")
        print()
        return
