#!moo verb i_cure --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: I-CURE
# aux: S

player = context.player
s = player.getp("strength")

if s > 0:
    s = 0
    player.set_property("strength", s)
elif s < 0:
    s = s + 1
    player.set_property("strength", s)
if s < 0:
    if player.zstate_get("LOAD-ALLOWED") < player.zstate_get("LOAD-MAX"):
        player.zstate_set("LOAD-ALLOWED", (player.zstate_get("LOAD-ALLOWED") + 10))
    return _.queue("i-cure", player.zstate_get("CURE-WAIT"))
else:
    player.zstate_set("LOAD-ALLOWED", player.zstate_get("LOAD-MAX"))
    return _.cancel("i-cure")
