#!moo verb i_lantern --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: I-LANTERN
# aux: TICK, TBL

player = context.player
tick = 0
tbl = value(player.zstate_get("LAMP-TABLE"))

_.queue("i-lantern", (tick := _.table_get(tbl, 0)))
# ZIL: <LIGHT-INT ...>
_.zork_thing.light_int(lookup("lamp"), tbl, tick)
if tick != 0:
    return player.zstate_set("LAMP-TABLE", _.rest(tbl, 4))
