#!moo verb look --on "West of House" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name

# ZIL: WEST-HOUSE / M-LOOK

player = context.player
rarg = args[0] if len(args) > 0 else "M-LOOK"
the_player_verb = args[1] if len(args) > 1 else invoked_verb_name(verb_name)

print(this.desc())
print("You are standing in an open field west of a white house, with a boarded\nfront door.", end="")
if player.zstate_get("WON-FLAG"):
    print(" A secret path leads southwest into the forest.", end="")
print()
_.zork_thing.describe_objects(True)
