#!moo verb examine x describe what --on "group of tool chests" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import invoked_verb_name

# ZIL routine: TOOL-CHEST-FCN (examine branch)

the_player_verb = invoked_verb_name(verb_name)

print("The chests are all empty.")
return
