#!moo verb take get pick open put place insert --on "group of tool chests" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: TOOL-CHEST-FCN (take/open/put branch)

the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

_.remove(this)
print("The chests are so rusty and corroded that they crumble when you\ntouch them.")
return
