#!moo verb tool_chest_fcn --on "group of tool chests" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL: TOOL-CHEST-FCN / combined OBJECT-FUNCTION dispatch
# Invoked by ``_.thing.dispatch_object_function(obj, verb, prep, iobj)``
# which looks up ``obj.action`` and calls ``obj.invoke_verb(action_atom, ...)``.

the_verb = args[0] if len(args) > 0 else None
prep = args[1] if len(args) > 1 else None
iobj = args[2] if len(args) > 2 else None
the_player_verb = the_verb

if the_verb == "examine":
    print("The chests are all empty.")
    return
elif the_verb == "take" or the_verb == "open" or the_verb == "put":
    _.remove(this)
    print("The chests are so rusty and corroded that they crumble when you\ntouch them.")
    return
elif the_verb == "open":
    print("The chests are already open.")
    return
return False
