#!moo verb bats_room look enterfunc --on "Bat Room" --dspec either

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name, lookup

# ZIL: BATS-ROOM / combined M-/F-clause dispatch

player = context.player
verb_to_const = {"look": "M-LOOK", "enterfunc": "M-ENTER"}
rarg = args[0] if len(args) > 0 else verb_to_const.get(verb_name, "M-LOOK")
the_player_verb = args[1] if len(args) > 1 else invoked_verb_name(verb_name)

if rarg == "M-LOOK":
    print(this.desc())
    print("You are in a small room which has doors only to the east and south.")
    _.thing.describe_objects(True)
elif rarg == "M-ENTER":
    if not player.zstate_get("DEAD"):
        if not lookup("garlic").location in (player, player.here()):
            # ZIL: <V-LOOK ...>
            _.thing.look()
            print()
            # ZIL: <FLY-ME ...>
            _.thing.fly_me()
