#!moo verb walk_around --on "white house" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name

# ZIL routine: WHITE-HOUSE-F (walk-around branch)

player = context.player
the_player_verb = invoked_verb_name(verb_name)

# ZIL: <GO-NEXT ...>
_.thing.go_next(player.zstate_get("HOUSE-AROUND"))
return True
