#!moo verb white_house_f --on "white house" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL: WHITE-HOUSE-F / combined OBJECT-FUNCTION dispatch
# Invoked by ``_.thing.dispatch_object_function(obj, verb, prep, iobj)``
# which looks up ``obj.action`` and calls ``obj.invoke_verb(action_atom, ...)``.

player = context.player
kitchen_window = lookup("kitchen_window")
the_verb = args[0] if len(args) > 0 else None
prep = args[1] if len(args) > 1 else None
iobj = args[2] if len(args) > 2 else None
the_player_verb = the_verb

if the_verb == "find":
    print("It's right here! Are you blind or something?")
    return
elif the_verb == "walk_around":
    # ZIL: <GO-NEXT ...>
    _.thing.go_next(player.zstate_get("HOUSE-AROUND"))
    return True
elif the_verb == "examine":
    print(
        "The house is a beautiful colonial house which is painted white.\nIt is clear that the owners must have been extremely wealthy."
    )
    return
elif the_verb == "through" or the_verb == "open":
    if player.here() == lookup("east_of_house"):
        if kitchen_window.flag("open"):
            return _.goto(lookup("kitchen"))
        else:
            print("The window is closed.")
            # ZIL: <THIS-IS-IT ...>
            return _.thing.this_is_it(kitchen_window)
    else:
        print("I can't see how to get in from here.")
        return
elif the_verb == "burn":
    print("You must be joking.")
    return
return False
