#!moo verb turnfunc --on "Living Room" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL: LIVING-ROOM-FCN / M-END

player = context.player
parser = context.parser
trophy_case = lookup("trophy_case")
rarg = args[0] if len(args) > 0 else "M-END"
rug_p = 0
the_player_verb = (
    args[1]
    if len(args) > 1
    else (parser.words[0].lower() if context.parser is not None and parser.words else verb_name)
)

if the_player_verb in ["take", "get", "pick"] or (
    the_player_verb in ["put", "place", "insert"] and (parser.get_iobj() if parser.has_iobj() else None) == trophy_case
):
    if (parser.get_dobj() if parser.has_dobj_str() else None).location == trophy_case:
        # ZIL: <TOUCH-ALL ...>
        _.zork_thing.touch_all((parser.get_dobj() if parser.has_dobj_str() else None))
    player.zstate_set("SCORE", (player.zstate_get("BASE-SCORE") + _.zork_thing.otval_frob()))
    # ZIL: <SCORE-UPD ...>
    _.zork_thing.score_upd(0)
    return False
