#!moo verb dam_room_fcn look --on "Dam" --dspec either

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name

# ZIL: DAM-ROOM-FCN / combined M-/F-clause dispatch

player = context.player
verb_to_const = {"look": "M-LOOK"}
rarg = args[0] if len(args) > 0 else verb_to_const.get(verb_name, "M-LOOK")
the_player_verb = args[1] if len(args) > 1 else invoked_verb_name(verb_name)

if rarg == "M-LOOK":
    print(this.desc())
    print(
        "You are standing on the top of the Flood Control Dam #3, which was\nquite a tourist attraction in times far distant. There are paths to\nthe north, south, and west, and a scramble down."
    )
    if player.zstate_get("LOW-TIDE") and player.zstate_get("GATES-OPEN"):
        print(
            "The water level behind the dam is low: The sluice gates have been\nopened. Water rushes through the dam and downstream."
        )
    elif player.zstate_get("GATES-OPEN"):
        print(
            "The sluice gates are open, and water rushes through the dam. The\nwater level behind the dam is still high."
        )
    elif player.zstate_get("LOW-TIDE"):
        print(
            "The sluice gates are closed. The water level in the reservoir is\nquite low, but the level is rising quickly."
        )
    else:
        print(
            "The sluice gates on the dam are closed. Behind the dam, there can be\nseen a wide reservoir. Water is pouring over the top of the now\nabandoned dam."
        )
    print(
        "There is a control panel here, on which a large metal bolt is mounted.\nDirectly above the bolt is a small green plastic bubble",
        end="",
    )
    if player.zstate_get("GATE-FLAG"):
        print(" which is\nglowing serenely", end="")
    print(".")
    _.thing.describe_objects(True)
