#!moo verb climb-down climb-foo climb-up through --on "chute" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, invoked_verb_name, lookup

# ZIL routine: SLIDE-FUNCTION

player = context.player
parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
cellar = lookup("cellar")
the_player_verb = invoked_verb_name(verb_name)

if the_player_verb in ["through", "climb-up", "climb-down", "climb-foo"] or (
    the_player_verb in ["put", "place", "insert"] and prso == lookup("me")
):
    if player.here() == cellar:
        _.walk(player.zstate_get("P?WEST"))
        return True
    else:
        print("You tumble down the slide....")
        return _.goto(cellar)
return passthrough()
