#!moo verb put place insert --on "chute" --dspec any --ispec on:this in:this at:this with:this from:this under:this over:this before:this around:this through:this behind:this beside:this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, invoked_verb_name

# ZIL routine: SLIDE-FUNCTION (put branch)

parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
the_player_verb = invoked_verb_name(verb_name)

if this not in (prso, prsi):
    return passthrough()

# ZIL: <SLIDER ...>
return _.thing.slider(prso)
