#!moo verb is_accessible --on "Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: ACCESSIBLE?
# params: OBJ
# aux: L

player = context.player
obj = args[0] if len(args) > 0 else None
l = obj.location

if obj.flag("invisible"):
    return False
elif not l:
    return False
elif l == lookup("global_objects"):
    return True
elif l == lookup("local_globals") and obj.global_in(player.here()):
    return True
elif not _.thing.meta_loc(obj) in (player.here(), player.location):
    return False
elif l in (player, player.here(), player.location):
    return True
elif l.flag("open") and _.thing.is_accessible(l):
    return True
else:
    return False
