#!moo verb is_forest_room --on "Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: FOREST-ROOM?

player = context.player

if player.here() in (lookup("forest_1"), lookup("forest_2"), lookup("forest_3")):
    return True
return player.here() in (lookup("path"), lookup("up_a_tree"))
