#!moo verb is_infested --on "Thing" --dspec this

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import task_time_low

# ZIL routine: INFESTED?
# params: R
# aux: F

r = args[0] if len(args) > 0 else None
f = r.contents.first()

while True:
    if task_time_low():
        print("[zil] long-running loop in INFESTED?; aborting (bug — please report).")
        return False
    if not f:
        return False
    elif f.flag("actorbit") and not f.flag("invisible"):
        return True
    elif not (f := _.next_sibling(f)):
        return False
