#!moo verb is_winning --on "Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

import random

# ZIL routine: WINNING?
# params: V
# aux: VS, PS

v = args[0] if len(args) > 0 else None
vs = 0
ps = 0

vs = v.getp("strength")
ps = vs - _.thing.fight_strength()
if ps > 3:
    return random.randint(1, 100) <= 90
elif ps > 0:
    return random.randint(1, 100) <= 75
elif ps == 0:
    return random.randint(1, 100) <= 50
elif vs > 1:
    return random.randint(1, 100) <= 25
else:
    return random.randint(1, 100) <= 10
