#!moo verb look --on "Reservoir" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name

# ZIL: RESERVOIR-FCN / M-LOOK

player = context.player
rarg = args[0] if len(args) > 0 else "M-LOOK"
the_player_verb = args[1] if len(args) > 1 else invoked_verb_name(verb_name)

print(this.desc())
if player.zstate_get("LOW-TIDE"):
    print(
        'You are on what used to be a large lake, but which is now a large\nmud pile. There are "shores" to the north and south.',
        end="",
    )
else:
    print(
        "You are on the lake. Beaches can be seen north and south.\nUpstream a small stream enters the lake through a narrow cleft\nin the rocks. The dam can be seen downstream.",
        end="",
    )
print()
_.zork_thing.describe_objects(True)
