#!moo verb reservoir_fcn turnfunc look --on "Reservoir" --dspec either

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name

# ZIL: RESERVOIR-FCN / combined M-/F-clause dispatch

player = context.player
verb_to_const = {"turnfunc": "M-END", "look": "M-LOOK"}
rarg = args[0] if len(args) > 0 else verb_to_const.get(verb_name, "M-END")
the_player_verb = args[1] if len(args) > 1 else invoked_verb_name(verb_name)

if rarg == "M-END":
    if not player.location.flag("vehicle") and not player.zstate_get("GATES-OPEN") and player.zstate_get("LOW-TIDE"):
        print(
            "You notice that the water level here is rising rapidly. The currents\nare also becoming stronger. Staying here seems quite perilous!"
        )
elif rarg == "M-LOOK":
    print(this.desc())
    if player.zstate_get("LOW-TIDE"):
        print(
            'You are on what used to be a large lake, but which is now a large\nmud pile. There are "shores" to the north and south.',
            end="",
        )
    else:
        print(
            "You are on the lake. Beaches can be seen north and south.\nUpstream a small stream enters the lake through a narrow cleft\nin the rocks. The dam can be seen downstream.",
            end="",
        )
    print()
    _.thing.describe_objects(True)
