#!moo verb reservoir_fcn --on "Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: RESERVOIR-FCN
# params: RARG

player = context.player
rarg = args[0] if len(args) > 0 else None

if (
    rarg == "M-END"
    and not player.location.flag("vehicle")
    and not player.zstate_get("GATES-OPEN")
    and player.zstate_get("LOW-TIDE")
):
    print(
        "You notice that the water level here is rising rapidly. The currents\nare also becoming stronger. Staying here seems quite perilous!"
    )
    return
return passthrough()
