#!moo verb board --on "magic boat" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: RBOAT-FUNCTION (board branch)

player = context.player
punctured_boat = lookup("punctured_boat")
rarg = args[0] if len(args) > 0 else None
tmp = 0
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if (
    lookup("sceptre").location == player
    or lookup("knife").location == player
    or lookup("sword").location == player
    or lookup("rusty_knife").location == player
    or lookup("axe").location == player
    or lookup("stiletto").location == player
):
    print(
        "Oops! Something sharp seems to have slipped and punctured the boat.\nThe boat deflates to the sounds of hissing, sputtering, and cursing."
    )
    _.remove(this)
    punctured_boat.moveto(player.here())
    # ZIL: <THIS-IS-IT ...>
    return _.zork_thing.this_is_it(punctured_boat)
return passthrough()
