#!moo verb deflate --on "magic boat" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: RBOAT-FUNCTION (deflate branch)

player = context.player
inflatable_boat = lookup("inflatable_boat")
rarg = args[0] if len(args) > 0 else None
tmp = 0
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if player.location == this:
    print("You can't deflate the boat while you're in it.")
    return
elif not this.location == player.here():
    print("The boat must be on the ground to be deflated.")
    return
else:
    print("The boat deflates.")
    player.zstate_set("DEFLATE", True)
    _.remove(this)
    inflatable_boat.moveto(player.here())
    # ZIL: <THIS-IS-IT ...>
    return _.zork_thing.this_is_it(inflatable_boat)
