#!moo verb preturnfunc --on "magic boat" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, lookup

# ZIL: RBOAT-FUNCTION / M-BEG

player = context.player
parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
in_stream = lookup("in_stream")
reservoir = lookup("reservoir")
rarg = args[0] if len(args) > 0 else "M-BEG"
tmp = 0
the_player_verb = (
    args[1]
    if len(args) > 1
    else (parser.words[0].lower() if context.parser is not None and parser.words else verb_name)
)

if the_player_verb in ["go", "walk", "move"]:
    if parser.get_dobj_str() in ("land", "east", "west"):
        return False
    elif player.here() == reservoir and parser.get_dobj_str() in ("north", "south"):
        return False
    elif player.here() == in_stream and parser.get_dobj_str() == "south":
        return False
    else:
        print("Read the label for the boat's instructions.")
        return True
elif the_player_verb == "launch":
    if player.here() in (lookup("river_1"), lookup("river_2"), lookup("river_3")) or player.here() in (
        lookup("river_4"),
        reservoir,
        in_stream,
    ):
        print("You are on the ", end="")
        if player.here() == reservoir:
            print("reservoir", end="")
        elif player.here() == in_stream:
            print("stream", end="")
        else:
            print("river", end="")
        print(", or have you forgotten?")
    elif (tmp := _.zork_thing.go_next(player.zstate_get("RIVER-LAUNCH"))) == 1:
        _.queue("i-river", _.zork_thing.lkp(player.here(), player.zstate_get("RIVER-SPEEDS")))
        return True
    elif tmp != 2:
        print("You can't launch it here.")
        return True
    else:
        return True
elif (
    (the_player_verb == "drop" and (prso.flag("weapon") if prso else None))
    or (the_player_verb in ["put", "place", "insert"] and (prso.flag("weapon") if prso else None) and prsi == this)
    or (
        the_player_verb
        in ["attack", "kill", "hit", "fight", "stab", "cut", "slice", "mung", "destroy", "break", "smash", "crack"]
        and (prsi.flag("weapon") if prsi else None)
    )
):
    _.remove(this)
    lookup("punctured_boat").moveto(player.here())
    # ZIL: <ROB ...>
    _.zork_thing.rob(this, player.here())
    player.moveto(player.here())
    print("It seems that the ", end="")
    if the_player_verb in ["drop", "put", "place", "insert"]:
        print((prso.desc() if prso else ""), end="")
    else:
        print((prsi.desc() if prsi else ""), end="")
    print(
        " didn't agree with the boat, as evidenced\nby the loud hissing noise issuing therefrom. With a pathetic sputter, the\nboat deflates, leaving you without."
    )
    if player.here().flag("nonlandbit"):
        print()
        if player.here() in (reservoir, in_stream):
            _.jigs_up("Another pathetic sputter, this time from you, heralds your drowning.")
        else:
            _.jigs_up(
                "In other words, fighting the fierce currents of the Frigid River. You\nmanage to hold your own for a bit, but then you are carried over a\nwaterfall and into some nasty rocks. Ouch!"
            )
    return True
elif the_player_verb == "launch":
    print("You're not in the boat!")
    return True
