#!moo verb count open --on "matchbook" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: MATCH-FUNCTION (count/open branch)

player = context.player
cnt = 0
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

print("You have ", end="")
cnt = player.zstate_get("MATCH-COUNT") - 1
if not cnt > 0:
    print("no", end="")
else:
    print(str(cnt), end="")
print(" match", end="")
if cnt != 1:
    print("es.", end="")
else:
    print(".", end="")
print()
return
