#!moo verb lamp_off --on "matchbook" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name

# ZIL routine: MATCH-FUNCTION (lamp-off branch)

player = context.player
cnt = 0
the_player_verb = invoked_verb_name(verb_name)

if this.flag("flamebit"):
    print("The match is out.")
    this.set_flag("flamebit", False)
    this.set_flag("onbit", False)
    player.zstate_set("LIT", _.thing.is_lit(player.here()))
    if not player.zstate_get("LIT"):
        print("It's pitch black in here!")
    _.schedule_realtime("i_match", 0)
    return True
return passthrough()
