#!moo verb lamp_off --on "torch" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, invoked_verb_name

# ZIL routine: TORCH-OBJECT (lamp-off branch)

parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
the_player_verb = invoked_verb_name(verb_name)

if prso.flag("onbit") if prso else None:
    print("You nearly burn your hand trying to extinguish the flame.")
    return
return passthrough()
