#!moo verb leap through --on "river" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import invoked_verb_name

# ZIL routine: RIVER-FUNCTION (leap/through branch)

the_player_verb = invoked_verb_name(verb_name)

print(
    "A look before leaping reveals that the river is wide and dangerous,\nwith swift currents and large, half-hidden rocks. You decide to forgo your\nswim."
)
return
