#!moo verb put place insert --on "river" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: RIVER-FUNCTION (put branch)

parser = context.parser
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if (parser.get_iobj() if parser.has_iobj() else None) == this:
    if (parser.get_dobj() if parser.has_dobj_str() else None) == lookup("me"):
        return _.jigs_up("You splash around for a while, fighting the current, then you drown.")
    elif (parser.get_dobj() if parser.has_dobj_str() else None) == lookup("inflated_boat"):
        print("You should get in the boat then launch it.")
        return
    elif (parser.get_dobj() if parser.has_dobj_str() else None).flag("flammable"):
        _.remove((parser.get_dobj() if parser.has_dobj_str() else None))
        print(
            "The " + (parser.get_dobj() if parser.has_dobj_str() else None).desc() + " floats for a moment, then sinks."
        )
        return
    else:
        _.remove((parser.get_dobj() if parser.has_dobj_str() else None))
        print(
            "The "
            + (parser.get_dobj() if parser.has_dobj_str() else None).desc()
            + " splashes into the water and is gone forever."
        )
        return
return passthrough()
