#!moo verb find where take get pick --on "songbird" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import invoked_verb_name

# ZIL routine: SONGBIRD-F (find/take branch)

the_player_verb = invoked_verb_name(verb_name)

print("The songbird is not here but is probably nearby.")
return
