#!moo verb songbird_f --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: SONGBIRD-F

print("You can't see any songbird here.")
return
