#!moo verb dig --on "sand" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, invoked_verb_name, lookup

# ZIL routine: SAND-FUNCTION (dig branch)

player = context.player
parser = context.parser
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
scarab = lookup("scarab")
the_player_verb = invoked_verb_name(verb_name)

if prsi == lookup("shovel"):
    player.zstate_set("BEACH-DIG", (1 + player.zstate_get("BEACH-DIG")))
    if player.zstate_get("BEACH-DIG") > 3:
        player.zstate_set("BEACH-DIG", -1)
        if scarab.location == player.here():
            scarab.set_flag("invisible", True)
        return _.jigs_up("The hole collapses, smothering you.")
    elif player.zstate_get("BEACH-DIG") == 3:
        if scarab.flag("invisible"):
            print("You can see a scarab here in the sand.")
            # ZIL: <THIS-IS-IT ...>
            _.zork_thing.this_is_it(scarab)
            return scarab.set_flag("invisible", False)
    else:
        print(_.table_get(player.zstate_get("BDIGS"), player.zstate_get("BEACH-DIG")))
        return
return passthrough()
