#!moo verb sand_function --on "sand" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, lookup

# ZIL: SAND-FUNCTION / combined OBJECT-FUNCTION dispatch
# Invoked by ``_.thing.dispatch_object_function(obj, verb, prep, iobj)``
# which looks up ``obj.action`` and calls ``obj.invoke_verb(action_atom, ...)``.

player = context.player
parser = context.parser
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
scarab = lookup("scarab")
the_verb = args[0] if len(args) > 0 else None
prep = args[1] if len(args) > 1 else None
iobj = args[2] if len(args) > 2 else None
the_player_verb = the_verb

if the_verb == "dig":
    if prsi == lookup("shovel"):
        player.zstate_set("BEACH-DIG", (1 + player.zstate_get("BEACH-DIG")))
        if player.zstate_get("BEACH-DIG") > 3:
            player.zstate_set("BEACH-DIG", -1)
            if scarab.location == player.here():
                scarab.set_flag("invisible", True)
            return _.jigs_up("The hole collapses, smothering you.")
        elif player.zstate_get("BEACH-DIG") == 3:
            if scarab.flag("invisible"):
                print("You can see a scarab here in the sand.")
                # ZIL: <THIS-IS-IT ...>
                _.thing.this_is_it(scarab)
                return scarab.set_flag("invisible", False)
        else:
            print(_.table_get(player.zstate_get("BDIGS"), player.zstate_get("BEACH-DIG")))
            return
return False
