#!moo verb burn light --on "black book" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, invoked_verb_name

# ZIL routine: BLACK-BOOK (burn branch)

parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
the_player_verb = invoked_verb_name(verb_name)

_.remove(prso)
return _.jigs_up(
    'A booming voice says "Wrong, cretin!" and you notice that you have\nturned into a pile of dust. How, I can\'t imagine.'
)
