#!moo verb open --on "black book" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import invoked_verb_name

# ZIL routine: BLACK-BOOK (open branch)

the_player_verb = invoked_verb_name(verb_name)

print("The book is already open to page 569.")
return
