#!moo verb read-page rotate turn --on "black book" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: BLACK-BOOK

player = context.player
parser = context.parser
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if the_player_verb in ["turn", "rotate"] or (
    the_player_verb == "read-page"
    and (parser.get_iobj() if parser.has_iobj() else None) == lookup("intnum")
    and not player.zstate_get("P-NUMBER") == 569
):
    print(
        "Beside page 569, there is only one other page with any legible printing on\nit. Most of it is unreadable, but the subject seems to be the banishment of\nevil. Apparently, certain noises, lights, and prayers are efficacious in this\nregard."
    )
    return
return passthrough()
