#!moo verb insert leap place put throw-off --on "cliff" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: CLIFF-OBJECT

parser = context.parser
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if the_player_verb == "leap" or (
    the_player_verb in ["put", "place", "insert"]
    and (parser.get_dobj() if parser.has_dobj_str() else None) == lookup("me")
):
    print("That would be very unwise. Perhaps even fatal.")
    return
elif (parser.get_iobj() if parser.has_iobj() else None) == this:
    if the_player_verb in ["put", "place", "insert", "throw-off"]:
        print(
            "The "
            + (parser.get_dobj() if parser.has_dobj_str() else None).desc()
            + " tumbles into the river and is seen no more."
        )
        return _.remove((parser.get_dobj() if parser.has_dobj_str() else None))
