#!moo verb insert leap place put throw-off --on "cliff" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, invoked_verb_name, lookup

# ZIL routine: CLIFF-OBJECT

parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
the_player_verb = invoked_verb_name(verb_name)

if the_player_verb == "leap" or (the_player_verb in ["put", "place", "insert"] and prso == lookup("me")):
    print("That would be very unwise. Perhaps even fatal.")
    return
elif prsi == this:
    if the_player_verb in ["put", "place", "insert", "throw-off"]:
        print("The " + (prso.desc() if prso else "") + " tumbles into the river and is seen no more.")
        return _.remove(prso)
