#!moo verb hello hi --on "sailor" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name

# ZIL routine: SAILOR-FCN (hello branch)

player = context.player
the_player_verb = invoked_verb_name(verb_name)

player.zstate_set("HS", (player.zstate_get("HS") + 1))
if player.zstate_get("HS") % 20 == 0:
    print("You seem to be repeating yourself.")
    return
elif player.zstate_get("HS") % 10 == 0:
    print("I think that phrase is getting a bit worn out.")
    return
else:
    print("Nothing happens here.")
    return
