#!moo verb cellar_fcn look enterfunc --on "Cellar" --dspec either

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import invoked_verb_name, lookup

# ZIL: CELLAR-FCN / combined M-/F-clause dispatch

trap_door = lookup("trap_door")
verb_to_const = {"look": "M-LOOK", "enterfunc": "M-ENTER"}
rarg = args[0] if len(args) > 0 else verb_to_const.get(verb_name, "M-LOOK")
the_player_verb = args[1] if len(args) > 1 else invoked_verb_name(verb_name)

if rarg == "M-LOOK":
    print(this.desc())
    print(
        "You are in a dark and damp cellar with a narrow passageway leading\nnorth, and a crawlway to the south. On the west is the bottom of a\nsteep metal ramp which is unclimbable."
    )
    _.thing.describe_objects(True)
elif rarg == "M-ENTER":
    if trap_door.flag("open") and not trap_door.flag("touchbit"):
        trap_door.set_flag("open", False)
        trap_door.set_flag("touchbit", True)
        print("The trap door crashes shut, and you hear someone barring it.")
