#!moo verb enterfunc --on "Cellar" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL: CELLAR-FCN / M-ENTER

parser = context.parser
trap_door = lookup("trap_door")
rarg = args[0] if len(args) > 0 else "M-ENTER"
the_player_verb = (
    args[1]
    if len(args) > 1
    else (parser.words[0].lower() if context.parser is not None and parser.words else verb_name)
)

if trap_door.flag("open") and not trap_door.flag("touchbit"):
    trap_door.set_flag("open", False)
    trap_door.set_flag("touchbit", True)
    print("The trap door crashes shut, and you hear someone barring it.")
