#!moo verb look --on "Cellar" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import invoked_verb_name

# ZIL: CELLAR-FCN / M-LOOK

rarg = args[0] if len(args) > 0 else "M-LOOK"
the_player_verb = args[1] if len(args) > 1 else invoked_verb_name(verb_name)

print(this.desc())
print(
    "You are in a dark and damp cellar with a narrow passageway leading\nnorth, and a crawlway to the south. On the west is the bottom of a\nsteep metal ramp which is unclimbable."
)
_.zork_thing.describe_objects(True)
