#!moo verb wave raise --on "sceptre" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: SCEPTRE-FUNCTION (wave/raise branch)

player = context.player
end_of_rainbow = lookup("end_of_rainbow")
on_rainbow = lookup("on_rainbow")
pot_of_gold = lookup("pot_of_gold")
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if player.here() == lookup("aragain_falls") or player.here() == end_of_rainbow:
    if not player.zstate_get("RAINBOW-FLAG"):
        pot_of_gold.set_flag("invisible", False)
        print(
            "Suddenly, the rainbow appears to become solid and, I venture,\nwalkable (I think the giveaway was the stairs and bannister)."
        )
        if player.here() == end_of_rainbow and pot_of_gold.location == end_of_rainbow:
            print("A shimmering pot of gold appears at the end of the rainbow.")
        return player.zstate_set("RAINBOW-FLAG", True)
    else:
        # ZIL: <ROB ...>
        _.zork_thing.rob(on_rainbow, lookup("wall"))
        print("The rainbow seems to have become somewhat run-of-the-mill.")
        player.zstate_set("RAINBOW-FLAG", False)
        return True
elif player.here() == on_rainbow:
    player.zstate_set("RAINBOW-FLAG", False)
    return _.jigs_up(
        "The structural integrity of the rainbow is severely compromised,\nleaving you hanging in midair, supported only by water vapor. Bye."
    )
else:
    print("A dazzling display of color briefly emanates from the sceptre.")
    return
