#!moo verb idrop --on "Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context

# ZIL routine: IDROP

player = context.player
parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None

if prso is None:
    if context.parser is not None and context.parser.has_dobj_str():
        print("There is no '" + context.parser.dobj_str + "' here.")
    else:
        print("I don't know how to do that.")
    return

if (
    not (prso is not None and prso.location == player)
    and not (prso.location if prso is not None else None).location == player
):
    print("You're not carrying the " + (prso.desc() if prso else "") + ".")
    return False
elif not (prso is not None and prso.location == player) and not (prso.location if prso is not None else None).flag(
    "open"
):
    print("The " + (prso.desc() if prso else "") + " is closed.")
    return False
else:
    (prso.moveto(player.location) if prso else None)
    return True
