#!moo verb listen hear --on "lurking grue" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: GRUE-FUNCTION (listen branch)

the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

print("It makes no sound but is always lurking in the darkness nearby.")
return
