#!moo verb insert place plug put put-on --on "leak" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: LEAK-FUNCTION

player = context.player
parser = context.parser
putty = lookup("putty")
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if player.zstate_get("WATER-LEVEL") > 0:
    if (
        the_player_verb in ["put", "place", "insert", "put-on"]
        and (parser.get_dobj() if parser.has_dobj_str() else None) == putty
    ):
        # ZIL: <FIX-MAINT-LEAK ...>
        return _.zork_thing.fix_maint_leak()
    elif the_player_verb == "plug":
        if (parser.get_iobj() if parser.has_iobj() else None) == putty:
            # ZIL: <FIX-MAINT-LEAK ...>
            return _.zork_thing.fix_maint_leak()
        else:
            # ZIL: <WITH-TELL ...>
            return _.zork_thing.with_tell((parser.get_iobj() if parser.has_iobj() else None))
