#!moo verb insert place plug put --on "leak" --dspec any --ispec on:this in:this at:this with:this from:this under:this over:this before:this around:this through:this behind:this beside:this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, invoked_verb_name, lookup

# ZIL routine: LEAK-FUNCTION

player = context.player
parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
putty = lookup("putty")
the_player_verb = invoked_verb_name(verb_name)

if player.zstate_get("WATER-LEVEL") > 0:
    if the_player_verb in ["put", "place", "insert", "put"] and prso == putty:
        # ZIL: <FIX-MAINT-LEAK ...>
        return _.thing.fix_maint_leak()
    elif the_player_verb == "plug":
        if prsi == putty:
            # ZIL: <FIX-MAINT-LEAK ...>
            return _.thing.fix_maint_leak()
        else:
            # ZIL: <WITH-TELL ...>
            return _.thing.with_tell(prsi)
