#!moo verb pre_give --on "Thing" --dspec this

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context

# ZIL routine: PRE-GIVE

parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None

if prso is None:
    if context.parser is not None and context.parser.has_dobj_str():
        print("There is no '" + context.parser.dobj_str + "' here.")
    else:
        print("I don't know how to do that.")
    return True

if not _.thing.is_held(prso):
    print("That's easy for you to say since you don't even have the " + (prso.desc() if prso else "") + ".")
    return True
