#!moo verb pre_board --on "Thing" --dspec this

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, lookup

# ZIL routine: PRE-BOARD
# aux: AV

player = context.player
parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
av = 0

if prso is None:
    if context.parser is not None and context.parser.has_dobj_str():
        print("There is no '" + context.parser.dobj_str + "' here.")
    else:
        print("I don't know how to do that.")
    return True

av = player.location
if _.thing.null_f():
    return True
elif prso.flag("vehicle") if prso else None:
    if not (prso is not None and prso.location == player.here()):
        print("The " + (prso.desc() if prso else "") + " must be on the ground to be boarded.")
    elif av.flag("vehicle"):
        print("You are already in the " + av.desc() + "!")
    else:
        return False
elif prso in (lookup("water"), lookup("global_water")):
    _.perform("swim", prso, None)
    return True
else:
    print("You have a theory on how to board a " + (prso.desc() if prso else "") + ", perhaps?")
return False
