#!moo verb pre_mung --on "Thing" --dspec this

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context

# ZIL routine: PRE-MUNG

parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None

if prso is None:
    if context.parser is not None and context.parser.has_dobj_str():
        print("There is no '" + context.parser.dobj_str + "' here.")
    else:
        print("I don't know how to do that.")
    return True

if _.thing.null_f():
    return True
elif not prsi or not (prsi.flag("weapon") if prsi else None):
    print("Trying to destroy the " + (prso.desc() if prso else "") + " with ", end="")
    if not prsi:
        print("your bare hands", end="")
    else:
        print("a " + (prsi.desc() if prsi else ""), end="")
    print(" is futile.")
    return True
