#!moo verb pre_read --on "Thing" --dspec this

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context

# ZIL routine: PRE-READ

player = context.player
parser = context.parser
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None

if not player.zstate_get("LIT"):
    print("It is impossible to read in the dark.")
    return True
elif prsi and not (prsi.flag("transparent") if prsi else None):
    print("How does one look through a " + (prsi.desc() if prsi else "") + "?")
    return True
