#!moo verb pre_put --on "Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: PRE-PUT

if _.thing.null_f():
    return False
else:
    # ZIL: <PRE-GIVE ...>
    return _.thing.pre_give()
