#!moo verb look --on "Machine Room" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import invoked_verb_name, lookup

# ZIL: MACHINE-ROOM-FCN / M-LOOK

rarg = args[0] if len(args) > 0 else "M-LOOK"
the_player_verb = args[1] if len(args) > 1 else invoked_verb_name(verb_name)

print(this.desc())
print(
    'This is a large, cold room whose sole exit is to the north. In one\ncorner there is a machine which is reminiscent of a clothes\ndryer. On its face is a switch which is labelled "START".\nThe switch does not appear to be manipulable by any human hand (unless the\nfingers are about 1/16 by 1/4 inch). On the front of the machine is a large\nlid, which is ',
    end="",
)
if lookup("machine").flag("open"):
    print("open.", end="")
else:
    print("closed.", end="")
print()
_.zork_thing.describe_objects(True)
