#!moo verb # --on "Zork Actor" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

"""Player command for #: dispatch by object slot."""

from moo.sdk import context

# Compound verb dispatch: <verb> <particle> routes to a different V-routine.
# Two parser shapes: (a) particle was a registered prep — pull dobj from
# prepositions; (b) particle was bare — re-resolve from words[2:].
compound_table = {"#": {"random": "random", "command": "command_file", "record": "record", "unrecord": "unrecord"}}
cmd_words = context.parser.words if context.parser is not None else []
if len(cmd_words) > 1:
    cmd_verb = cmd_words[0].lower()
    cmd_particle = cmd_words[1].lower()
    particle_table = compound_table.get(cmd_verb)
    if particle_table and cmd_particle in particle_table:
        if context.parser.dobj is None:
            for prep_objects in context.parser.prepositions.values():
                for prep_record in prep_objects:
                    if prep_record[2] is not None:
                        context.parser.dobj = prep_record[2]
                        context.parser.dobj_str = prep_record[1]
                        break
                if context.parser.dobj is not None:
                    break
            if context.parser.dobj is None and len(cmd_words) > 2:
                target_str = " ".join(cmd_words[2:])
                resolved = context.player.find(target_str).first()
                if resolved is None and context.player.location is not None:
                    resolved = context.player.location.find(target_str).first()
                if resolved is not None:
                    context.parser.dobj = resolved
                    context.parser.dobj_str = target_str
        _.zork_thing.invoke_verb(particle_table[cmd_particle])
        return

if context.parser.has_dobj_str():
    _.zork_thing.random()
else:
    _.zork_thing.command_file()
