#!moo verb enter --on "Zork Actor" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

"""Player command for ENTER: dispatch by object slot."""

from moo.sdk import context

if context.parser.has_dobj_str():
    _.zork_thing.through()
else:
    _.zork_thing.enter()
