#!moo verb pour spill drop leave --on "Zork Actor" --dspec any

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

"""Player command for POUR: delegate to V-DROP."""

_.zork_thing.drop()
