#!moo verb enterfunc --on "Forest Path" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL: FOREST-ROOM / M-ENTER

parser = context.parser
rarg = args[0] if len(args) > 0 else "M-ENTER"
the_player_verb = (
    args[1]
    if len(args) > 1
    else (parser.words[0].lower() if context.parser is not None and parser.words else verb_name)
)

_.queue("i-forest-room", -1)
