#!moo verb burn light --on "pile of leaves" --dspec any --ispec on:this in:this at:this with:this from:this under:this over:this before:this around:this through:this behind:this beside:this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, invoked_verb_name

# ZIL routine: LEAF-PILE (burn branch)

player = context.player
parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
the_player_verb = invoked_verb_name(verb_name)

if this not in (prso, prsi):
    return passthrough()

# ZIL: <LEAVES-APPEAR ...>
_.thing.leaves_appear()
_.remove(prso)
if prso is not None and prso.location == player.here():
    print("The leaves burn.")
    return
else:
    return _.jigs_up("The leaves burn, and so do you.")
