#!moo verb count --on "pile of leaves" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import invoked_verb_name

# ZIL routine: LEAF-PILE (count branch)

the_player_verb = invoked_verb_name(verb_name)

print("There are 69,105 leaves here.")
return
