#!moo verb cut --on "pile of leaves" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import invoked_verb_name

# ZIL routine: LEAF-PILE (cut branch)

the_player_verb = invoked_verb_name(verb_name)

print("You rustle the leaves around, making quite a mess.")
# ZIL: <LEAVES-APPEAR ...>
_.zork_thing.leaves_appear()
return True
