#!moo verb cut --on "pile of leaves" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: LEAF-PILE (cut branch)

the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

print("You rustle the leaves around, making quite a mess.")
# ZIL: <LEAVES-APPEAR ...>
_.zork_thing.leaves_appear()
return True
