#!moo verb look-under --on "pile of leaves" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: LEAF-PILE (look-under branch)

player = context.player
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if not player.zstate_get("GRATE-REVEALED"):
    print(
        "Underneath the pile of leaves is a grating. As you release the leaves,\nthe grating is once again concealed from view."
    )
    return
return passthrough()
