#!moo verb move take get pick --on "pile of leaves" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name

# ZIL routine: LEAF-PILE (move/take branch)

player = context.player
the_player_verb = invoked_verb_name(verb_name)

if the_player_verb == "move":
    print("Done.")
if player.zstate_get("GRATE-REVEALED"):
    return passthrough()
# ZIL: <LEAVES-APPEAR ...>
_.thing.leaves_appear()
if the_player_verb in ["take", "get", "pick"]:
    return passthrough()
else:
    return True
