#!moo verb move take get pick --on "pile of leaves" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: LEAF-PILE (move/take branch)

player = context.player
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if the_player_verb == "move":
    print("Done.")
if player.zstate_get("GRATE-REVEALED"):
    return passthrough()
# ZIL: <LEAVES-APPEAR ...>
_.zork_thing.leaves_appear()
if the_player_verb in ["take", "get", "pick"]:
    return passthrough()
else:
    return True
