#!moo verb canary_object --on "broken clockwork canary" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, lookup

# ZIL: CANARY-OBJECT / combined OBJECT-FUNCTION dispatch
# Invoked by ``_.thing.dispatch_object_function(obj, verb, prep, iobj)``
# which looks up ``obj.action`` and calls ``obj.invoke_verb(action_atom, ...)``.

player = context.player
parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
the_verb = args[0] if len(args) > 0 else None
prep = args[1] if len(args) > 1 else None
iobj = args[2] if len(args) > 2 else None
the_player_verb = the_verb

if the_verb == "wind":
    if prso == lookup("canary"):
        if not player.zstate_get("SING-SONG") and _.thing.is_forest_room():
            print(
                "The canary chirps, slightly off-key, an aria from a forgotten opera.\nFrom out of the greenery flies a lovely songbird. It perches on a\nlimb just over your head and opens its beak to sing. As it does so\na beautiful brass bauble drops from its mouth, bounces off the top of\nyour head, and lands glimmering in the grass. As the canary winds\ndown, the songbird flies away."
            )
            player.zstate_set("SING-SONG", True)
            return lookup("bauble").moveto((lookup("path") if player.here() == lookup("up_a_tree") else player.here()))
        else:
            print("The canary chirps blithely, if somewhat tinnily, for a short time.")
            return
    else:
        print("There is an unpleasant grinding noise from inside the canary.")
        return
return False
