#!moo verb enterfunc --on "Loud Room" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name, lookup, task_time_low

# ZIL: LOUD-ROOM-FCN / M-ENTER

player = context.player
parser = context.parser
rarg = args[0] if len(args) > 0 else "M-ENTER"
wrd = 0
the_player_verb = args[1] if len(args) > 1 else invoked_verb_name(verb_name)

if player.zstate_get("LOUD-FLAG") or (not player.zstate_get("GATES-OPEN") and player.zstate_get("LOW-TIDE")):
    return False
elif player.zstate_get("GATES-OPEN") and not player.zstate_get("LOW-TIDE"):
    return False
else:
    # ZIL: <V-FIRST-LOOK ...>
    _.zork_thing.first_look()
    if player:
        print("The rest of your commands have been lost in the noise.")
        player.zstate_set("P-CONT", False)
    while True:
        if task_time_low():
            print("[zil] long-running loop in LOUD-ROOM-FCN; aborting (bug — please report).")
            return False
        if not player.zstate_get("SUPER-BRIEF"):
            print()
        print(">", end="")
        # ZIL: <READ ...>
        return True
        if (len(parser.words) if context.parser is not None else 0) == 0:
            print("I beg your pardon?")
            # ZIL: <AGAIN ...>
            lookup("again")
        wrd = parser.words[(1) - 1] if context.parser is not None and len(parser.words) >= (1) else ""
        if wrd in (player.zstate_get("W?GO"), player.zstate_get("W?WALK"), player.zstate_get("W?RUN")):
            wrd = parser.words[(3) - 1] if context.parser is not None and len(parser.words) >= (3) else ""
        elif wrd == player.zstate_get("W?SAY"):
            wrd = parser.words[(5) - 1] if context.parser is not None and len(parser.words) >= (5) else ""
        if wrd == player.zstate_get("W?SAVE"):
            # ZIL: <V-SAVE ...>
            player.save()
        elif wrd == player.zstate_get("W?RESTORE"):
            # ZIL: <V-RESTORE ...>
            player.restore()
        elif wrd in (player.zstate_get("W?Q"), player.zstate_get("W?QUIT")):
            # ZIL: <V-QUIT ...>
            player.quit()
        elif wrd in (player.zstate_get("W?W"), player.zstate_get("W?WEST")):
            return _.goto(lookup("round_room"))
        elif wrd in (player.zstate_get("W?E"), player.zstate_get("W?EAST")):
            return _.goto(lookup("damp_cave"))
        elif wrd in (player.zstate_get("W?U"), player.zstate_get("W?UP")):
            return _.goto(lookup("deep_canyon"))
        elif wrd == player.zstate_get("W?BUG"):
            print("That's only your opinion.")
        elif wrd == player.zstate_get("W?ECHO"):
            player.zstate_set("LOUD-FLAG", True)
            lookup("bar").set_flag("sacred", False)
            print("The acoustics of the room change subtly.")
            if not player.zstate_get("SUPER-BRIEF"):
                print()
            break
        else:
            # ZIL: <V-ECHO ...>
            player.echo()
