#!moo verb look --on "Loud Room" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name

# ZIL: LOUD-ROOM-FCN / M-LOOK

player = context.player
rarg = args[0] if len(args) > 0 else "M-LOOK"
wrd = 0
the_player_verb = args[1] if len(args) > 1 else invoked_verb_name(verb_name)

print(this.desc())
print(
    "This is a large room with a ceiling which cannot be detected from\nthe ground. There is a narrow passage from east to west and a stone\nstairway leading upward.",
    end="",
)
if player.zstate_get("LOUD-FLAG") or (not player.zstate_get("GATES-OPEN") and player.zstate_get("LOW-TIDE")):
    print(" The room is eerie in its quietness.", end="")
else:
    print(
        " The room is deafeningly loud with an\nundetermined rushing sound. The sound seems to reverberate from all\nof the walls, making it difficult even to think.",
        end="",
    )
print()
_.zork_thing.describe_objects(True)
