#!moo verb loud_room_fcn --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: LOUD-ROOM-FCN
# params: RARG
# aux: WRD

player = context.player
rarg = args[0] if len(args) > 0 else None
wrd = 0

if rarg == "M-END" and player.zstate_get("GATES-OPEN") and not player.zstate_get("LOW-TIDE"):
    print(
        "It is unbearably loud here, with an ear-splitting roar seeming to\ncome from all around you. There is a pounding in your head which won't\nstop. With a tremendous effort, you scramble out of the room."
    )
    _.goto(_.pick(player.zstate_get("LOUD-RUNS")))
    return False
return passthrough()
