#!moo verb deep_canyon_f look --on "Deep Canyon" --dspec either

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name

# ZIL: DEEP-CANYON-F / combined M-/F-clause dispatch

player = context.player
verb_to_const = {"look": "M-LOOK"}
rarg = args[0] if len(args) > 0 else verb_to_const.get(verb_name, "M-LOOK")
the_player_verb = args[1] if len(args) > 1 else invoked_verb_name(verb_name)

if rarg == "M-LOOK":
    print(this.desc())
    print(
        "You are on the south edge of a deep canyon. Passages lead off to the\neast, northwest and southwest. A stairway leads down.",
        end="",
    )
    if player.zstate_get("GATES-OPEN") and not player.zstate_get("LOW-TIDE"):
        print(" You can hear a loud roaring sound, like that of rushing water, from\nbelow.", end="")
    elif not player.zstate_get("GATES-OPEN") and player.zstate_get("LOW-TIDE"):
        print()
        return True
    else:
        print(" You can hear the sound of flowing water from below.", end="")
    print()
    _.thing.describe_objects(True)
