#!moo verb grate_function --on "grating" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, lookup

# ZIL: GRATE-FUNCTION / combined OBJECT-FUNCTION dispatch
# Invoked by ``_.thing.dispatch_object_function(obj, verb, prep, iobj)``
# which looks up ``obj.action`` and calls ``obj.invoke_verb(action_atom, ...)``.

player = context.player
parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
clearing = lookup("clearing")
grating_clearing = lookup("grating_clearing")
grating_room = lookup("grating_room")
keys = lookup("keys")
the_verb = args[0] if len(args) > 0 else None
prep = args[1] if len(args) > 1 else None
iobj = args[2] if len(args) > 2 else None
the_player_verb = the_verb

if the_verb == "open":
    if prsi == keys:
        _.perform("unlock", this, keys)
        return True
elif the_verb == "lock":
    if player.here() == grating_room:
        player.zstate_set("GRUNLOCK", False)
        print("The grate is locked.")
        return
    elif player.here() == grating_clearing:
        print("You can't lock it from this side.")
        return
elif the_verb == "unlock":
    if prso == this:
        if player.here() == grating_room and prsi == keys:
            player.zstate_set("GRUNLOCK", True)
            print("The grate is unlocked.")
            return
        elif player.here() == grating_clearing and prsi == keys:
            print("You can't reach the lock from here.")
            return
        else:
            print("Can you unlock a grating with a " + (prsi.desc() if prsi else "") + "?")
            return
elif the_verb == "pick":
    print("You can't pick the lock.")
    return
elif the_verb == "open" or the_verb == "close":
    if player.zstate_get("GRUNLOCK"):
        # ZIL: <OPEN-CLOSE ...>
        _.thing.open_close(
            this,
            ("The grating opens." if player.here() == clearing else "The grating opens to reveal trees above you."),
            "The grating is closed.",
        )
        if this.flag("open"):
            if not player.here() == clearing and not player.zstate_get("GRATE-REVEALED"):
                print("A pile of leaves falls onto your head and to the ground.")
                player.zstate_set("GRATE-REVEALED", True)
                lookup("leaves").moveto(player.here())
            return grating_room.set_flag("onbit", True)
        else:
            return grating_room.set_flag("onbit", False)
    else:
        print("The grating is locked.")
        return
elif the_verb == "put":
    if prsi == this:
        if (prso.getp("size") if prso else None) > 20:
            print("It won't fit through the grating.")
            return
        else:
            prso.moveto(grating_room)
            print("The " + (prso.desc() if prso else "") + " goes through the grating into the darkness below.")
            return
return False
