#!moo verb lock --on "grating" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: GRATE-FUNCTION (lock branch)

player = context.player
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if player.here() == lookup("grating_room"):
    player.zstate_set("GRUNLOCK", False)
    print("The grate is locked.")
    return
elif player.here() == lookup("grating_clearing"):
    print("You can't lock it from this side.")
    return
return passthrough()
