#!moo verb open close shut --on "grating" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: GRATE-FUNCTION (open/close branch)

player = context.player
clearing = lookup("clearing")
grating_room = lookup("grating_room")
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if player.zstate_get("GRUNLOCK"):
    # ZIL: <OPEN-CLOSE ...>
    _.zork_thing.open_close(
        this,
        ("The grating opens." if player.here() == clearing else "The grating opens to reveal trees above you."),
        "The grating is closed.",
    )
    if this.flag("open"):
        if not player.here() == clearing and not player.zstate_get("GRATE-REVEALED"):
            print("A pile of leaves falls onto your head and to the ground.")
            player.zstate_set("GRATE-REVEALED", True)
            lookup("leaves").moveto(player.here())
        return grating_room.set_flag("onbit", True)
    else:
        return grating_room.set_flag("onbit", False)
else:
    print("The grating is locked.")
    return
