#!moo verb put place insert --on "grating" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, invoked_verb_name, lookup

# ZIL routine: GRATE-FUNCTION (put branch)

parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
the_player_verb = invoked_verb_name(verb_name)

if prsi == this:
    if (prso.getp("size") if prso else None) > 20:
        print("It won't fit through the grating.")
        return
    else:
        prso.moveto(lookup("grating_room"))
        print("The " + (prso.desc() if prso else "") + " goes through the grating into the darkness below.")
        return
return passthrough()
