#!moo verb unlock --on "grating" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, invoked_verb_name, lookup

# ZIL routine: GRATE-FUNCTION (unlock branch)

player = context.player
parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
keys = lookup("keys")
the_player_verb = invoked_verb_name(verb_name)

if prso == this:
    if player.here() == lookup("grating_room") and prsi == keys:
        player.zstate_set("GRUNLOCK", True)
        print("The grate is unlocked.")
        return
    elif player.here() == lookup("grating_clearing") and prsi == keys:
        print("You can't reach the lock from here.")
        return
    else:
        print("Can you unlock a grating with a " + (prsi.desc() if prsi else "") + "?")
        return
return passthrough()
