#!moo verb unlock --on "grating" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: GRATE-FUNCTION (unlock branch)

player = context.player
parser = context.parser
keys = lookup("keys")
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if (parser.get_dobj() if parser.has_dobj_str() else None) == this:
    if player.here() == lookup("grating_room") and (parser.get_iobj() if parser.has_iobj() else None) == keys:
        player.zstate_set("GRUNLOCK", True)
        print("The grate is unlocked.")
        return
    elif player.here() == lookup("grating_clearing") and (parser.get_iobj() if parser.has_iobj() else None) == keys:
        print("You can't reach the lock from here.")
        return
    else:
        print("Can you unlock a grating with a " + (parser.get_iobj().desc() if parser.has_iobj() else "") + "?")
        return
return passthrough()
