#!moo verb forest_f --on "forest (FOREST)" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL: FOREST-F / combined OBJECT-FUNCTION dispatch
# Invoked by ``_.thing.dispatch_object_function(obj, verb, prep, iobj)``
# which looks up ``obj.action`` and calls ``obj.invoke_verb(action_atom, ...)``.

player = context.player
the_verb = args[0] if len(args) > 0 else None
prep = args[1] if len(args) > 1 else None
iobj = args[2] if len(args) > 2 else None
the_player_verb = the_verb

if the_verb == "walk_around":
    if player.here() in (
        lookup("west_of_house"),
        lookup("north_of_house"),
        lookup("south_of_house"),
    ) or player.here() == lookup("east_of_house"):
        print("You aren't even in the forest.")
    # ZIL: <GO-NEXT ...>
    return _.thing.go_next(player.zstate_get("FOREST-AROUND"))
elif the_verb == "disembark":
    print("You will have to specify a direction.")
    return
elif the_verb == "find":
    print("You cannot see the forest for the trees.")
    return
elif the_verb == "listen":
    print("The pines and the hemlocks seem to be murmuring.")
    return
return False
