#!moo verb turn rotate --on "bolt" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, lookup

# ZIL routine: BOLT-F (turn branch)

player = context.player
parser = context.parser
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if prsi == lookup("wrench"):
    if player.zstate_get("GATE-FLAG"):
        lookup("reservoir_south").set_flag("touchbit", False)
        if player.zstate_get("GATES-OPEN"):
            player.zstate_set("GATES-OPEN", False)
            lookup("loud_room").set_flag("touchbit", False)
            print("The sluice gates close and water starts to collect behind the dam.")
            _.queue("i-rfill", 8)
            return _.queue("i-rempty", 0)
        else:
            player.zstate_set("GATES-OPEN", True)
            print("The sluice gates open and water pours through the dam.")
            _.queue("i-rempty", 8)
            return _.queue("i-rfill", 0)
    else:
        print("The bolt won't turn with your best effort.")
        return
elif not prsi in (False, lookup("hands"), player.zstate_get("ROOMS")):
    print("The bolt won't turn using the " + (prsi.desc() if prsi else "") + ".")
    return
return passthrough()
