#!moo verb advent plugh xyzzy --on "Actor" --dspec none

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: V-ADVENT

print('A hollow voice says "Fool."')
return
