#!moo verb inventory i --on "Actor" --dspec none

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: V-INVENTORY

player = context.player

if player.contents.first():
    # ZIL: <PRINT-CONT ...>
    return _.thing.print_cont(player)
else:
    print("You are empty-handed.")
    return
