#!moo verb odysseus ulysses --on "Actor" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: V-ODYSSEUS

player = context.player
cyclops = lookup("cyclops")

if (
    player.here() == lookup("cyclops_room")
    and cyclops.location == player.here()
    and not player.zstate_get("CYCLOPS-FLAG")
):
    _.cancel("i-cyclops")
    player.zstate_set("CYCLOPS-FLAG", True)
    print(
        "The cyclops, hearing the name of his father's deadly nemesis, flees the room\nby knocking down the wall on the east of the room."
    )
    player.zstate_set("MAGIC-FLAG", True)
    cyclops.set_flag("hostile", False)
    return _.remove(cyclops)
else:
    print("Wasn't he a sailor?")
    return
