#!moo verb pray --on "Actor" --dspec none

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: V-PRAY

player = context.player

if player.here() == lookup("south_temple"):
    return _.goto(lookup("forest_1"))
else:
    print("If you pray enough, your prayers may be answered.")
    return
