#!moo verb restart --on "Actor" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: V-RESTART

player = context.player

# ZIL: <V-SCORE ...>
player.score(True)
print("Do you wish to restart? (Y is affirmative): ", end="")
if player.is_yes():
    print("Restarting.")
    print("Restart not supported in DjangoMOO.")
    print("Failed.")
    return
