#!moo verb stay --on "Actor" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: V-STAY

print("You will be lost without me!")
return
