#!moo verb unscript --on "Actor" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: V-UNSCRIPT

player = context.player

print("Here ends a transcript of interaction with")
# ZIL: <V-VERSION ...>
player.version()
# ZIL: <PUT ...>
_.table_put(0, 8, (((_.table_get(_.get_property("zstate_version_table"), 8)) or 0) & ((-2) or 0)))
return True
