#!moo verb wish --on "Actor" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: V-WISH

print("With luck, your wish will come true.")
return
