#!moo verb examine x describe what --on "pedestal" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context

# ZIL routine: DUMB-CONTAINER (examine branch)

parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

print("It looks pretty much like a " + (prso.desc() if prso else "") + ".")
return
