#!moo verb burn light --on "wooden door" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import invoked_verb_name

# ZIL routine: FRONT-DOOR-FCN (burn branch)

the_player_verb = invoked_verb_name(verb_name)

print("You cannot burn this door.")
return
