#!moo verb read --on "wooden door" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name, lookup

# ZIL routine: FRONT-DOOR-FCN (read branch)

player = context.player
the_player_verb = invoked_verb_name(verb_name)

if player.here() == lookup("living_room"):
    print('The engravings translate to "This space intentionally left blank."', end="")
elif print("There is no writing on this side.", end=""):
    pass
print()
return
