#!moo verb forest_room enterfunc preturnfunc --on "Forest (FOREST-2)" --dspec either

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, invoked_verb_name, lookup

# ZIL: FOREST-ROOM / combined M-/F-clause dispatch

player = context.player
parser = context.parser
prso = None
if context.parser is not None:
    try:
        prso = parser.get_dobj() if parser.has_dobj_str() else None
    except NoSuchObjectError:
        prso = None
verb_to_const = {"enterfunc": "M-ENTER", "preturnfunc": "M-BEG"}
rarg = args[0] if len(args) > 0 else verb_to_const.get(verb_name, "M-ENTER")
the_player_verb = args[1] if len(args) > 1 else invoked_verb_name(verb_name)

if rarg == "M-ENTER":
    _.schedule_realtime("i_forest_room", -1)
elif rarg == "M-BEG":
    if the_player_verb in ["climb_foo", "climb_up"] and prso == lookup("tree"):
        _.walk(player.zstate_get("P?UP"))
        return True
