#!moo verb pour-on --on "red hot brass bell" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context

# ZIL routine: HOT-BELL-F (pour-on branch)

parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

_.remove(prso)
print("The water cools the bell and is evaporated.")
_.queue("i-xbh", 0)
# ZIL: <I-XBH ...>
return _.zork_thing.i_xbh()
