#!moo verb take get pick --on "red hot brass bell" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import invoked_verb_name

# ZIL routine: HOT-BELL-F (take branch)

the_player_verb = invoked_verb_name(verb_name)

print("The bell is very hot and cannot be taken.")
return
