#!moo verb look_under --on "rainbow" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import invoked_verb_name

# ZIL routine: RAINBOW-FCN (look-under branch)

the_player_verb = invoked_verb_name(verb_name)

print("The Frigid River flows under the rainbow.")
return
