#!moo verb rainbow_fcn --on "rainbow" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL: RAINBOW-FCN / combined OBJECT-FUNCTION dispatch
# Invoked by ``_.thing.dispatch_object_function(obj, verb, prep, iobj)``
# which looks up ``obj.action`` and calls ``obj.invoke_verb(action_atom, ...)``.

player = context.player
aragain_falls = lookup("aragain_falls")
end_of_rainbow = lookup("end_of_rainbow")
the_verb = args[0] if len(args) > 0 else None
prep = args[1] if len(args) > 1 else None
iobj = args[2] if len(args) > 2 else None
the_player_verb = the_verb

if the_verb == "cross" or the_verb == "through":
    if player.here() == lookup("canyon_view"):
        print("From here?!?")
        return True
    if player.zstate_get("RAINBOW-FLAG"):
        if player.here() == aragain_falls:
            return _.goto(end_of_rainbow)
        elif player.here() == end_of_rainbow:
            return _.goto(aragain_falls)
        else:
            print("You'll have to say which way...")
            return
    else:
        print("Can you walk on water vapor?")
        return
elif the_verb == "look_under":
    print("The Frigid River flows under the rainbow.")
    return
return False
