#!moo verb look --on "Kitchen" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import invoked_verb_name, lookup

# ZIL: KITCHEN-FCN / M-LOOK

rarg = args[0] if len(args) > 0 else "M-LOOK"
the_player_verb = args[1] if len(args) > 1 else invoked_verb_name(verb_name)

print(this.desc())
print(
    "You are in the kitchen of the white house. A table seems to\nhave been used recently for the preparation of food. A passage\nleads to the west and a dark staircase can be seen leading\nupward. A dark chimney leads down and to the east is a small\nwindow which is ",
    end="",
)
if lookup("kitchen_window").flag("open"):
    print("open.")
else:
    print("slightly ajar.")
_.zork_thing.describe_objects(True)
