#!moo verb thief_in_treasure --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup, task_time_low

# ZIL routine: THIEF-IN-TREASURE
# aux: F

player = context.player
f = 0

f = player.here().contents.first()
if f and _.next_sibling(f):
    print("The thief gestures mysteriously, and the treasures in the room\nsuddenly vanish.")
while True:
    if task_time_low():
        print("[zil] long-running loop in THIEF-IN-TREASURE; aborting (bug — please report).")
        return False
    if not f:
        break
    elif not f in (lookup("chalice"), lookup("thief")):
        f.set_flag("invisible", True)
    f = _.next_sibling(f)
