#!moo verb v_answer --on "Thing" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: V-ANSWER

player = context.player

print("Nobody seems to be awaiting your answer.")
player.zstate_set("P-CONT", False)
player.zstate_set("QUOTE-FLAG", False)
return True
