#!moo verb v_blast --on "Thing" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: V-BLAST

print("You can't blast anything by using words.")
return
