#!moo verb v_brush --on "Thing" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: V-BRUSH

print("If you wish, but heaven only knows why.")
return
