#!moo verb v_command_file --on "Thing" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: V-COMMAND-FILE

# ZIL: <DIRIN ...>
dirin(1)
return True
