#!moo verb v_drink --on "Thing" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: V-DRINK

# ZIL: <V-EAT ...>
return _.thing.eat()
