#!moo verb v_eat drink --on "Thing" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, invoked_verb_name, lookup

# ZIL routine: V-EAT
# aux: EAT?, DRINK?, NOBJ

player = context.player
parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
eat_p = 0
drink_p = 0
nobj = 0
the_player_verb = invoked_verb_name(verb_name)

if prso is None:
    if context.parser is not None and context.parser.has_dobj_str():
        print("There is no '" + context.parser.dobj_str + "' here.")
    else:
        print("What do you want to eat?")
    return

if eat_p := (prso.flag("edible") if prso else None):
    if (
        not (prso is not None and prso.location == player)
        and not (prso.location if prso is not None else None).location == player
    ):
        print("You're not holding that.")
    elif the_player_verb == "drink":
        print("How can you drink that?", end="")
    else:
        print("Thank you very much. It really hit the spot.", end="")
        _.remove(prso)
    print()
    return
elif prso.flag("drinkable") if prso else None:
    drink_p = True
    nobj = prso.location if prso is not None else None
    if (
        (prso is not None and prso.location == lookup("global_objects"))
        or lookup("global_water").global_in(player.here())
        or prso == lookup("pseudo_object")
    ):
        # ZIL: <HIT-SPOT ...>
        return _.thing.hit_spot()
    elif not nobj or not _.thing.is_accessible(nobj):
        print("There isn't any water here.")
        return
    elif _.thing.is_accessible(nobj) and not nobj.location == player:
        print("You have to be holding the " + nobj.desc() + " first.")
        return
    elif not nobj.flag("open"):
        print("You'll have to open the " + nobj.desc() + " first.")
        return
    else:
        # ZIL: <HIT-SPOT ...>
        return _.thing.hit_spot()
elif not (eat_p or drink_p):
    print("I don't think that the " + (prso.desc() if prso else "") + " would agree with you.")
    return
