#!moo verb v_enchant --on "Thing" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: V-ENCHANT

# ZIL: <NULL-F ...>
_.thing.null_f()
# ZIL: <V-DISENCHANT ...>
return _.thing.disenchant()
