#!moo verb v_examine --on "Thing" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context

# ZIL routine: V-EXAMINE

parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None

if prso is None:
    if context.parser is not None and context.parser.has_dobj_str():
        print("There is no '" + context.parser.dobj_str + "' here.")
    else:
        print("What do you want to examine?")
    return

if prso.getp("text") if prso else None:
    print((prso.getp("text") if prso else None))
    return
elif (prso.flag("contbit") if prso else None) or (prso.flag("is_door") if prso else None):
    # ZIL: <V-LOOK-INSIDE ...>
    return _.thing.look_inside()
else:
    print("There's nothing special about the " + (prso.desc() if prso else "") + ".")
    return
