#!moo verb v_inflate --on "Thing" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: V-INFLATE

print("How can you inflate that?")
return
