#!moo verb v_put --on "Thing" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context

# ZIL routine: V-PUT

parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None

if prso is None:
    if context.parser is not None and context.parser.has_dobj_str():
        print("There is no '" + context.parser.dobj_str + "' here.")
    else:
        print("What do you want to put?")
    return

pre_x = "pre_put"
if _.thing.invoke_verb(pre_x):
    return
if (
    (prsi.flag("open") if prsi else None)
    or (prsi.flag("openable") if prsi else None)
    or (prsi.flag("vehicle") if prsi else None)
):
    pass
else:
    print("You can't do that.")
    return True
if not (prsi.flag("open") if prsi else None):
    print("The " + (prsi.desc() if prsi else "") + " isn't open.")
    # ZIL: <THIS-IS-IT ...>
    return _.thing.this_is_it(prsi)
elif prsi == prso:
    print("How can you do that?")
    return
elif prso is not None and prso.location == prsi:
    print("The " + (prso.desc() if prso else "") + " is already in the " + (prsi.desc() if prsi else "") + ".")
    return
elif ((_.thing.weight(prsi) + _.thing.weight(prso)) - (prsi.getp("size") if prsi else None)) > (
    prsi.getp("capacity") if prsi else None
):
    print("There's no room.")
    return
elif not _.thing.is_held(prso) and (prso.flag("trytakebit") if prso else None):
    print("You don't have the " + (prso.desc() if prso else "") + ".")
    return True
elif not _.thing.is_held(prso) and not _.thing.itake():
    return True
else:
    (prso.moveto(prsi) if prso else None)
    (prso.set_flag("touchbit", True) if prso else None)
    # ZIL: <SCORE-OBJ ...>
    _.thing.score_obj(prso)
    print("Done.")
    return
