#!moo verb v_push --on "Thing" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: V-PUSH

# ZIL: <HACK-HACK ...>
return _.thing.hack_hack("Pushing the ")
