#!moo verb v_random --on "Thing" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

import random
from moo.sdk import NoSuchObjectError, context, lookup

# ZIL routine: V-RANDOM

player = context.player
parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None

if prso is None:
    if context.parser is not None and context.parser.has_dobj_str():
        print("There is no '" + context.parser.dobj_str + "' here.")
    else:
        print("What do you want to random?")
    return

if not prso == lookup("intnum"):
    print("Illegal call to #RND.")
    return
else:
    random.randint(1, (0 - player.zstate_get("P-NUMBER")))
    return True
