#!moo verb v_script --on "Thing" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: V-SCRIPT

player = context.player

# ZIL: <PUT ...>
_.table_put(0, 8, (((_.table_get(_.get_property("zstate_version_table"), 8)) or 0) | ((1) or 0)))
print("Here begins a transcript of interaction with")
# ZIL: <V-VERSION ...>
player.version()
return True
