#!moo verb v_spray --on "Thing" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: V-SPRAY

# ZIL: <V-SQUEEZE ...>
return _.thing.squeeze()
