#!moo verb v_throw --on "Thing" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, lookup

# ZIL routine: V-THROW

player = context.player
parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None

if prso is None:
    if context.parser is not None and context.parser.has_dobj_str():
        print("There is no '" + context.parser.dobj_str + "' here.")
    else:
        print("What do you want to throw?")
    return

if _.thing.idrop():
    if prsi == lookup("me"):
        print("A terrific throw! The " + (prso.desc() if prso else ""), end="")
        player.zstate_set("WINNER", player)
        return _.jigs_up(
            " hits you squarely in the head. Normally,\nthis wouldn't do much damage, but by incredible mischance, you fall over\nbackwards trying to duck, and break your neck, justice being swift and\nmerciful in the Great Underground Empire."
        )
    elif prsi and (prsi.flag("actorbit") if prsi else None):
        print(
            "The "
            + (prsi.desc() if prsi else "")
            + " ducks as the "
            + (prso.desc() if prso else "")
            + " flies by and crashes to the ground."
        )
        return
    else:
        print("Thrown.")
        return
else:
    print("Huh?")
    return
