#!moo verb v_tie_up --on "Thing" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: V-TIE-UP

print("You could certainly never tie it with that!")
return
