#!moo verb v_unrecord --on "Thing" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: V-UNRECORD

# ZIL: <DIROUT ...>
dirout(-4)
return True
