#!moo verb v_unlock --on "Thing" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: V-UNLOCK

# ZIL: <V-LOCK ...>
return _.thing.lock()
