#!moo verb v_untie --on "Thing" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: V-UNTIE

print("This cannot be tied, so it cannot be untied!")
return
