#!moo verb attack kill hit fight stab cut slice mung destroy break smash crack --on "number of ghosts" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: GHOSTS-F (attack/mung branch)

parser = context.parser
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if (parser.get_dobj() if parser.has_dobj_str() else None) == this:
    print("How can you attack a spirit with material objects?")
    return
return passthrough()
