#!moo verb exorcise --on "number of ghosts" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import invoked_verb_name

# ZIL routine: GHOSTS-F (exorcise branch)

the_player_verb = invoked_verb_name(verb_name)

print("Only the ceremony itself has any effect.")
return
