#!moo verb ghosts_f --on "number of ghosts" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context

# ZIL: GHOSTS-F / combined OBJECT-FUNCTION dispatch
# Invoked by ``_.thing.dispatch_object_function(obj, verb, prep, iobj)``
# which looks up ``obj.action`` and calls ``obj.invoke_verb(action_atom, ...)``.

player = context.player
parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
the_verb = args[0] if len(args) > 0 else None
prep = args[1] if len(args) > 1 else None
iobj = args[2] if len(args) > 2 else None
the_player_verb = the_verb

if the_verb == "tell":
    print("The spirits jeer loudly and ignore you.")
    return player.zstate_set("P-CONT", False)
elif the_verb == "exorcise":
    print("Only the ceremony itself has any effect.")
    return
elif the_verb == "attack" or the_verb == "mung":
    if prso == this:
        print("How can you attack a spirit with material objects?")
        return
return False
