#!moo verb tell --on "number of ghosts" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: GHOSTS-F (tell branch)

player = context.player
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

print("The spirits jeer loudly and ignore you.")
return player.zstate_set("P-CONT", False)
