#!moo verb tell --on "number of ghosts" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name

# ZIL routine: GHOSTS-F (tell branch)

player = context.player
the_player_verb = invoked_verb_name(verb_name)

print("The spirits jeer loudly and ignore you.")
return player.zstate_set("P-CONT", False)
