#!moo verb reservoir_north_fcn look --on "Reservoir North" --dspec either

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name

# ZIL: RESERVOIR-NORTH-FCN / combined M-/F-clause dispatch

player = context.player
verb_to_const = {"look": "M-LOOK"}
rarg = args[0] if len(args) > 0 else verb_to_const.get(verb_name, "M-LOOK")
the_player_verb = args[1] if len(args) > 1 else invoked_verb_name(verb_name)

if rarg == "M-LOOK":
    print(this.desc())
    if player.zstate_get("LOW-TIDE") and player.zstate_get("GATES-OPEN"):
        print(
            "You are in a large cavernous room, the south of which was formerly\na lake. However, with the water level lowered, there is merely\na wide stream running through there.",
            end="",
        )
    elif player.zstate_get("GATES-OPEN"):
        print(
            "You are in a large cavernous area. To the south is a wide lake,\nwhose water level appears to be falling rapidly.",
            end="",
        )
    elif player.zstate_get("LOW-TIDE"):
        print(
            "You are in a cavernous area, to the south of which is a very wide\nstream. The level of the stream is rising rapidly, and it appears\nthat before long it will be impossible to cross to the other side.",
            end="",
        )
    else:
        print("You are in a large cavernous room, north of a large lake.", end="")
    print()
    print("There is a slimy stairway leaving the room to the north.")
    _.thing.describe_objects(True)
