#!moo verb enterfunc --on "Clearing (GRATING-CLEARING)" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL: CLEARING-FCN / M-ENTER

player = context.player
parser = context.parser
rarg = args[0] if len(args) > 0 else "M-ENTER"
the_player_verb = (
    args[1]
    if len(args) > 1
    else (parser.words[0].lower() if context.parser is not None and parser.words else verb_name)
)

if not player.zstate_get("GRATE-REVEALED"):
    lookup("grate").set_flag("invisible", True)
