#!moo verb weapon_function --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: WEAPON-FUNCTION
# params: W, V

player = context.player
w = args[0] if len(args) > 0 else None
v = args[1] if len(args) > 1 else None
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if not v.location == player.here():
    return False
elif the_player_verb in ["take", "get", "pick"]:
    if w.location == v:
        print("The " + v.desc() + " swings it out of your reach.")
        return
    else:
        print("The " + w.desc() + " seems white-hot. You can't hold on to it.")
        return
