#!moo verb awaken --on "Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: AWAKEN
# params: O
# aux: S

o = args[0] if len(args) > 0 else None
s = o.getp("strength")

if s < 0:
    o.set_property("strength", (0 - s))
    # ZIL: <APPLY ...>
    if o is not None and o.has_verb("f_conscious", recurse=False):
        o.invoke_verb("f_conscious")
return True
