#!moo verb bad_egg --on "Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import lookup

# ZIL routine: BAD-EGG

broken_canary = lookup("broken_canary")
egg = lookup("egg")

if lookup("canary").location == egg:
    print(" " + broken_canary.getp("first_description"), end="")
else:
    _.remove(broken_canary)
lookup("broken_egg").moveto(egg.location)
_.remove(egg)
return True
