#!moo verb bat_d --on "Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: BAT-D

player = context.player

if lookup("garlic").location in (player, player.here()):
    print(
        "In the corner of the room on the ceiling is a large vampire bat who\nis obviously deranged and holding his nose."
    )
    return
else:
    print("A large vampire bat, hanging from the ceiling, swoops down at you!")
    return
