#!moo verb ccount --on "Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import task_time_low

# ZIL routine: CCOUNT
# params: OBJ
# aux: CNT, X

obj = args[0] if len(args) > 0 else None
cnt = 0
x = 0

if x := obj.contents.first():
    while True:
        if task_time_low():
            print("[zil] long-running loop in CCOUNT; aborting (bug — please report).")
            return False
        if not x.flag("wearbit"):
            cnt = cnt + 1
        if not (x := _.next_sibling(x)):
            break
return cnt
