#!moo verb drop_junk --on "Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

import random
from moo.sdk import context, lookup, task_time_low

# ZIL routine: DROP-JUNK
# params: RM
# aux: X, N, FLG

player = context.player
rm = args[0] if len(args) > 0 else None
x = 0
n = 0
flg = 0

x = lookup("thief").contents.first()
while True:
    if task_time_low():
        print("[zil] long-running loop in DROP-JUNK; aborting (bug — please report).")
        return False
    if not x:
        return flg
    n = _.next_sibling(x)
    if x in (lookup("stiletto"), lookup("large_bag")):
        pass
    elif x.getp("tvalue") == 0 and random.randint(1, 100) <= 30:
        x.set_flag("invisible", False)
        x.moveto(rm)
        if not flg and rm == player.here():
            print("The robber, rummaging through his bag, dropped a few items he found\nvalueless.")
            flg = True
    x = n
