#!moo verb goto --on "Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

import random
from moo.sdk import context, lookup

# ZIL routine: GOTO
# params: RM, V?
# aux: LB, WLOC, AV, OLIT, OHERE

player = context.player
rm = args[0] if len(args) > 0 else None
v_p = args[1] if len(args) > 1 else True
lb = rm.flag("outdoor")
wloc = player.location
av = 0
olit = 0
ohere = 0

olit = player.zstate_get("LIT")
ohere = player.here()
if wloc.flag("vehicle"):
    av = wloc.getp("vtype")
if not lb and not av:
    # ZIL: <NO-GO-TELL ...>
    _.thing.no_go_tell(av, wloc)
    return False
elif not lb and not rm.flag(av):
    # ZIL: <NO-GO-TELL ...>
    _.thing.no_go_tell(av, wloc)
    return False
elif player.here().flag("outdoor") and lb and av and not av == "outdoor" and not rm.flag(av):
    # ZIL: <NO-GO-TELL ...>
    _.thing.no_go_tell(av, wloc)
    return False
elif rm.flag("rmungbit"):
    print(rm.getp("description"))
    return False
else:
    if lb and not player.here().flag("outdoor") and not player.zstate_get("DEAD") and wloc.flag("vehicle"):
        print("The " + wloc.desc() + " comes to a rest on the shore.")
    if av:
        wloc.moveto(rm)
    else:
        player.moveto(rm)
    player.zstate_set("HERE", rm)
    player.zstate_set("LIT", _.thing.is_lit(player.here()))
    if not olit and not player.zstate_get("LIT") and random.randint(1, 100) <= 80:
        if player.zstate_get("SPRAYED?"):
            print("There are sinister gurgling noises in the darkness all around you!")
        elif _.thing.null_f():
            return False
        else:
            print("Oh, no! A lurking grue slithered into the ", end="")
            if player.location.flag("vehicle"):
                print(player.location.desc(), end="")
            else:
                print("room", end="")
            _.jigs_up(" and devoured you!")
            return True
    if not player.zstate_get("LIT") and player == player:
        print("You have moved into a dark place.")
        player.zstate_set("P-CONT", False)
    # ZIL: <APPLY ...>
    if player.here() is not None and player.here().has_verb("enterfunc", recurse=False):
        player.here().invoke_verb("enterfunc")
    # ZIL: <SCORE-OBJ ...>
    _.thing.score_obj(rm)
    if player.here() != rm:
        return True
    elif player != player and player.location == ohere:
        print("The " + player.desc() + " leaves the room.")
    elif player.here() == ohere and player.here() == lookup("entrance_to_hades"):
        return True
    elif v_p and player == player:
        # ZIL: <V-FIRST-LOOK ...>
        _.thing.first_look()
    return True
