#!moo verb int --on "Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, task_time_low

# ZIL routine: INT
# params: RTN, DEMON, E, C, INT

player = context.player
rtn = args[0] if len(args) > 0 else None
demon = args[1] if len(args) > 1 else None
e = args[2] if len(args) > 2 else None
c = args[3] if len(args) > 3 else None
int_v = args[4] if len(args) > 4 else None

player.zstate_get("#DECL")
e = _.rest(player.zstate_get("C-TABLE"), player.zstate_get("C-TABLELEN"))
c = _.rest(player.zstate_get("C-TABLE"), player.zstate_get("C-INTS"))
while True:
    if task_time_low():
        print("[zil] long-running loop in INT; aborting (bug — please report).")
        return False
    if c == e:
        player.zstate_set("C-INTS", (player.zstate_get("C-INTS") - player.zstate_get("C-INTLEN")))
        if demon:
            player.zstate_set("C-DEMONS", (player.zstate_get("C-DEMONS") - player.zstate_get("C-INTLEN")))
        int_v = _.rest(player.zstate_get("C-TABLE"), player.zstate_get("C-INTS"))
        # ZIL: <PUT ...>
        _.table_put(int_v, player.zstate_get("C-RTN"), rtn)
        return int_v
    elif _.table_get(c, player.zstate_get("C-RTN")) == rtn:
        return c
    c = _.rest(c, player.zstate_get("C-INTLEN"))
