#!moo verb leaves_appear --on "Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name, lookup

# ZIL routine: LEAVES-APPEAR

player = context.player
grate = lookup("grate")
the_player_verb = invoked_verb_name(verb_name)

if not grate.flag("open") and not player.zstate_get("GRATE-REVEALED"):
    if the_player_verb in ["move", "take", "get", "pick"]:
        print("In disturbing the pile of leaves, a grating is revealed.")
    else:
        print("With the leaves moved, a grating is revealed.")
    grate.set_flag("invisible", False)
    return player.zstate_set("GRATE-REVEALED", True)
