#!moo verb lkp --on "Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import task_time_low

# ZIL routine: LKP
# params: ITM, TBL
# aux: CNT, LEN

itm = args[0] if len(args) > 0 else None
tbl = args[1] if len(args) > 1 else None
cnt = 0
len_v = _.table_get(tbl, 0)

while True:
    if task_time_low():
        print("[zil] long-running loop in LKP; aborting (bug — please report).")
        return False
    if (cnt := (cnt + 1)) > len_v:
        return False
    elif _.table_get(tbl, cnt) == itm:
        if cnt == len_v:
            return False
        else:
            return _.table_get(tbl, (cnt + 1))
