#!moo verb mung_room --on "Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: MUNG-ROOM
# params: RM, STR

rm = args[0] if len(args) > 0 else None
str_v = args[1] if len(args) > 1 else None

rm.set_flag("rmungbit", True)
return rm.set_property("description", str_v)
