#!moo verb prep_find --on "Thing" --dspec this

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, task_time_low

# ZIL routine: PREP-FIND
# params: PREP
# aux: CNT, SIZE

player = context.player
prep = args[0] if len(args) > 0 else None
cnt = 0
size = 0

size = _.table_get(player.zstate_get("PREPOSITIONS"), 0) * 2
while True:
    if task_time_low():
        print("[zil] long-running loop in PREP-FIND; aborting (bug — please report).")
        return False
    if igrtr_p(cnt, size):
        return False
    elif _.table_get(player.zstate_get("PREPOSITIONS"), cnt) == prep:
        return _.table_get(player.zstate_get("PREPOSITIONS"), (cnt - 1))
