#!moo verb random_element --on "Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

import random

# ZIL routine: RANDOM-ELEMENT
# params: FROB

frob = args[0] if len(args) > 0 else None

# ZIL: <GET ...>
return _.table_get(frob, random.randint(1, _.table_get(frob, 0)))
