#!moo verb recover_stiletto --on "Thing" --dspec this

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import lookup

# ZIL routine: RECOVER-STILETTO

stiletto = lookup("stiletto")
thief = lookup("thief")

if stiletto.location == thief.location:
    stiletto.set_flag("ndescbit", True)
    return stiletto.moveto(thief)
