#!moo verb slider --on "Thing" --dspec this

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: SLIDER
# params: OBJ

player = context.player
obj = args[0] if len(args) > 0 else None

if obj.flag("takeable"):
    print("The " + obj.desc() + " falls into the slide and is gone.")
    if obj == lookup("water"):
        return _.remove(obj)
    else:
        return obj.moveto(lookup("cellar"))
else:
    print(_.pick(player.zstate_get("YUKS")))
    return
