#!moo verb weight --on "Thing" --dspec this

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, task_time_low

# ZIL routine: WEIGHT
# params: OBJ
# aux: CONT, WT

player = context.player
obj = args[0] if len(args) > 0 else None
cont = 0
wt = 0

if cont := obj.contents.first():
    while True:
        if task_time_low():
            print("[zil] long-running loop in WEIGHT; aborting (bug — please report).")
            return False
        if obj == player and cont.flag("wearbit"):
            wt = wt + 1
        else:
            wt = wt + _.thing.weight(cont)
        if not (cont := _.next_sibling(cont)):
            break
return wt + obj.getp("size")
