#!moo verb zmemqb --on "Thing" --dspec this

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import task_time_low

# ZIL routine: ZMEMQB
# params: ITM, TBL, SIZE
# aux: CNT

itm = args[0] if len(args) > 0 else None
tbl = args[1] if len(args) > 1 else None
size = args[2] if len(args) > 2 else None
cnt = 0

while True:
    if task_time_low():
        print("[zil] long-running loop in ZMEMQB; aborting (bug — please report).")
        return False
    if itm == _.table_get(tbl, cnt):
        return True
    elif igrtr_p(cnt, size):
        return False
