#!moo verb take get pick examine x describe what --on "board" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import invoked_verb_name

# ZIL routine: BOARD-F (take/examine branch)

the_player_verb = invoked_verb_name(verb_name)

print("The boards are securely fastened.")
return
