#!moo verb front_door_fcn --on "door" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL: FRONT-DOOR-FCN / combined OBJECT-FUNCTION dispatch
# Invoked by ``_.thing.dispatch_object_function(obj, verb, prep, iobj)``
# which looks up ``obj.action`` and calls ``obj.invoke_verb(action_atom, ...)``.

player = context.player
the_verb = args[0] if len(args) > 0 else None
prep = args[1] if len(args) > 1 else None
iobj = args[2] if len(args) > 2 else None
the_player_verb = the_verb

if the_verb == "open":
    print("The door cannot be opened.")
    return
elif the_verb == "burn":
    print("You cannot burn this door.")
    return
elif the_verb == "mung":
    print("You can't seem to damage the door.")
    return
elif the_verb == "look_behind":
    print("It won't open.")
    return
elif the_verb == "read":
    if player.here() == lookup("living_room"):
        print('The engravings translate to "This space intentionally left blank."', end="")
    elif print("There is no writing on this side.", end=""):
        pass
    print()
    return
return False
