#!moo verb look_behind --on "door" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import invoked_verb_name

# ZIL routine: FRONT-DOOR-FCN (look-behind branch)

the_player_verb = invoked_verb_name(verb_name)

print("It won't open.")
return
