#!moo verb mung destroy break smash crack --on "door" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: FRONT-DOOR-FCN (mung branch)

the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

print("You can't seem to damage the door.")
return
