#!moo verb read --on "door" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: FRONT-DOOR-FCN (read branch)

player = context.player
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if player.here() == lookup("living_room"):
    print('The engravings translate to "This space intentionally left blank."', end="")
elif print("There is no writing on this side.", end=""):
    pass
print()
return
