#!moo verb mung destroy break smash crack burn light --on "pile of bodies" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: BODY-FUNCTION (mung/burn branch)

the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

return _.jigs_up(
    'The voice of the guardian of the dungeon booms out from the darkness,\n"Your disrespect costs you your life!" and places your head on a sharp\npole.'
)
