#!moo verb mung destroy break smash crack --on "painting" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, invoked_verb_name

# ZIL routine: PAINTING-FCN (mung branch)

parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
the_player_verb = invoked_verb_name(verb_name)

(prso.set_property("tvalue", 0) if prso else None)
(prso.set_property("description", "There is a worthless piece of canvas here.") if prso else None)
print("Congratulations! Unlike the other vandals, who merely stole the\nartist's masterpieces, you have destroyed one.")
return
