#!moo verb painting_fcn --on "painting" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context

# ZIL: PAINTING-FCN / combined OBJECT-FUNCTION dispatch
# Invoked by ``_.thing.dispatch_object_function(obj, verb, prep, iobj)``
# which looks up ``obj.action`` and calls ``obj.invoke_verb(action_atom, ...)``.

parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
the_verb = args[0] if len(args) > 0 else None
prep = args[1] if len(args) > 1 else None
iobj = args[2] if len(args) > 2 else None
the_player_verb = the_verb

if the_verb == "mung":
    (prso.set_property("tvalue", 0) if prso else None)
    (prso.set_property("description", "There is a worthless piece of canvas here.") if prso else None)
    print(
        "Congratulations! Unlike the other vandals, who merely stole the\nartist's masterpieces, you have destroyed one."
    )
    return
return False
