#!moo verb examine x describe what --on "chimney" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: CHIMNEY-F (examine branch)

player = context.player
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

print("The chimney leads ", end="")
if player.here() == lookup("kitchen"):
    print("down", end="")
else:
    print("up", end="")
print("ward, and looks climbable.")
return
