#!moo verb examine x describe what --on "chimney" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name, lookup

# ZIL routine: CHIMNEY-F (examine branch)

player = context.player
the_player_verb = invoked_verb_name(verb_name)

print("The chimney leads ", end="")
if player.here() == lookup("kitchen"):
    print("down", end="")
else:
    print("up", end="")
print("ward, and looks climbable.")
return
