#!moo verb lamp-on --on "machine" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: MACHINE-F (lamp-on branch)

parser = context.parser
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if not (parser.get_iobj() if parser.has_iobj() else None):
    print("It's not clear how to turn it on with your bare hands.")
    return
else:
    _.perform("turn", lookup("machine_switch"), (parser.get_iobj() if parser.has_iobj() else None))
    return True
