#!moo verb lamp-on --on "machine" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, lookup

# ZIL routine: MACHINE-F (lamp-on branch)

parser = context.parser
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if not prsi:
    print("It's not clear how to turn it on with your bare hands.")
    return
else:
    _.perform("turn", lookup("machine_switch"), prsi)
    return True
