#!moo verb open --on "machine" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: MACHINE-F (open branch)

player = context.player
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if this.flag("open"):
    print(_.pick(player.zstate_get("DUMMY")))
    return
elif this.contents.first():
    print("The lid opens, revealing ", end="")
    # ZIL: <PRINT-CONTENTS ...>
    _.zork_thing.print_contents(this)
    print(".")
    return this.set_flag("open", True)
else:
    print("The lid opens.")
    return this.set_flag("open", True)
