#!moo verb leap --on "Canyon View" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context

# ZIL routine: CANYON-VIEW-F (leap branch)

parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
rarg = args[0] if len(args) > 0 else None
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if rarg == "M-BEG" and not prso:
    _.jigs_up("Nice view, lousy place to jump.")
    return True
return passthrough()
