#!moo verb attack kill hit fight stab cut slice mung destroy break smash crack --on "cretin (ME)" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, invoked_verb_name

# ZIL routine: CRETIN-FCN (attack/mung branch)

parser = context.parser
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
the_player_verb = invoked_verb_name(verb_name)

if prsi and (prsi.flag("weapon") if prsi else None):
    return _.jigs_up("If you insist.... Poof, you're dead!")
else:
    print("Suicide is not the answer.")
    return
