#!moo verb eat --on "cretin (ME)" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import invoked_verb_name

# ZIL routine: CRETIN-FCN (eat branch)

the_player_verb = invoked_verb_name(verb_name)

print("Auto-cannibalism is not the answer.")
return
