#!moo verb examine x describe what --on "cretin (ME)" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name, lookup

# ZIL routine: CRETIN-FCN (examine branch)

player = context.player
the_player_verb = invoked_verb_name(verb_name)

if player.here() in (lookup("mirror_1").location, lookup("mirror_2").location):
    print("Your image in the mirror looks tired.")
    return
else:
    print("That's difficult unless your eyes are prehensile.")
    return
