#!moo verb take get pick --on "cretin (ME)" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import invoked_verb_name

# ZIL routine: CRETIN-FCN (take branch)

the_player_verb = invoked_verb_name(verb_name)

print("How romantic!")
return
