#!moo verb dome_room_fcn look enterfunc --on "Dome Room" --dspec either

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name, lookup

# ZIL: DOME-ROOM-FCN / combined M-/F-clause dispatch

player = context.player
torch_room = lookup("torch_room")
verb_to_const = {"look": "M-LOOK", "enterfunc": "M-ENTER"}
rarg = args[0] if len(args) > 0 else verb_to_const.get(verb_name, "M-LOOK")
the_player_verb = args[1] if len(args) > 1 else invoked_verb_name(verb_name)

if rarg == "M-LOOK":
    print(this.desc())
    print(
        "You are at the periphery of a large dome, which forms the ceiling\nof another room below. Protecting you from a precipitous drop is a\nwooden railing which circles the dome."
    )
    if player.zstate_get("DOME-FLAG"):
        print("Hanging down from the railing is a rope which ends about ten feet\nfrom the floor below.")
    _.thing.describe_objects(True)
elif rarg == "M-ENTER":
    if player.zstate_get("DEAD"):
        print("As you enter the dome you feel a strong pull as if from a wind\ndrawing you over the railing and down.")
        player.moveto(torch_room)
        player.zstate_set("HERE", torch_room)
        return True
    elif the_player_verb == "leap":
        _.jigs_up("I'm afraid that the leap you attempted has done you in.")
