#!moo verb enterfunc --on "Dome Room" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name, lookup

# ZIL: DOME-ROOM-FCN / M-ENTER

player = context.player
torch_room = lookup("torch_room")
rarg = args[0] if len(args) > 0 else "M-ENTER"
the_player_verb = args[1] if len(args) > 1 else invoked_verb_name(verb_name)

if player.zstate_get("DEAD"):
    print("As you enter the dome you feel a strong pull as if from a wind\ndrawing you over the railing and down.")
    player.moveto(torch_room)
    player.zstate_set("HERE", torch_room)
    return True
elif the_player_verb == "leap":
    _.jigs_up("I'm afraid that the leap you attempted has done you in.")
