#!moo verb look --on "Dome Room" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name

# ZIL: DOME-ROOM-FCN / M-LOOK

player = context.player
rarg = args[0] if len(args) > 0 else "M-LOOK"
the_player_verb = args[1] if len(args) > 1 else invoked_verb_name(verb_name)

print(this.desc())
print(
    "You are at the periphery of a large dome, which forms the ceiling\nof another room below. Protecting you from a precipitous drop is a\nwooden railing which circles the dome."
)
if player.zstate_get("DOME-FLAG"):
    print("Hanging down from the railing is a rope which ends about ten feet\nfrom the floor below.")
_.thing.describe_objects(True)
