#!moo verb climb-up climb-down climb-foo --on "mountain range" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: MOUNTAIN-RANGE-F (climb-up/climb-down/climb-foo branch)

the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

print("Don't you believe me? The mountains are impassable!")
return
