#!moo verb attack kill hit fight stab cut slice mung destroy break smash crack --on "pseudo" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: CRETIN-FCN (attack/mung branch)

parser = context.parser
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if (parser.get_iobj() if parser.has_iobj() else None) and (
    parser.get_iobj().flag("weapon") if parser.has_iobj() else None
):
    return _.jigs_up("If you insist.... Poof, you're dead!")
else:
    print("Suicide is not the answer.")
    return
