#!moo verb cretin_fcn --on "pseudo" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, lookup

# ZIL: CRETIN-FCN / combined OBJECT-FUNCTION dispatch
# Invoked by ``_.thing.dispatch_object_function(obj, verb, prep, iobj)``
# which looks up ``obj.action`` and calls ``obj.invoke_verb(action_atom, ...)``.

player = context.player
parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
me = lookup("me")
the_verb = args[0] if len(args) > 0 else None
prep = args[1] if len(args) > 1 else None
iobj = args[2] if len(args) > 2 else None
the_player_verb = the_verb

if the_verb == "tell":
    player.zstate_set("P-CONT", False)
    player.zstate_set("QUOTE-FLAG", False)
    print("Talking to yourself is said to be a sign of impending mental collapse.")
    return
elif the_verb == "give":
    if prsi == me:
        _.perform("take", prso, None)
        return True
elif the_verb == "make":
    print("Only you can do that.")
    return
elif the_verb == "disembark":
    print("You'll have to do that on your own.")
    return
elif the_verb == "eat":
    print("Auto-cannibalism is not the answer.")
    return
elif the_verb == "attack" or the_verb == "mung":
    if prsi and (prsi.flag("weapon") if prsi else None):
        return _.jigs_up("If you insist.... Poof, you're dead!")
    else:
        print("Suicide is not the answer.")
        return
elif the_verb == "throw":
    if prso == me:
        print("Why don't you just walk like normal people?")
        return
elif the_verb == "take":
    print("How romantic!")
    return
elif the_verb == "examine":
    if player.here() in (lookup("mirror_1").location, lookup("mirror_2").location):
        print("Your image in the mirror looks tired.")
        return
    else:
        print("That's difficult unless your eyes are prehensile.")
        return
return False
