#!moo verb give --on "pseudo" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, lookup

# ZIL routine: CRETIN-FCN (give branch)

parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if prsi == lookup("me"):
    _.perform("take", prso, None)
    return True
return passthrough()
