#!moo verb tell --on "pseudo" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name

# ZIL routine: CRETIN-FCN (tell branch)

player = context.player
the_player_verb = invoked_verb_name(verb_name)

player.zstate_set("P-CONT", False)
player.zstate_set("QUOTE-FLAG", False)
print("Talking to yourself is said to be a sign of impending mental collapse.")
return
