#!moo verb throw toss --on "pseudo" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, invoked_verb_name, lookup

# ZIL routine: CRETIN-FCN (throw branch)

parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
the_player_verb = invoked_verb_name(verb_name)

if prso == lookup("me"):
    print("Why don't you just walk like normal people?")
    return
return passthrough()
