#!moo verb find get lower pick raise read take where --on "granite wall" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: GRANITE-WALL-F

player = context.player
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if player.here() == lookup("north_temple"):
    if the_player_verb in ["find", "where"]:
        print("The west wall is solid granite here.")
        return
    elif the_player_verb in ["take", "get", "pick", "raise", "lower"]:
        print("It's solid granite.")
        return
elif player.here() == lookup("treasure_room"):
    if the_player_verb in ["find", "where"]:
        print("The east wall is solid granite here.")
        return
    elif the_player_verb in ["take", "get", "pick", "raise", "lower"]:
        print("It's solid granite.")
        return
elif player.here() == lookup("slide_room"):
    if the_player_verb in ["find", "where", "read"]:
        print('It only SAYS "Granite Wall".')
        return
    else:
        print("The wall isn't granite.")
        return
else:
    print("There is no granite wall here.")
    return
