#!moo verb turn rotate --on "switch" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup, task_time_low

# ZIL routine: MSWITCH-FUNCTION (turn branch)

player = context.player
parser = context.parser
coal = lookup("coal")
machine = lookup("machine")
o = 0
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if (parser.get_iobj() if parser.has_iobj() else None) == lookup("screwdriver"):
    if machine.flag("open"):
        print("The machine doesn't seem to want to do anything.")
        return
    else:
        print(
            "The machine comes to life (figuratively) with a dazzling display of\ncolored lights and bizarre noises. After a few moments, the\nexcitement abates."
        )
        if coal.location == machine:
            _.remove(coal)
            return lookup("diamond").moveto(machine)
        else:
            while True:
                if task_time_low():
                    print("[zil] long-running loop in MSWITCH-FUNCTION; aborting (bug — please report).")
                    return False
                if o := machine.contents.first():
                    _.remove(o)
                else:
                    break
            return lookup("gunk").moveto(machine)
elif not (parser.get_iobj() if parser.has_iobj() else None) in (False, lookup("hands"), player.zstate_get("ROOMS")):
    print("It seems that a " + (parser.get_iobj().desc() if parser.has_iobj() else "") + " won't do.")
    return
return passthrough()
