#!moo verb turn rotate --on "switch" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, invoked_verb_name, lookup, task_time_low

# ZIL routine: MSWITCH-FUNCTION (turn branch)

player = context.player
parser = context.parser
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
coal = lookup("coal")
machine = lookup("machine")
o = 0
the_player_verb = invoked_verb_name(verb_name)

if prsi == lookup("screwdriver"):
    if machine.flag("open"):
        print("The machine doesn't seem to want to do anything.")
        return
    else:
        print(
            "The machine comes to life (figuratively) with a dazzling display of\ncolored lights and bizarre noises. After a few moments, the\nexcitement abates."
        )
        if coal.location == machine:
            _.remove(coal)
            return lookup("diamond").moveto(machine)
        else:
            while True:
                if task_time_low():
                    print("[zil] long-running loop in MSWITCH-FUNCTION; aborting (bug — please report).")
                    return False
                if o := machine.contents.first():
                    _.remove(o)
                else:
                    break
            return lookup("gunk").moveto(machine)
elif not prsi in (False, lookup("hands"), player.zstate_get("ROOMS")):
    print("It seems that a " + (prsi.desc() if prsi else "") + " won't do.")
    return
return passthrough()
