#!moo verb board --on "Thing" --dspec this

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context

# ZIL routine: V-BOARD
# aux: AV

player = context.player
parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
av = 0

if prso is None:
    if context.parser is not None and context.parser.has_dobj_str():
        print("There is no '" + context.parser.dobj_str + "' here.")
    else:
        print("What do you want to board?")
    return

pre_x = "pre_board"
if _.thing.invoke_verb(pre_x):
    return
print("You are now in the " + (prso.desc() if prso else "") + ".")
player.moveto(prso)
# ZIL: <APPLY ...>
if prso is not None and (prso.has_verb("enterfunc", recurse=False) if prso else None):
    (prso.invoke_verb("enterfunc") if prso else None)
return True
