#!moo verb burn incinerate ignite light --on "Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context

# ZIL routine: V-BURN

player = context.player
parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None

if prso is None:
    if context.parser is not None and context.parser.has_dobj_str():
        print("There is no '" + context.parser.dobj_str + "' here.")
    else:
        print("What do you want to burn?")
    return

pre_x = "pre_burn"
if _.thing.invoke_verb(pre_x):
    return
if _.thing.null_f():
    return False
elif prso.flag("flammable") if prso else None:
    if (prso is not None and prso.location == player) or player.location == prso:
        _.remove(prso)
        print("The " + (prso.desc() if prso else "") + " catches fire. Unfortunately, you were ", end="")
        if player.location == prso:
            print("in", end="")
        else:
            print("holding", end="")
        return _.jigs_up(" it at the time.")
    else:
        _.remove(prso)
        print("The " + (prso.desc() if prso else "") + " catches fire and is consumed.")
        return
else:
    print("You can't burn a " + (prso.desc() if prso else "") + ".")
    return
