#!moo verb kick taunt --on "Thing" --dspec this

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: V-KICK

# ZIL: <HACK-HACK ...>
return _.thing.hack_hack("Kicking the ")
