#!moo verb kiss --on "Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: V-KISS

print("I'd sooner kiss a pig.")
return
