#!moo verb look l stare gaze --on "Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: V-LOOK

if _.thing.describe_room(True):
    # ZIL: <DESCRIBE-OBJECTS ...>
    return _.thing.describe_objects(True)
