#!moo verb look_under --on "Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: V-LOOK-UNDER

print("There is nothing but dust there.")
return
