#!moo verb lower --on "Thing" --dspec this

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: V-LOWER

# ZIL: <HACK-HACK ...>
return _.thing.hack_hack("Playing in this way with the ")
