#!moo verb oil lubricate grease --on "Thing" --dspec this

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: V-OIL

print("You probably put spinach in your gas tank, too.")
return
