#!moo verb pour_on --on "Thing" --dspec this

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, lookup

# ZIL routine: V-POUR-ON

parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
putty = lookup("putty")

if prso is None:
    if context.parser is not None and context.parser.has_dobj_str():
        print("There is no '" + context.parser.dobj_str + "' here.")
    else:
        print("What do you want to pour on?")
    return

if prso == lookup("water"):
    _.remove(prso)
    if flaming_p(prsi):
        print("The " + (prsi.desc() if prsi else "") + " is extinguished.")
        # ZIL: <NULL-F ...>
        _.thing.null_f()
        (prsi.set_flag("onbit", False) if prsi else None)
        return prsi.set_flag("flamebit", False) if prsi else None
    else:
        print("The water spills over the " + (prsi.desc() if prsi else "") + ", to the floor, and evaporates.")
        return
elif prso == putty:
    return _.perform("put", putty, prsi)
else:
    print("You can't pour that.")
    return
