#!moo verb put_behind --on "Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: V-PUT-BEHIND

print("That hiding place is too obvious.")
return
