#!moo verb raise lift --on "Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: V-RAISE

# ZIL: <V-LOWER ...>
return _.thing.lower()
