#!moo verb record --on "Thing" --dspec none

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: V-RECORD

# ZIL: <DIROUT ...>
dirout(4)
return True
