#!moo verb spin --on "Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: V-SPIN

print("You can't spin that!")
return
