#!moo verb stab --on "Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context

# ZIL routine: V-STAB
# aux: W

player = context.player
parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
w = 0

if prso is None:
    if context.parser is not None and context.parser.has_dobj_str():
        print("There is no '" + context.parser.dobj_str + "' here.")
    else:
        print("What do you want to stab?")
    return

if w := _.thing.find_weapon(player):
    _.perform("attack", prso, w)
    return True
else:
    print("No doubt you propose to stab the " + (prso.desc() if prso else "") + " with your pinky?")
    return
