#!moo verb tie_up --on "Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: V-TIE-UP

print("You could certainly never tie it with that!")
return
