#!moo verb walk_to --on "Thing" --dspec this

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context

# ZIL routine: V-WALK-TO

player = context.player
parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None

if prso is None:
    if context.parser is not None and context.parser.has_dobj_str():
        print("There is no '" + context.parser.dobj_str + "' here.")
    else:
        print("What do you want to walk to?")
    return

if prso and ((prso is not None and prso.location == player.here()) or prso.global_in(player.here())):
    print("It's here!")
    return
else:
    print("You should supply a direction!")
    return
