#!moo verb walk_around go run proceed step --on "Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL routine: V-WALK-AROUND

print("Use compass directions for movement.")
return
