#!moo verb examine x describe what --on "brass lantern" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import invoked_verb_name

# ZIL routine: LANTERN (examine branch)

the_player_verb = invoked_verb_name(verb_name)

print("The lamp ", end="")
if this.flag("rmungbit"):
    print("has burned out.", end="")
elif this.flag("onbit"):
    print("is on.", end="")
else:
    print("is turned off.", end="")
print()
return
