#!moo verb lamp-off --on "brass lantern" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: LANTERN (lamp-off branch)

the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if this.flag("rmungbit"):
    print("The lamp has already burned out.")
    return
else:
    return _.cancel("i-lantern")
