#!moo verb lamp-off --on "brass lantern" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import invoked_verb_name

# ZIL routine: LANTERN (lamp-off branch)

the_player_verb = invoked_verb_name(verb_name)

if this.flag("rmungbit"):
    print("The lamp has already burned out.")
    return
else:
    return _.cancel("i-lantern")
