#!moo verb cyclops_fcn --on "cyclops" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, lookup

# ZIL: CYCLOPS-FCN / combined OBJECT-FUNCTION dispatch
# Invoked by ``_.thing.dispatch_object_function(obj, verb, prep, iobj)``
# which looks up ``obj.action`` and calls ``obj.invoke_verb(action_atom, ...)``.

player = context.player
parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
bottle = lookup("bottle")
lunch = lookup("lunch")
water = lookup("water")
the_verb = args[0] if len(args) > 0 else None
prep = args[1] if len(args) > 1 else None
iobj = args[2] if len(args) > 2 else None
count = 0
the_player_verb = the_verb

if the_verb == "examine":
    print("A hungry cyclops is standing at the foot of the stairs.")
    return
elif the_verb == "give":
    if prsi == this:
        if prso == lunch:
            if not count < 0:
                _.remove(lunch)
                print(
                    'The cyclops says "Mmm Mmm. I love hot peppers! But oh, could I use\na drink. Perhaps I could drink the blood of that thing."  From the\ngleam in his eye, it could be surmised that you are "that thing".'
                )
                player.zstate_set("CYCLOWRATH", min(-1, (-count)))
            return _.queue("i-cyclops", -1)
        elif prso == water or (prso == bottle and water.location == bottle):
            if count < 0:
                _.remove(water)
                bottle.moveto(player.here())
                bottle.set_flag("open", True)
                this.set_flag("hostile", False)
                print(
                    "The cyclops takes the bottle, checks that it's open, and drinks the water.\nA moment later, he lets out a yawn that nearly blows you over, and then\nfalls fast asleep (what did you put in that drink, anyway?)."
                )
                return player.zstate_set("CYCLOPS-FLAG", True)
            else:
                print("The cyclops apparently is not thirsty and refuses your generous offer.")
                return
        elif prso == lookup("garlic"):
            print("The cyclops may be hungry, but there is a limit.")
            return
        else:
            print("The cyclops is not so stupid as to eat THAT!")
            return
elif the_verb == "throw" or the_verb == "attack" or the_verb == "mung":
    _.queue("i-cyclops", -1)
    if the_player_verb in ["mung", "destroy", "break", "smash", "crack"]:
        print('"Do you think I\'m as stupid as my father was?", he says, dodging.')
        return
    else:
        print("The cyclops shrugs but otherwise ignores your pitiful attempt.")
        if the_player_verb in ["throw", "toss"]:
            prso.moveto(player.here())
        return True
elif the_verb == "take":
    print("The cyclops doesn't take kindly to being grabbed.")
    return
elif the_verb == "tie":
    print("You cannot tie the cyclops, though he is fit to be tied.")
    return
elif the_verb == "listen":
    print("You can hear his stomach rumbling.")
    return
return False
