#!moo verb examine x describe what --on "cyclops" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: CYCLOPS-FCN (examine branch)

count = 0
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

print("A hungry cyclops is standing at the foot of the stairs.")
return
