#!moo verb examine x describe what --on "cyclops" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import invoked_verb_name

# ZIL routine: CYCLOPS-FCN (examine branch)

count = 0
the_player_verb = invoked_verb_name(verb_name)

print("A hungry cyclops is standing at the foot of the stairs.")
return
