#!moo verb give --on "cyclops" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: CYCLOPS-FCN (give branch)

player = context.player
parser = context.parser
bottle = lookup("bottle")
lunch = lookup("lunch")
water = lookup("water")
count = 0
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if (parser.get_iobj() if parser.has_iobj() else None) == this:
    if (parser.get_dobj() if parser.has_dobj_str() else None) == lunch:
        if not count < 0:
            _.remove(lunch)
            print(
                'The cyclops says "Mmm Mmm. I love hot peppers! But oh, could I use\na drink. Perhaps I could drink the blood of that thing."  From the\ngleam in his eye, it could be surmised that you are "that thing".'
            )
            player.zstate_set("CYCLOWRATH", min(-1, (-count)))
        return _.queue("i-cyclops", -1)
    elif (parser.get_dobj() if parser.has_dobj_str() else None) == water or (
        (parser.get_dobj() if parser.has_dobj_str() else None) == bottle and water.location == bottle
    ):
        if count < 0:
            _.remove(water)
            bottle.moveto(player.here())
            bottle.set_flag("open", True)
            this.set_flag("hostile", False)
            print(
                "The cyclops takes the bottle, checks that it's open, and drinks the water.\nA moment later, he lets out a yawn that nearly blows you over, and then\nfalls fast asleep (what did you put in that drink, anyway?)."
            )
            return player.zstate_set("CYCLOPS-FLAG", True)
        else:
            print("The cyclops apparently is not thirsty and refuses your generous offer.")
            return
    elif (parser.get_dobj() if parser.has_dobj_str() else None) == lookup("garlic"):
        print("The cyclops may be hungry, but there is a limit.")
        return
    else:
        print("The cyclops is not so stupid as to eat THAT!")
        return
return passthrough()
