#!moo verb listen hear --on "cyclops" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import invoked_verb_name

# ZIL routine: CYCLOPS-FCN (listen branch)

count = 0
the_player_verb = invoked_verb_name(verb_name)

print("You can hear his stomach rumbling.")
return
