#!moo verb hero_blow --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

import random
from moo.sdk import context, task_time_low

# ZIL routine: HERO-BLOW
# aux: OO, VILLAIN, OUT?, DWEAPON, ATT, DEF, CNT, OA, OD, TBL, RES, LEN

player = context.player
parser = context.parser
oo = 0
villain = 0
out_p = 0
dweapon = 0
att = 0
def_v = 0
cnt = 0
oa = 0
od = 0
tbl = 0
res = 0
len_v = _.table_get(player.zstate_get("VILLAINS"), 0)

while True:
    if task_time_low():
        print("[zil] long-running loop in HERO-BLOW; aborting (bug — please report).")
        return False
    cnt = cnt + 1
    if cnt == len_v:
        break
    oo = _.table_get(player.zstate_get("VILLAINS"), cnt)
    if _.table_get(oo, player.zstate_get("V-VILLAIN")) == (parser.get_dobj() if parser.has_dobj_str() else None):
        break
(parser.get_dobj() if parser.has_dobj_str() else None).set_flag("hostile", True)
if player.flag("staggered"):
    print("You are still recovering from that last blow, so your attack is\nineffective.")
    player.set_flag("staggered", False)
    return True
att = _.zork_thing.fight_strength()
if att < 1:
    att = 1
oa = att
villain = _.table_get(oo, player.zstate_get("V-VILLAIN"))
if (od := (def_v := _.zork_thing.villain_strength(oo))) == 0:
    if (parser.get_dobj() if parser.has_dobj_str() else None) == player:
        return _.jigs_up("Well, you really did it that time. Is suicide painless?")
    print("Attacking the " + villain.desc() + " is pointless.")
    return True
dweapon = _.zork_thing.find_weapon(villain)
if not dweapon or def_v < 0:
    print("The ", end="")
    if def_v < 0:
        print("unconscious", end="")
    else:
        print("unarmed", end="")
    print(" " + villain.desc() + " cannot defend himself: He dies.")
    res = player.zstate_get("KILLED")
else:
    if def_v == 1:
        if att > 2:
            att = 3
        tbl = _.table_get(player.zstate_get("DEF1-RES"), (att - 1))
    elif def_v == 2:
        if att > 3:
            att = 4
        tbl = _.table_get(player.zstate_get("DEF2-RES"), (att - 1))
    elif def_v > 2:
        att = att - def_v
        if att < -1:
            att = -2
        elif att > 1:
            att = 2
        tbl = _.table_get(player.zstate_get("DEF3-RES"), (att + 2))
    res = _.table_get(tbl, (random.randint(1, 9) - 1))
    if out_p:
        if res == player.zstate_get("STAGGER"):
            res = player.zstate_get("HESITATE")
        else:
            res = player.zstate_get("SITTING-DUCK")
    if res == player.zstate_get("STAGGER") and dweapon and random.randint(1, 100) <= 25:
        res = player.zstate_get("LOSE-WEAPON")
    # ZIL: <REMARK ...>
    _.zork_thing.remark(
        _.zork_thing.random_element(_.table_get(player.zstate_get("HERO-MELEE"), (res - 1))),
        (parser.get_dobj() if parser.has_dobj_str() else None),
        (parser.get_iobj() if parser.has_iobj() else None),
    )
if res == player.zstate_get("MISSED") or res == player.zstate_get("HESITATE"):
    pass
elif res == player.zstate_get("UNCONSCIOUS"):
    def_v = -def_v
elif res == player.zstate_get("KILLED") or res == player.zstate_get("SITTING-DUCK"):
    def_v = 0
elif res == player.zstate_get("LIGHT-WOUND"):
    def_v = def_v - 1
    if def_v < 0:
        def_v = 0
elif res == player.zstate_get("SERIOUS-WOUND"):
    def_v = def_v - 2
    if def_v < 0:
        def_v = 0
elif res == player.zstate_get("STAGGER"):
    (parser.get_dobj() if parser.has_dobj_str() else None).set_flag("staggered", True)
else:
    dweapon.set_flag("ndescbit", False)
    dweapon.set_flag("weapon", True)
    dweapon.moveto(player.here())
    # ZIL: <THIS-IS-IT ...>
    _.zork_thing.this_is_it(dweapon)
# ZIL: <VILLAIN-RESULT ...>
return _.zork_thing.villain_result((parser.get_dobj() if parser.has_dobj_str() else None), def_v, res)
