#!moo verb hit_spot --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: HIT-SPOT

player = context.player
parser = context.parser

if (parser.get_dobj() if parser.has_dobj_str() else None) == lookup("water") and not lookup("global_water").global_in(
    player.here()
):
    _.remove((parser.get_dobj() if parser.has_dobj_str() else None))
print("Thank you very much. I was rather thirsty (from all this talking,\nprobably).")
return
