#!moo verb itake --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

import random
from moo.sdk import NoSuchObjectError, context, invoked_verb_name

# ZIL routine: ITAKE
# params: VB
# aux: CNT, OBJ

player = context.player
parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
vb = args[0] if len(args) > 0 else True
cnt = 0
obj = 0
the_player_verb = invoked_verb_name(verb_name)

if prso is None:
    if context.parser is not None and context.parser.has_dobj_str():
        print("There is no '" + context.parser.dobj_str + "' here.")
    else:
        print("I don't know how to do that.")
    return

player.zstate_get("#DECL")
if player.zstate_get("DEAD"):
    if vb:
        print("Your hand passes through its object.")
    return False
elif not (prso.flag("takeable") if prso else None):
    if vb:
        print(_.pick(player.zstate_get("YUKS")))
    return False
elif _.zork_thing.null_f():
    return False
elif prso.location.flag("contbit") and not prso.location.flag("open"):
    return False
elif not prso.location.location == player and (
    _.zork_thing.weight(prso) + _.zork_thing.weight(player)
) > player.zstate_get("LOAD-ALLOWED"):
    if vb:
        print("Your load is too heavy", end="")
        if player.zstate_get("LOAD-ALLOWED") < player.zstate_get("LOAD-MAX"):
            print(", especially in light of your condition.", end="")
        else:
            print(".", end="")
        print()
    # ZIL: <RFATAL ...>
    return 2
elif (
    the_player_verb in ["take", "get", "pick"]
    and (cnt := _.zork_thing.ccount(player)) > player.zstate_get("FUMBLE-NUMBER")
    and random.randint(1, 100) <= (cnt * player.zstate_get("FUMBLE-PROB"))
):
    print("You're holding too many things already!")
    return False
else:
    (prso.moveto(player) if prso else None)
    (prso.set_flag("ndescbit", False) if prso else None)
    (prso.set_flag("touchbit", True) if prso else None)
    # ZIL: <NULL-F ...>
    _.zork_thing.null_f()
    if player.zstate_get("ZORK-NUMBER") == 1 or player.zstate_get("ZORK-NUMBER") == 2:
        # ZIL: <SCORE-OBJ ...>
        _.zork_thing.score_obj(prso)
    else:
        # ZIL: <NULL-F ...>
        _.zork_thing.null_f()
    return True
