#!moo verb kill_interrupts --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import lookup

# ZIL routine: KILL-INTERRUPTS

_.cancel("i-xb")
_.cancel("i-xc")
_.cancel("i-cyclops")
_.cancel("i-lantern")
_.cancel("i-candles")
_.cancel("i-sword")
_.cancel("i-forest-room")
_.cancel("i-match")
lookup("match").set_flag("onbit", False)
return True
