#!moo verb maze_diodes --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: MAZE-DIODES

player = context.player

print("You won't be able to get back up to the tunnel you are going through\nwhen it gets to the next room.")
if player.here() == lookup("maze_2"):
    return lookup("maze_4")
elif player.here() == lookup("maze_7"):
    return lookup("dead_end_1")
elif player.here() == lookup("maze_9"):
    return lookup("maze_11")
elif player.here() == lookup("maze_12"):
    return lookup("maze_5")
