#!moo verb other_side --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, task_time_low

# ZIL routine: OTHER-SIDE
# params: DOBJ
# aux: P, TX

player = context.player
dobj = args[0] if len(args) > 0 else None
p = 0
tx = 0

while True:
    if task_time_low():
        print("[zil] long-running loop in OTHER-SIDE; aborting (bug — please report).")
        return False
    if (p := nextp(player.here(), p)) < player.zstate_get("LOW-DIRECTION"):
        return False
    else:
        tx = getpt(player.here(), p)
        if ptsize(tx) == player.zstate_get("DEXIT") and _.table_get(tx, player.zstate_get("DEXITOBJ")) == dobj:
            return p
