#!moo verb shake_loop --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup, task_time_low

# ZIL routine: SHAKE-LOOP
# aux: X

player = context.player
parser = context.parser
pseudo_object = lookup("pseudo_object")
x = 0

while True:
    if task_time_low():
        print("[zil] long-running loop in SHAKE-LOOP; aborting (bug — please report).")
        return False
    if x := (parser.get_dobj() if parser.has_dobj_str() else None).contents.first():
        x.set_flag("touchbit", True)
        return x.moveto(
            (
                (
                    lookup("path")
                    if player.here() == lookup("up_a_tree")
                    else (pseudo_object if not player.here().flag("outdoor") else player.here())
                )
                if player.zstate_get("ZORK-NUMBER") == 1
                else (
                    (
                        pseudo_object
                        if x == lookup("water")
                        else (pseudo_object if not player.here().flag("outdoor") else player.here())
                    )
                    if player.zstate_get("ZORK-NUMBER") == 2
                    else (
                        player.zstate_get("IN-LAKE") if player.here() == player.zstate_get("ON-LAKE") else player.here()
                    )
                )
            )
        )
    else:
        break
