#!moo verb take_check --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: TAKE-CHECK

player = context.player
parser = context.parser

if _.zork_thing.itake_check(
    (parser.get_dobj() if parser.has_dobj_str() else None),
    _.table_get(player.zstate_get("P-SYNTAX"), player.zstate_get("P-SLOC1")),
):
    # ZIL: <ITAKE-CHECK ...>
    return _.zork_thing.itake_check(
        (parser.get_iobj() if parser.has_iobj() else None),
        _.table_get(player.zstate_get("P-SYNTAX"), player.zstate_get("P-SLOC2")),
    )
