#!moo verb untie_from --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: UNTIE-FROM

player = context.player
parser = context.parser

if (parser.get_dobj() if parser.has_dobj_str() else None) == lookup("rope") and (
    player.zstate_get("DOME-FLAG") and (parser.get_iobj() if parser.has_iobj() else None) == lookup("railing")
):
    return _.perform("untie", (parser.get_dobj() if parser.has_dobj_str() else None), None)
else:
    print("It's not attached to that!")
    return
