#!moo verb examine x describe what look-inside --on "large bag" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: LARGE-BAG-F (examine/look-inside branch)

the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

print("The bag is underneath the thief, so one can't say what, if anything, is\ninside.")
return
