#!moo verb open close shut --on "large bag" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import invoked_verb_name

# ZIL routine: LARGE-BAG-F (open/close branch)

the_player_verb = invoked_verb_name(verb_name)

print("Getting close enough would be a good trick.")
return
