#!moo verb take get pick --on "large bag" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: LARGE-BAG-F (take branch)

player = context.player
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if lookup("thief").getp("description") == player.zstate_get("ROBBER-U-DESC"):
    print("Sadly for you, the robber collapsed on top of the bag. Trying to take\nit would wake him.")
    return
else:
    print("The bag will be taken over his dead body.")
    return
