#!moo verb find where --on "passage" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: PATH-OBJECT (find branch)

the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

print("I can't help you there....")
return
