#!moo verb path_object --on "passage" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL: PATH-OBJECT / combined OBJECT-FUNCTION dispatch
# Invoked by ``_.thing.dispatch_object_function(obj, verb, prep, iobj)``
# which looks up ``obj.action`` and calls ``obj.invoke_verb(action_atom, ...)``.

the_verb = args[0] if len(args) > 0 else None
prep = args[1] if len(args) > 1 else None
iobj = args[2] if len(args) > 2 else None
the_player_verb = the_verb

if the_verb == "take" or the_verb == "follow":
    print("You must specify a direction to go.")
    return
elif the_verb == "find":
    print("I can't help you there....")
    return
elif the_verb == "dig":
    print("Not a chance.")
    return
return False
