#!moo verb take get pick follow --on "passage" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import invoked_verb_name

# ZIL routine: PATH-OBJECT (take/follow branch)

the_player_verb = invoked_verb_name(verb_name)

print("You must specify a direction to go.")
return
