#!moo verb i_cyclops --on "Thing" --dspec this

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: I-CYCLOPS

player = context.player

if player.zstate_get("CYCLOPS-FLAG") or player.zstate_get("DEAD"):
    return True
elif not player.here() == lookup("cyclops_room"):
    return _.cancel("i-cyclops")
else:
    if abs(player.zstate_get("CYCLOWRATH")) > 5:
        _.cancel("i-cyclops")
        return _.jigs_up(
            "The cyclops, tired of all of your games and trickery, grabs you firmly.\nAs he licks his chops, he says \"Mmm. Just like Mom used to make 'em.\"\nIt's nice to be appreciated."
        )
    else:
        if player.zstate_get("CYCLOWRATH") < 0:
            player.zstate_set("CYCLOWRATH", (player.zstate_get("CYCLOWRATH") - 1))
        else:
            player.zstate_set("CYCLOWRATH", (player.zstate_get("CYCLOWRATH") + 1))
        if not player.zstate_get("CYCLOPS-FLAG"):
            print(nth(player.zstate_get("CYCLOMAD"), (abs(player.zstate_get("CYCLOWRATH")) - 1)))
            return
