#!moo verb i_maint_room --on "Thing" --dspec this

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: I-MAINT-ROOM
# aux: HERE?

player = context.player
maintenance_room = lookup("maintenance_room")
here_p = 0

here_p = player.here() == maintenance_room
if here_p:
    print(
        "The water level here is now "
        + _.table_get(player.zstate_get("DROWNINGS"), (player.zstate_get("WATER-LEVEL") // 2)),
        end="",
    )
    print()
player.zstate_set("WATER-LEVEL", (1 + player.zstate_get("WATER-LEVEL")))
if not player.zstate_get("WATER-LEVEL") < 14:
    # ZIL: <MUNG-ROOM ...>
    _.thing.mung_room(maintenance_room, "The room is full of water and cannot be entered.")
    _.schedule_realtime("i_maint_room", 0)
    if here_p:
        _.jigs_up("I'm afraid you have done drowned yourself.")
elif player.location == lookup("inflated_boat") and player.here() in (
    maintenance_room,
    lookup("dam_room"),
    lookup("dam_lobby"),
):
    _.jigs_up("The rising water carries the boat over the dam, down the river, and over\nthe falls. Tsk, tsk.")
return True
