#!moo verb i_sword --on "Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup, task_time_low

# ZIL routine: I-SWORD
# aux: DEM, G, NG, P, T, L

player = context.player
sword = lookup("sword")
dem = None
g = sword.getp("tvalue")
ng = 0
p = 0
t = 0
l = 0

if sword.location == player:
    if _.thing.is_infested(player.here()):
        ng = 2
    else:
        p = 0
        while True:
            if task_time_low():
                print("[zil] long-running loop in I-SWORD; aborting (bug — please report).")
                return False
            if (p := nextp(player.here(), p)) == 0:
                break
            elif not p < player.zstate_get("LOW-DIRECTION"):
                t = getpt(player.here(), p)
                l = ptsize(True)
                if l in (player.zstate_get("UEXIT"), player.zstate_get("CEXIT"), player.zstate_get("DEXIT")):
                    if _.thing.is_infested(_.table_get(True, 0)):
                        ng = 1
                        break
    if ng == g:
        return False
    elif ng == 2:
        print("Your sword has begun to glow very brightly.")
    elif ng == 1:
        print("Your sword is glowing with a faint blue glow.")
    elif ng == 0:
        print("Your sword is no longer glowing.")
    sword.set_property("tvalue", ng)
    return True
else:
    # ZIL: <PUT ...>
    _.table_put(dem, player.zstate_get("C-ENABLED?"), 0)
    return False
