#!moo verb basket_f --on "Zork Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: BASKET-F

parser = context.parser

if (parser.get_dobj() if parser.has_dobj_str() else None) == this or (
    parser.get_iobj() if parser.has_iobj() else None
) == this:
    print("The basket is at the other end of the chain.")
    return
return passthrough()
