#!moo verb lower --on "basket (LOWERED-BASKET)" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name, lookup

# ZIL routine: BASKET-F (lower branch)

player = context.player
the_player_verb = invoked_verb_name(verb_name)

if not player.zstate_get("CAGE-TOP"):
    print(_.pick(player.zstate_get("DUMMY")))
    return
else:
    lookup("raised_basket").moveto(lookup("lower_shaft"))
    this.moveto(lookup("shaft_room"))
    # ZIL: <THIS-IS-IT ...>
    _.thing.this_is_it(this)
    print("The basket is lowered to the bottom of the shaft.")
    player.zstate_set("CAGE-TOP", False)
    if player.zstate_get("LIT") and not player.zstate_set("LIT", _.thing.is_lit(player.here())):
        print("It is now pitch black.")
    return True
