#!moo verb squeeze --on "tube" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, invoked_verb_name, lookup

# ZIL routine: TUBE-FUNCTION (squeeze branch)

player = context.player
parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
putty = lookup("putty")
the_player_verb = invoked_verb_name(verb_name)

if (prso.flag("open") if prso else None) and putty.location == prso:
    putty.moveto(player)
    print("The viscous material oozes into your hand.")
    return
elif prso.flag("open") if prso else None:
    print("The tube is apparently empty.")
    return
else:
    print("The tube is closed.")
    return
