#!moo verb eat --on "clove of garlic" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, invoked_verb_name

# ZIL routine: GARLIC-F (eat branch)

parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
the_player_verb = invoked_verb_name(verb_name)

_.remove(prso)
print("What the heck! You won't make friends this way, but nobody around\nhere is too friendly anyhow. Gulp!")
return
