#!moo verb insert oil place put --on "viscous material" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: PUTTY-FCN

parser = context.parser
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if (the_player_verb == "oil" and (parser.get_iobj() if parser.has_iobj() else None) == this) or (
    the_player_verb in ["put", "place", "insert"] and (parser.get_dobj() if parser.has_dobj_str() else None) == this
):
    print("The all-purpose gunk isn't a lubricant.")
    return
