#!moo verb dam_function --on "dam (DAM)" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, lookup

# ZIL: DAM-FUNCTION / combined OBJECT-FUNCTION dispatch
# Invoked by ``_.thing.dispatch_object_function(obj, verb, prep, iobj)``
# which looks up ``obj.action`` and calls ``obj.invoke_verb(action_atom, ...)``.

parser = context.parser
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
the_verb = args[0] if len(args) > 0 else None
prep = args[1] if len(args) > 1 else None
iobj = args[2] if len(args) > 2 else None
the_player_verb = the_verb

if the_verb == "open" or the_verb == "close":
    print("Sounds reasonable, but this isn't how.")
    return
elif the_verb == "plug":
    if prsi == lookup("hands"):
        print("Are you the little Dutch boy, then? Sorry, this is a big dam.")
        return
    else:
        print(
            "With a "
            + (prsi.desc() if prsi else "")
            + "? Do you know how big this dam is? You could only\nstop a tiny leak with that."
        )
        return
return False
