#!moo verb open close shut --on "dam (DAM)" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: DAM-FUNCTION (open/close branch)

the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

print("Sounds reasonable, but this isn't how.")
return
