#!moo verb plug --on "dam (DAM)" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, invoked_verb_name, lookup

# ZIL routine: DAM-FUNCTION (plug branch)

parser = context.parser
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
the_player_verb = invoked_verb_name(verb_name)

if prsi == lookup("hands"):
    print("Are you the little Dutch boy, then? Sorry, this is a big dam.")
    return
else:
    print(
        "With a "
        + (prsi.desc() if prsi else "")
        + "? Do you know how big this dam is? You could only\nstop a tiny leak with that."
    )
    return
