#!moo verb through --on "crack" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import invoked_verb_name

# ZIL routine: CRACK-FCN (through branch)

the_player_verb = invoked_verb_name(verb_name)

print("You can't fit through the crack.")
return
