#!moo verb break climb_on crack destroy hatch mung open smash throw toss --on "jewel-encrusted egg" --dspec any --ispec on:this in:this at:this with:this from:this under:this over:this before:this around:this through:this behind:this beside:this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, invoked_verb_name, lookup

# ZIL routine: EGG-OBJECT

player = context.player
parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
the_player_verb = invoked_verb_name(verb_name)

if the_player_verb in ["open", "mung", "destroy", "break", "smash", "crack"] and prso == this:
    if prso.flag("open") if prso else None:
        print("The egg is already open.")
        return
    elif not prsi:
        print("You have neither the tools nor the expertise.")
        return
    elif prsi == lookup("hands"):
        print("I doubt you could do that without damaging it.")
        return
    elif (
        (prsi.flag("weapon") if prsi else None)
        or (prsi.flag("toolbit") if prsi else None)
        or the_player_verb in ["mung", "destroy", "break", "smash", "crack"]
    ):
        print(
            "The egg is now open, but the clumsiness of your attempt has seriously\ncompromised its esthetic appeal.",
            end="",
        )
        # ZIL: <BAD-EGG ...>
        _.thing.bad_egg()
        print()
        return
    elif prso.flag("hostile") if prso else None:
        print("Not to say that using the " + (prsi.desc() if prsi else "") + " isn't original too...")
        return
    else:
        print("The concept of using a " + (prsi.desc() if prsi else "") + " is certainly original.")
        return prso.set_flag("hostile", True) if prso else None
elif the_player_verb in ["climb_on", "hatch"]:
    print(
        "There is a noticeable crunch from beneath you, and inspection reveals\nthat the egg is lying open, badly damaged.",
        end="",
    )
    # ZIL: <BAD-EGG ...>
    _.thing.bad_egg()
    print()
    return
elif the_player_verb in ["open", "mung", "destroy", "break", "smash", "crack", "throw", "toss"]:
    if the_player_verb in ["throw", "toss"]:
        prso.moveto(player.here())
    print(
        "Your rather indelicate handling of the egg has caused it some damage,\nalthough you have succeeded in opening it.",
        end="",
    )
    # ZIL: <BAD-EGG ...>
    _.thing.bad_egg()
    print()
    return
