#!moo verb climb-on hatch --on "jewel-encrusted egg" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import invoked_verb_name

# ZIL routine: EGG-OBJECT (climb-on/hatch branch)

the_player_verb = invoked_verb_name(verb_name)

print(
    "There is a noticeable crunch from beneath you, and inspection reveals\nthat the egg is lying open, badly damaged.",
    end="",
)
# ZIL: <BAD-EGG ...>
_.zork_thing.bad_egg()
print()
return
