#!moo verb open mung destroy break smash crack --on "jewel-encrusted egg" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, lookup

# ZIL routine: EGG-OBJECT (open/mung branch)

parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if prso == this:
    if prso.flag("open") if prso else None:
        print("The egg is already open.")
        return
    elif not prsi:
        print("You have neither the tools nor the expertise.")
        return
    elif prsi == lookup("hands"):
        print("I doubt you could do that without damaging it.")
        return
    elif (
        (prsi.flag("weapon") if prsi else None)
        or (prsi.flag("toolbit") if prsi else None)
        or the_player_verb in ["mung", "destroy", "break", "smash", "crack"]
    ):
        print(
            "The egg is now open, but the clumsiness of your attempt has seriously\ncompromised its esthetic appeal.",
            end="",
        )
        # ZIL: <BAD-EGG ...>
        _.zork_thing.bad_egg()
        print()
        return
    elif prso.flag("hostile") if prso else None:
        print("Not to say that using the " + (prsi.desc() if prsi else "") + " isn't original too...")
        return
    else:
        print("The concept of using a " + (prsi.desc() if prsi else "") + " is certainly original.")
        return prso.set_flag("hostile", True) if prso else None
return passthrough()
