#!moo verb open mung destroy break smash crack --on "jewel-encrusted egg" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: EGG-OBJECT (open/mung branch)

parser = context.parser
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if (parser.get_dobj() if parser.has_dobj_str() else None) == this:
    if (parser.get_dobj() if parser.has_dobj_str() else None).flag("open"):
        print("The egg is already open.")
        return
    elif not (parser.get_iobj() if parser.has_iobj() else None):
        print("You have neither the tools nor the expertise.")
        return
    elif (parser.get_iobj() if parser.has_iobj() else None) == lookup("hands"):
        print("I doubt you could do that without damaging it.")
        return
    elif (
        (parser.get_iobj().flag("weapon") if parser.has_iobj() else None)
        or (parser.get_iobj().flag("toolbit") if parser.has_iobj() else None)
        or the_player_verb in ["mung", "destroy", "break", "smash", "crack"]
    ):
        print(
            "The egg is now open, but the clumsiness of your attempt has seriously\ncompromised its esthetic appeal.",
            end="",
        )
        # ZIL: <BAD-EGG ...>
        _.zork_thing.bad_egg()
        print()
        return
    elif (parser.get_dobj() if parser.has_dobj_str() else None).flag("hostile"):
        print(
            "Not to say that using the "
            + (parser.get_iobj().desc() if parser.has_iobj() else "")
            + " isn't original too..."
        )
        return
    else:
        print(
            "The concept of using a "
            + (parser.get_iobj().desc() if parser.has_iobj() else "")
            + " is certainly original."
        )
        return (parser.get_dobj() if parser.has_dobj_str() else None).set_flag("hostile", True)
return passthrough()
