#!moo verb examine x describe what --on "zorkmid" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: ZORKMID-FUNCTION (examine branch)

the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

print("The zorkmid is the unit of currency of the Great Underground Empire.")
return
