#!moo verb find where --on "zorkmid" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: ZORKMID-FUNCTION (find branch)

the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

print("The best way to find zorkmids is to go out and look for them.")
return
