#!moo verb zorkmid_function --on "zorkmid" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

# ZIL: ZORKMID-FUNCTION / combined OBJECT-FUNCTION dispatch
# Invoked by ``_.thing.dispatch_object_function(obj, verb, prep, iobj)``
# which looks up ``obj.action`` and calls ``obj.invoke_verb(action_atom, ...)``.

the_verb = args[0] if len(args) > 0 else None
prep = args[1] if len(args) > 1 else None
iobj = args[2] if len(args) > 2 else None
the_player_verb = the_verb

if the_verb == "examine":
    print("The zorkmid is the unit of currency of the Great Underground Empire.")
    return
elif the_verb == "find":
    print("The best way to find zorkmids is to go out and look for them.")
    return
return False
