#!moo verb climb-down --on "rope" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context

# ZIL routine: ROPE-FUNCTION (climb-down branch)

player = context.player
parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
rloc = 0
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if prso in (this, player.zstate_get("ROOMS")) and player.zstate_get("DOME-FLAG"):
    return _.walk(player.zstate_get("P?DOWN"))
return passthrough()
