#!moo verb drop --on "rope" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: ROPE-FUNCTION (drop branch)

player = context.player
rloc = 0
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if player.here() == lookup("dome_room") and not player.zstate_get("DOME-FLAG"):
    this.moveto(lookup("torch_room"))
    print("The rope drops gently to the floor below.")
    return
return passthrough()
