#!moo verb take get pick --on "rope" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name

# ZIL routine: ROPE-FUNCTION (take branch)

player = context.player
rloc = 0
the_player_verb = invoked_verb_name(verb_name)

if player.zstate_get("DOME-FLAG"):
    print("The rope is tied to the railing.")
    return
return passthrough()
