#!moo verb take get pick --on "rope" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: ROPE-FUNCTION (take branch)

player = context.player
rloc = 0
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if player.zstate_get("DOME-FLAG"):
    print("The rope is tied to the railing.")
    return
return passthrough()
