#!moo verb tie attach fasten --on "rope" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, lookup

# ZIL routine: ROPE-FUNCTION (tie branch)

player = context.player
parser = context.parser
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
rloc = 0
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if prsi == lookup("railing"):
    if player.zstate_get("DOME-FLAG"):
        print("The rope is already tied to it.")
        return
    else:
        print("The rope drops over the side and comes within ten feet of the floor.")
        player.zstate_set("DOME-FLAG", True)
        this.set_flag("ndescbit", True)
        rloc = this.location
        if not rloc or not rloc.location == player.zstate_get("ROOMS"):
            return this.moveto(player.here())
return passthrough()
