#!moo verb tie-up --on "rope" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context

# ZIL routine: ROPE-FUNCTION (tie-up branch)

parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
rloc = 0
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if this == prsi:
    if prso.flag("actorbit") if prso else None:
        if (prso.getp("strength") if prso else None) < 0:
            print("Your attempt to tie up the " + (prso.desc() if prso else "") + " awakens him.", end="")
            # ZIL: <AWAKEN ...>
            return _.zork_thing.awaken(prso)
        else:
            print("The " + (prso.desc() if prso else "") + " struggles and you cannot tie him up.")
            return
    else:
        print("Why would you tie up a " + (prso.desc() if prso else "") + "?")
        return
return passthrough()
