#!moo verb untie --on "rope" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: ROPE-FUNCTION (untie branch)

player = context.player
rloc = 0
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if player.zstate_get("DOME-FLAG"):
    player.zstate_set("DOME-FLAG", False)
    this.set_flag("ndescbit", False)
    print("The rope is now untied.")
    return
else:
    print("It is not tied to anything.")
    return
