#!moo verb untie --on "rope" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name

# ZIL routine: ROPE-FUNCTION (untie branch)

player = context.player
rloc = 0
the_player_verb = invoked_verb_name(verb_name)

if player.zstate_get("DOME-FLAG"):
    player.zstate_set("DOME-FLAG", False)
    this.set_flag("ndescbit", False)
    print("The rope is now untied.")
    return
else:
    print("It is not tied to anything.")
    return
