#!moo verb treasure_room_fcn --on "Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: TREASURE-ROOM-FCN
# params: RARG

player = context.player
thief = lookup("thief")
rarg = args[0] if len(args) > 0 else None

if rarg == "M-ENTER" and _.table_get(None, player.zstate_get("C-ENABLED?")) == 1 and not player.zstate_get("DEAD"):
    if not thief.location == player.here():
        print(
            "You hear a scream of anguish as you violate the robber's hideaway.\nUsing passages unknown to you, he rushes to its defense."
        )
        thief.moveto(player.here())
    thief.set_flag("hostile", True)
    thief.set_flag("invisible", False)
    # ZIL: <THIEF-IN-TREASURE ...>
    return _.thing.thief_in_treasure()
