#!moo verb examine x describe what --on "sword" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import invoked_verb_name

# ZIL routine: SWORD-FCN (examine branch)

g = 0
the_player_verb = invoked_verb_name(verb_name)

if (g := this.getp("tvalue")) == 1:
    print("Your sword is glowing with a faint blue glow.")
    return
elif g == 2:
    print("Your sword is glowing very brightly.")
    return
return passthrough()
