#!moo verb sword_fcn --on "sword" --dspec none

# Generated by moo/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL: SWORD-FCN / combined OBJECT-FUNCTION dispatch
# Invoked by ``_.thing.dispatch_object_function(obj, verb, prep, iobj)``
# which looks up ``obj.action`` and calls ``obj.invoke_verb(action_atom, ...)``.

player = context.player
the_verb = args[0] if len(args) > 0 else None
prep = args[1] if len(args) > 1 else None
iobj = args[2] if len(args) > 2 else None
g = 0
the_player_verb = the_verb

if the_verb == "take":
    if player == player:
        _.queue("i-sword", -1)
    return False
elif the_verb == "examine":
    if (g := this.getp("tvalue")) == 1:
        print("Your sword is glowing with a faint blue glow.")
        return
    elif g == 2:
        print("Your sword is glowing very brightly.")
        return
return False
