#!moo verb take get pick --on "sword" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name

# ZIL routine: SWORD-FCN (take branch)

player = context.player
g = 0
the_player_verb = invoked_verb_name(verb_name)

if player == player:
    _.queue("i-sword", -1)
return passthrough()
