#!moo verb dig --on "ground" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import invoked_verb_name

# ZIL routine: GROUND-FUNCTION (dig branch)

the_player_verb = invoked_verb_name(verb_name)

print("The ground is too hard for digging here.")
return
