#!moo verb put place insert put-on --on "ground" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context

# ZIL routine: GROUND-FUNCTION (put/put-on branch)

parser = context.parser
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if (parser.get_iobj() if parser.has_iobj() else None) == this:
    _.perform("drop", (parser.get_dobj() if parser.has_dobj_str() else None), None)
    return True
return passthrough()
