#!moo verb basket_f --on "Thing" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import NoSuchObjectError, context, lookup

# ZIL routine: BASKET-F

parser = context.parser
try:
    prso = parser.get_dobj() if parser.has_dobj_str() else None
except NoSuchObjectError:
    prso = None
try:
    prsi = parser.get_iobj() if parser.has_iobj() else None
except NoSuchObjectError:
    prsi = None
lowered_basket = lookup("lowered_basket")

if prso == lowered_basket or prsi == lowered_basket:
    print("The basket is at the other end of the chain.")
    return
return passthrough()
