#!moo verb raise --on "basket (RAISED-BASKET)" --dspec this

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, invoked_verb_name, lookup

# ZIL routine: BASKET-F (raise branch)

player = context.player
the_player_verb = invoked_verb_name(verb_name)

if player.zstate_get("CAGE-TOP"):
    print(_.pick(player.zstate_get("DUMMY")))
    return
else:
    this.moveto(lookup("shaft_room"))
    lookup("lowered_basket").moveto(lookup("lower_shaft"))
    player.zstate_set("CAGE-TOP", True)
    # ZIL: <THIS-IS-IT ...>
    _.thing.this_is_it(this)
    print("The basket is raised to the top of the shaft.")
    return
