#!moo verb take get pick --on "basket (RAISED-BASKET)" --dspec either

# Generated by extras/zil_import — do not edit by hand
# pylint: disable=return-outside-function,undefined-variable,no-name-in-module

from moo.sdk import context, lookup

# ZIL routine: BASKET-F (take branch)

parser = context.parser
the_player_verb = context.parser.words[0].lower() if context.parser is not None and context.parser.words else verb_name

if (parser.get_dobj() if parser.has_dobj_str() else None) in (this, lookup("lowered_basket")):
    print("The cage is securely fastened to the iron chain.")
    return
return passthrough()
